const fs = require("fs");
const path = require("path");
const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

// ====== TRANSLATIONS FOR BATCH 001 (questions 200-399, trade cmrbe6r1d0000eap3fmyxpqfo) ======
// Format: { "batchIdx": [question, options_array, explanation] }
const BATCH_001 = {
  "0": ["A 200 A panel with a 30 A backup generator. The 120% busbar rule:", ["200 A ≤ 240 A OK", "230 A ≤ 240 A OK", "200 A + 30 A = 230 A ≥ 240 A NO", "200 A × 1.2 = 240 A, 200+30=230 ≤ 240 OK"], "200 × 1.2 = 240 A. 200 + 30 = 230 ≤ 240, so 200 A × 1.2 = 240 A, 200+30=230 ≤ 240 OK."],
  "1": ["An installation with Icc = 25 kA requires a breaker with an interrupting capacity of at least:", ["10 kA", "14 kA", "22 kA", "25 kA"], "The interrupting capacity must be ≥ the available short-circuit current (25 kA)."],
  "2": ["What is fault loop impedance?", ["Earth resistance", "Total impedance of the fault path", "Neutral impedance", "Cable capacitance"], "The total impedance of the fault path, including source, conductors, and fault return path."],
  "3": ["A 24 A continuous load + 10 A non-continuous load. Sizing current?", ["34 A", "36 A", "40 A", "44 A"], "24 A × 1.25 + 10 A = 30 + 10 = 40 A."],
  "4": ["Surge Protective Device (SPD) is mandatory in Quebec for:", ["All buildings", "Buildings with solar panels", "New residential buildings", "Industrial buildings only"], "New residential buildings require SPD per Quebec regulation."],
  "5": ["A 5 A breaker for a 347 V lighting circuit. This is:", ["Too small", "Correct", "Too large", "Depends on the load"], "5 A at 347 V = 1,735 VA, sufficient for lighting circuits."],
  "6": ["A 10 HP, 600 V motor, FLA = 9 A. Type D breaker = ?", ["15 A", "20 A", "25 A", "30 A"], "250% × 9 = 22.5 → next standard size up = 25 A. But wait: 9 × 2.5 = 22.5 A, next size = 25 A."],
  "7": ["The energy-limiting function of a breaker serves to:", ["Limit voltage", "Limit fault current", "Limit the electrical arc", "Limit power"], "Energy-limiting breakers reduce the fault current let-through to protect downstream equipment."],
  "8": ["Two 20 A breakers in parallel on the same circuit:", ["Give 40 A", "Are prohibited", "Double safety", "Are permitted in residential"], "Parallel breakers are prohibited by Code — each breaker must protect its own circuit."],
  "9": ["A combined 20 A GFCI breaker protects against:", ["Overload + short circuit only", "Ground faults only", "Overload, short circuit AND ground faults", "Overvoltages only"], "A combined GFCI breaker provides overload protection, short-circuit protection, AND ground fault protection."],
  "10": ["What is FLA (Full Load Amps) of a motor?", ["Starting current", "Full load current", "No-load current", "Short-circuit current"], "FLA is the current drawn by the motor when operating at its rated full load."],
  "11": ["LRA stands for:", ["Low Running Amps", "Locked Rotor Amps", "Load Rated Amps", "Line Return Amps"], "LRA = Locked Rotor Amps — the current when the rotor is stationary at full voltage."],
  "12": ["A standard three-phase induction motor has a typical LRA of:", ["2-3× FLA", "5-8× FLA", "10-12× FLA", "15-20× FLA"], "Typical LRA for an induction motor is 5-8 times FLA."],
  "13": ["A VFD (variable frequency drive) allows:", ["Changing voltage", "Varying motor speed", "Increasing torque", "Reducing power"], "A VFD varies the frequency to control AC motor speed."],
  "14": ["Which device protects a motor against thermal overloads?", ["Standard breaker", "Thermal overload relay", "Disconnect switch", "Fast-acting fuse"], "The thermal overload relay protects the motor from overheating due to prolonged overcurrent."],
  "15": ["Maximum distance between a disconnect switch and its motor:", ["3 m", "6 m", "9 m", "12 m"], "Art. 28-600: 9 m (30 ft) within sight of the motor."],
  "16": ["What is the most common type of motor used in industry?", ["DC motor", "Squirrel cage induction motor", "Synchronous motor", "Universal motor"], "The squirrel cage induction motor is the most widely used due to its simplicity and robustness."],
  "17": ["A contactor in a motor circuit is used to:", ["Protect against overloads", "Remotely switch the circuit", "Measure current", "Reduce voltage"], "A contactor allows remote switching of the motor circuit via a control signal."],
  "18": ["A 5 HP, 240 V single-phase motor, FLA = 28 A. Conductor size?", ["10 AWG", "8 AWG", "6 AWG", "4 AWG"], "125% × 28 = 35 A. 8 AWG at 60 °C = 40 A, adequate."],
  "19": ["Conductors supplying a motor must be sized at:", ["100% of FLA", "125% of FLA", "150% of FLA", "200% of FLA"], "Art. 28-106: motor supply conductors at 125% of FLA."],
  "20": ["Motor overload protection is set at a maximum of:", ["100% of FLA", "115-125% of FLA", "150% of FLA", "200% of FLA"], "Overload relays are typically set at 115-125% of the motor FLA."],
  "21": ["A three-phase motor loses a phase while running:", ["Nothing", "It runs normally", "Current increases 200-300%, risk of damage", "It stops"], "The motor continues running on 2 phases but current can reach 200-300% of FLA, risking damage."],
  "22": ["A 20 HP, 600 V three-phase motor, FLA = 20 A. Type D motor breaker?", ["20 A", "30 A", "40 A", "50 A"], "250% × 20 = 50 A, next standard size = 50 A. Actually: 20 × 2.5 = 50 A."],
  "23": ["A motor disconnect switch must be visible from the motor within:", ["3 m", "6 m", "9 m", "15 m"], "Art. 28-600: within 9 m (30 ft) and in sight of the motor."],
  "24": ["The efficiency of a standard electric motor is generally between:", ["60-70%", "70-80%", "80-92%", "93-98%"], "Standard efficiency motors range from 80-92% depending on size and design."],
  "25": ["A 10 HP, 600 V motor. Approximate full load current?", ["8 A", "9 A", "11 A", "14 A"], "Approx. FLA = 10 HP × 746 / (600 × √3 × 0.85 × 0.85) ≈ 11 A."],
  "26": ["What is a star-delta starter?", ["Changes voltage", "Reduces starting current by changing winding configuration", "Increases power", "Changes frequency"], "A star-delta starter connects the motor windings in star for starting (reduced current), then switches to delta for full power."],
  "27": ["A 3 HP, 240 V motor, FLA = 9 A. Thermal relay set to?", ["9 A", "10-11 A", "15 A", "20 A"], "The overload relay is set at 115-125% of FLA = 10.35-11.25 A ≈ 10-11 A."],
  "28": ["Premium Efficiency motors reduce:", ["Speed", "Joule and magnetic losses", "Torque", "FLA"], "Premium motors are designed to reduce joule (I²R) and magnetic (core) losses."],
  "29": ["A VFD typically receives as input:", ["DC", "Three-phase AC 60 Hz", "Single-phase AC", "Regulated DC"], "VFDs typically take three-phase AC 60 Hz and convert it to DC, then to variable-frequency AC."],
  "30": ["To reverse the rotation direction of a three-phase motor:", ["Change voltage", "Swap two phases", "Change frequency", "Add a capacitor"], "Swapping any two phase connections reverses the rotation of a three-phase motor."],
  "31": ["The service factor (SF) of a motor indicates:", ["Speed", "Continuous overload capacity", "Efficiency", "Torque"], "The service factor is a multiplier indicating how much continuous overload the motor can handle."],
  "32": ["A 50 HP, 600 V three-phase motor, cos φ = 0.88, efficiency = 0.92. Current?", ["42 A", "48 A", "54 A", "60 A"], "I = (50 × 746) / (√3 × 600 × 0.88 × 0.92) = 37,300 / 841 = 44.3 A ≈ 48 A."],
  "33": ["What type of motor starter gives the smoothest start?", ["Direct-on-line", "Star-delta", "Soft starter", "Auto-transformer"], "A soft starter provides smooth, controlled acceleration by ramping up the voltage."],
  "34": ["A 15 kW, 600 V motor, cos φ = 0.85. Approximate FLA?", ["14 A", "17 A", "20 A", "24 A"], "FLA = 15,000 / (√3 × 600 × 0.85) = 15,000 / 883 = 17 A."],
  "35": ["The number of poles of a motor determines:", ["Torque", "Synchronous speed", "FLA", "LRA"], "Synchronous speed = 120 × f / P, where P is the number of poles."],
  "36": ["A 2-pole motor at 60 Hz runs at a synchronous speed of:", ["1,800 RPM", "3,000 RPM", "3,600 RPM", "7,200 RPM"], "Ns = 120 × 60 / 2 = 3,600 RPM."],
  "37": ["A 4-pole motor at 60 Hz has a synchronous speed of:", ["900 RPM", "1,200 RPM", "1,800 RPM", "3,600 RPM"], "Ns = 120 × 60 / 4 = 1,800 RPM."],
  "38": ["A 100 HP, 600 V motor, FLA = 100 A, service factor 1.15. Conductor?", ["2 AWG", "1 AWG", "1/0 AWG", "2/0 AWG"], "125% × 100 = 125 A. 1/0 AWG at 75 °C = 150 A. Adequate."],
  "39": ["Slip of a 1,800 RPM rated induction motor, measured at 1,750 RPM:", ["1.4%", "2.8%", "3.5%", "5.0%"], "Slip = (1800-1750)/1800 = 50/1800 = 2.8%."],
  "40": ["A 30 HP, 600 V motor, FLA = 32 A. Maximum breaker allowed (250% of FLA)?", ["60 A", "70 A", "80 A", "90 A"], "250% × 32 = 80 A. Maximum breaker size = 80 A."],
  "41": ["A VFD with a 100 m motor cable can cause:", ["No problem", "Wave reflections and voltage spikes at motor terminals", "Excessive heating", "Power loss"], "Long motor cable runs with VFDs can cause wave reflections, causing voltage spikes at the motor."],
  "42": ["For a star-delta motor start, the starting current in star is:", ["Equal to direct-on-line", "33% of direct-on-line", "50% of direct-on-line", "100% of direct-on-line"], "In star configuration, the voltage across each winding is 1/√3 of line voltage, so current is about 33% of DOL."],
  "43": ["A 10 HP, 240 V single-phase motor, FLA = 50 A. Conductor?", ["8 AWG", "6 AWG", "4 AWG", "3 AWG"], "125% × 50 = 62.5 A. 6 AWG at 75 °C = 65 A."],
  "44": ["Class F motor insulation tolerates a maximum temperature of:", ["130 °C", "155 °C", "180 °C", "200 °C"], "Class F insulation is rated for 155 °C maximum operating temperature."],
  "45": ["A three-phase 600 V, 50 HP motor, efficiency 0.90, cos φ 0.85. Active power input?", ["37.3 kW", "41.4 kW", "45.2 kW", "50.0 kW"], "P_input = (50 × 746) / 0.90 = 41,444 W ≈ 41.4 kW."],
  "46": ["Maximum acceptable starting time for a motor protected by a thermal relay:", ["3 s", "5 s", "10 s", "20 s"], "Thermal relays allow starting times up to 20 s for standard motors."],
  "47": ["The starting current (LRA) of a 5 HP 240 V single-phase motor (FLA = 28 A) is approximately:", ["50-80 A", "100-150 A", "140-224 A", "200-280 A"], "LRA = 5-8 × FLA = 5-8 × 28 = 140-224 A."],
  "48": ["A motor must have a disconnect with fuse or breaker within 9 m. Which article?", ["Art. 14-100", "Art. 26-700", "Art. 28-600", "Art. 46-200"], "Art. 28-600 requires the disconnecting means within sight of the motor."],
  "49": ["For a motor with a mechanical brake, the disconnect must:", ["Also cut the brake", "Be lockable", "Be within 3 m", "Be type C"], "The disconnect must disconnect both the motor and the brake simultaneously."],
  "50": ["Which component converts solar energy into electricity?", ["Inverter", "Photovoltaic cell", "Battery", "Charge controller"], "The photovoltaic cell converts sunlight directly into electricity via the photovoltaic effect."],
  "51": ["What is the purpose of an inverter in a PV system?", ["Produce current", "Convert DC to AC", "Store energy", "Regulate temperature"], "The inverter converts DC from solar panels into grid-compatible AC."],
  "52": ["Which panel type offers the best efficiency?", ["Polycrystalline", "Monocrystalline", "Thin film", "Amorphous silicon"], "Monocrystalline panels offer 18-22% efficiency."],
  "53": ["What is net metering?", ["A type of panel", "Net measurement — credit for energy fed into the grid", "A safety device", "A charge controller"], "Net metering credits solar energy fed into the Hydro-Québec grid."],
  "54": ["Typical efficiency of a modern monocrystalline solar panel:", ["12-15%", "15-18%", "18-22%", "25-30%"], "Modern monocrystalline panels have efficiencies of 18-22%."],
  "55": ["A micro-inverter is distinguished by:", ["Its high power", "Integration at each panel", "Its very low price", "Its liquid cooling"], "Micro-inverters are installed on each individual panel, allowing per-panel MPPT optimization."],
  "56": ["What is the Voc voltage of a solar panel?", ["Operating voltage", "Open circuit voltage", "Rated voltage", "Breakdown voltage"], "Voc = Open circuit voltage — the voltage when no load is connected, typically measured at STC."],
  "57": ["Solar energy in Quebec is most productive in:", ["Winter (snow reflection)", "Summer (more sunlight hours)", "Fall", "Spring"], "Summer provides the most sunlight hours and highest production."],
  "58": ["The 120% rule for PV in Quebec applies to:", ["Electric meter", "Main panel busbar", "Panel cable", "Solar breaker"], "The 120% rule limits the total connected load to 120% of the main panel busbar rating."],
  "59": ["200 A panel, 40 A inverter. 120% rule:", ["200 A + 40 A = 240 A ≤ 240 A OK", "200 A + 40 A = 240 A > 200 A NO", "200 A × 1.2 = 240 A, 200+40=240 OK", "40 A ≤ 200 A OK"], "200 × 1.2 = 240. 200 + 40 = 240 ≤ 240 → OK."],
  "60": ["The temperature coefficient of power (γ) of a panel is typically:", ["Positive (+0.4%/°C)", "Negative (-0.4%/°C)", "Zero", "Variable"], "Panel power decreases as temperature increases, giving a negative coefficient of about -0.4%/°C."],
  "61": ["The minimum design temperature for panel sizing in Quebec is:", ["-20 °C", "-30 °C", "-40 °C", "-50 °C"], "Quebec's design minimum temperature is -40 °C."],
  "62": ["A PV system with backup battery requires an inverter:", ["Standard", "Bidirectional with islanding capability", "Micro-inverter", "Centralized"], "A battery-based system needs a bidirectional inverter with islanding (off-grid) capability."],
  "63": ["What is rapid shutdown for in a PV system?", ["Turn off the system at night", "Reduce panel voltage in case of emergency for firefighter safety", "Increase production", "Protect against lightning"], "Rapid shutdown reduces PV conductor voltage to safe levels for firefighters."],
  "64": ["The maximum voltage of a string of panels must be calculated at:", ["25 °C", "-10 °C", "The minimum site temperature", "STC (25 °C)"], "Panel voltage increases as temperature decreases, so max voltage is calculated at minimum site temperature."],
  "65": ["A standard solar panel has a Voc of about 40 V. How many in series for a 600 V inverter (max 600 V)?", ["12", "13", "14", "15"], "600 / 40 = 15, but with cold temperature correction, max is typically 12-13 panels."],
  "66": ["The conductor size between panels and inverter depends on:", ["Panel power only", "Short-circuit current Isc × 1.25", "Grid voltage", "Frequency"], "PV source circuit conductors must be sized at 125% of Isc."],
  "67": ["The difference between a central inverter and micro-inverters is:", ["Price only", "Per-panel optimization (micro) vs centralized (central)", "Total power", "Output voltage"], "Micro-inverters optimize each panel individually; central inverters handle all panels together."],
  "68": ["The short-circuit current Isc of a typical 400 W panel is approximately:", ["5 A", "10 A", "15 A", "20 A"], "A typical 400 W panel has Vmp ≈ 40 V, Imp ≈ 10 A, Isc ≈ 10-11 A."],
  "69": ["A 10 kWp PV installation in Quebec can produce annually approximately:", ["5,000 kWh", "10,000-12,000 kWh", "15,000-20,000 kWh", "25,000 kWh"], "In Quebec, 1 kWp produces about 1,000-1,200 kWh/year, so 10 kWp produces 10,000-12,000 kWh."],
  "70": ["A power optimizer differs from a micro-inverter because:", ["It is cheaper", "It does not convert to AC — it sends conditioned DC", "It is more efficient", "It is smaller"], "A power optimizer conditions DC voltage per panel but sends DC to a central inverter."],
  "71": ["A breaker for a PV DC circuit must be:", ["Standard AC", "DC (direct current) specific", "AFCI", "GFCI"], "DC breakers are specially designed to interrupt DC arcs, which are harder to extinguish than AC arcs."],
  "72": ["In a PV system with battery, the MPPT charge controller:", ["Regulates temperature", "Optimizes energy transfer from panels to battery", "Converts to AC", "Measures production"], "MPPT (Maximum Power Point Tracking) maximizes the power extracted from the solar panels."],
  "73": ["Temperature correction factor for a panel at 60 °C (vs 25 °C STC) is approximately:", ["0.90", "0.86", "0.80", "0.75"], "Power drops ~0.4%/°C, so at 60 °C (35 °C above STC): 1 - (0.004 × 35) = 0.86."],
  "74": ["Minimum size of the ground conductor for a PV system:", ["14 AWG", "12 AWG", "10 AWG", "8 AWG"], "The minimum ground conductor for PV systems is 8 AWG copper."],
  "75": ["Rapid shutdown must reduce the voltage outside the PV array to:", ["≤ 120 V in 10 s", "≤ 30 V in 30 s", "≤ 600 V in 5 s", "≤ 50 V in 60 s"], "NEC 690.12 requires ≤ 30 V within 30 s outside the PV array boundary."],
  "76": ["For a PV installation with self-consumption and battery, the inverter must:", ["Be bidirectional", "Have an anti-islanding relay", "Be connected to the meter", "All of these answers"], "A battery-based self-consumption inverter must be bidirectional, have anti-islanding, and connect to the meter."],
  "77": ["Optimal tilt angle for solar panels in Quebec:", ["0° (horizontal)", "15-20°", "35-45°", "60-75°"], "Quebec's latitude is ~45°N, so optimal tilt is 35-45° for year-round production."],
  "78": ["400 W panel, Voc = 49.6 V, Voc coefficient = -0.27%/°C. Maximum voltage at -40 °C?", ["51.2 V", "55.4 V", "58.3 V", "62.1 V"], "ΔT = -40 - 25 = -65 °C. Voc_max = 49.6 × (1 + (-0.0027 × -65)) = 49.6 × 1.1755 = 58.3 V."],
  "79": ["15 panels in series at -40 °C (Voc_max = 58.3 V each). Total voltage?", ["744 V", "812 V", "875 V", "923 V"], "15 × 58.3 = 874.5 V ≈ 875 V."],
  "80": ["400 W panel, Vmp = 41.2 V, Imp = 9.71 A. For a 600 V inverter, how many in series (max 600 V ÷ 41.2)?", ["8", "9", "10", "11"], "600 / 41.2 = 14.5. But considering cold temp correction, typically max 10 panels."],
  "81": ["200 A panel, 40 A solar inverter. Which rule applies for the busbar?", ["200 + 40 ≤ 200", "200 + 40 ≤ 240 (120% of 200)", "200 ≤ 200", "40 ≤ 200"], "The 120% rule: 200 + 40 = 240 ≤ 120% × 200 = 240 → OK."],
  "82": ["A 15 kWp PV system with 15 kW three-phase 208 V inverter. Max AC current?", ["41.7 A", "52.0 A", "72.2 A", "83.3 A"], "I = 15,000 / (√3 × 208) = 15,000 / 360 = 41.7 A."],
  "83": ["Anti-islanding protection of a PV inverter must detect grid loss within:", ["0.5 s", "1 s", "2 s", "5 s"], "Anti-islanding protection must detect grid disconnection within 2 seconds per CSA C22.2 107.1."],
  "84": ["15 panels of 400 W in 3 strings of 5. Isc = 10.4 A per panel. Total Isc per combiner?", ["10.4 A", "13 A", "31.2 A", "52 A"], "Per string: Isc = 10.4 A. Total Isc into combiner = 3 × 10.4 = 31.2 A."],
  "85": ["The DC conductor between combiner and inverter must be sized at:", ["100% of Isc × 1", "125% of total Isc", "150% of total Isc", "200% of total Isc"], "PV output circuits must be sized at 125% of the rated short-circuit current."],
  "86": ["A 10 kWp PV installation, annual production 12,000 kWh. Annual savings at $0.07/kWh:", ["$500", "$840", "$1,200", "$2,000"], "12,000 × $0.07 = $840/year."],
  "87": ["Maximum spacing between two rows of panels to avoid mutual shading at winter solstice:", ["Equal to height", "1.5× height", "2-3× height", "4× height"], "Row spacing should be 2-3× the height difference to avoid shading at the winter solstice."],
  "88": ["A 10 kW PV inverter connected to a 200 A panel. Is the 120% rule respected if the inverter breaker is 50 A?", ["Yes: 200+50 = 250 > 240, no", "No: 200+50 = 250 > 240 (120%×200)", "Yes: 200 ≥ 50", "No: 50 > 40"], "200 + 50 = 250 > 240 (120% of 200). No, the 120% rule is NOT respected."],
  "89": ["Typical annual degradation of a monocrystalline panel:", ["0.1-0.2%", "0.3-0.5%", "0.7-1.0%", "2-3%"], "Monocrystalline panels typically degrade 0.3-0.5% per year."],
  "90": ["What are the two most common types of smoke detectors?", ["Thermal and ionization", "Ionization and optical (photoelectric)", "Laser and ultrasonic", "Capacitive and magnetic"], "Ionization (fast-flaming fires) and optical/photoelectric (smoldering fires) are most common."],
  "91": ["Which standard governs fire alarm system installation in Canada?", ["CSA C22.1", "CAN/ULC-S524", "NEC 70", "BNQ 3000"], "CAN/ULC-S524 covers fire alarm system installation in Canada."],
  "92": ["A smoke detector must be installed:", ["On the ceiling or high on the wall", "Near the floor", "Behind a door", "In a closet"], "Smoke rises, so detectors are placed on the ceiling or high on walls."],
  "93": ["What does PIR mean in a motion detector?", ["Pulse Infrared Receiver", "Passive Infrared", "Power Interface Relay", "Positive Impulse Response"], "PIR = Passive Infrared — detects changes in infrared radiation from moving warm bodies."],
  "94": ["IP surveillance cameras typically use:", ["120 V AC direct", "PoE via network cable", "Internal battery", "Solar panel"], "Power over Ethernet (PoE) supplies both power and data via the network cable."],
  "95": ["A smoke alarm must emit a sound level of at least:", ["65 dB", "75 dB", "85 dB", "95 dB"], "Smoke alarms must produce at least 85 dB at 3 m."],
  "96": ["Minimum backup battery autonomy for a fire alarm panel:", ["4 h", "8 h", "12 h", "24 h"], "Standards require 24 hours of backup battery for fire alarm panels."],
  "97": ["A smoke detector must NOT be installed:", ["In a corridor", "In a corner of a room", "Near an air vent", "On the ceiling"], "Smoke detectors should not be installed near air vents/diffusers where airflow may prevent smoke from reaching them."],
  "98": ["A Class A loop in a fire alarm system:", ["Is an open loop", "Has a return to the panel (redundancy)", "Is unmonitored", "Uses a single wire pair"], "Class A has a redundant return path to the panel — if a wire breaks, the loop still functions."],
  "99": ["A Class B fire alarm loop:", ["Has a return to the panel", "Has an end-of-line resistor (EOL)", "Is fully redundant", "Does not need a panel"], "Class B loops terminate with an end-of-line resistor (EOL) that supervises the wiring integrity."],
  "100": ["A smoke detector in each bedroom must be installed within:", ["1 m of the door", "3 m of the door", "5 m of the door", "No requirement"], "Smoke detectors must be within 3 m of each bedroom door."],
  "101": ["Fire alarm loop cable must be:", ["Standard NMD90", "Fire-resistant cable (FPL, riser)", "Cat5e", "TECK90"], "Fire alarm circuits require specialty fire-resistant cable."],
  "102": ["What is the maximum number of smoke detectors per circuit?", ["6", "12", "18", "24"], "Maximum 12 smoke detectors per circuit."],
  "103": ["A heat detector (thermovelocimetric) triggers at:", ["45 °C", "57 °C or 93 °C", "120 °C", "200 °C"], "Heat detectors are typically rated at 57 °C (135 °F) or 93 °C (200 °F)."],
  "104": ["An outdoor IP camera must have a minimum IP classification:", ["IP20", "IP54", "IP65", "IP68"], "IP65 is the minimum for outdoor use — dust-tight and protected against water jets."],
  "105": ["Maximum distance between a smoke detector and the ceiling for wall mounting:", ["100 mm", "200 mm", "300 mm", "500 mm"], "When wall-mounted, the top of the detector must be 300 mm (12 in) from the ceiling."],
  "106": ["What is a Class B, Class A alarm system?", ["Class B for detectors, Class A for notification", "Class B for one floor, Class A for another", "Mixed by zones", "Class A everywhere"], "A Class B detection loop with Class A notification circuits."],
  "107": ["A delay device (DACUM) in a security system serves to:", ["Detect intrusions", "Delay alarm transmission for verification", "Increase sound volume", "Save battery"], "A delay device gives time to disarm before the alarm is transmitted."],
  "108": ["Standby (quiescent) current of a typical smoke detector:", ["1-5 mA", "50-100 µA", "10-20 mA", "100-200 mA"], "Modern smoke detectors draw very low standby current: 50-100 µA."],
  "109": ["In a 3-story building, smoke detectors must be interconnected:", ["Per floor only", "Throughout the entire building", "Only on the ground floor", "Per fire zone"], "Detectors must be interconnected throughout the entire building."],
  "110": ["A sprinkler system is mandatory in Quebec for buildings over:", ["3 stories or 2,000 m²", "6 stories or 4,000 m²", "2 stories or 1,000 m²", "8 stories or 6,000 m²"], "Sprinklers are required for buildings over 3 stories or 2,000 m²."],
  "111": ["A manual pull station (manual alarm) must be installed at:", ["1.2 m from the floor", "1.5 m from the floor", "1.8 m from the floor", "2.0 m from the floor"], "Manual pull stations are installed at 1.2 m (48 in) from the floor."],
  "112": ["The recommended cable type for PoE cameras is:", ["Cat5e or Cat6", "RG59 coaxial", "2-conductor alarm cable", "NM-B electrical cable"], "PoE cameras use Cat5e or Cat6 network cable for both data and power."],
  "113": ["Maximum distance of a PoE (Cat6) cable between switch and camera:", ["50 m", "100 m", "150 m", "200 m"], "The maximum PoE cable run is 100 m (328 ft)."],
  "114": ["An ionization smoke detector contains what radioactive source?", ["Uranium", "Americium 241", "Cesium 137", "Cobalt 60"], "Ionization detectors use Americium 241 (Am-241) as an alpha particle source."],
  "115": ["For an intrusion alarm system, magnetic contacts are placed on:", ["Walls", "Doors and windows", "Ceilings", "Floors"], "Magnetic contacts detect when doors or windows are opened."],
  "116": ["Typical power supply voltage for a fire alarm panel:", ["12 V DC or 24 V DC", "120 V AC", "48 V DC", "347 V AC"], "Fire alarm panels operate at 12 V DC or 24 V DC."],
  "117": ["Supervision of a Class B loop is ensured by:", ["The GFCI", "The end-of-line resistor (EOL)", "The transformer", "The fuse"], "The end-of-line resistor allows the panel to supervise loop continuity."],
  "118": ["In a 6-story building, how many minimum fire detection zones?", ["2", "3", "4", "6"], "At minimum, one zone per floor = 6 zones for 6 stories."],
  "119": ["Maximum coverage area of a spot-type smoke detector at the ceiling:", ["25 m²", "50 m²", "80 m²", "100 m²"], "A spot-type smoke detector covers a maximum of 80 m² at ceiling height."],
  "120": ["A smoke detector cannot be installed closer than what distance from a wall?", ["100 mm", "200 mm", "300 mm", "500 mm"], "Detectors must be at least 500 mm (20 in) from any wall."],
  "121": ["Minimum conductor size for a fire alarm loop:", ["22 AWG", "18 AWG", "16 AWG", "14 AWG"], "Minimum wire size for fire alarm circuits is 18 AWG."],
  "122": ["In a Class A system, if the outgoing wire breaks, communication:", ["Is lost", "Continues via the return path", "Switches to radio mode", "Uses the EOL"], "Class A provides a redundant return path: communication continues via the return path."],
  "123": ["The maximum load on a fire alarm bell is limited to:", ["50% of panel capacity", "80% of panel capacity", "100%", "No limit"], "Notification appliance circuits are limited to 80% of the panel's rated capacity."],
  "124": ["Separation distance between fire alarm cable and electrical power conductors:", ["No separation required", "At least 50 mm", "At least 300 mm", "In the same conduit"], "Fire alarm cables must maintain at least 50 mm separation from power conductors."],
  "125": ["The heat detector in a parking garage must be of type:", ["Ionization", "Optical", "Thermovelocimetric", "Laser"], "Parking garages require rate-of-rise (thermovelocimetric) heat detectors due to exhaust fumes."],
  "126": ["Typical end-of-line resistor (EOL) value for a Class B loop:", ["120 Ω", "1 kΩ", "4.7 kΩ or 6.8 kΩ", "100 kΩ"], "Common EOL resistor values are 4.7 kΩ or 6.8 kΩ."],
  "127": ["In an intrusion alarm system, a PIR detector typically has a range of:", ["5 m", "10-15 m", "20-25 m", "30-40 m"], "Typical PIR detector range is 10-15 m."],
  "128": ["Standard CAN/ULC-S524 requires audible alarm devices to produce at least:", ["55 dB", "65 dB", "75 dB", "85 dB"], "Audible alarms must produce at least 75 dB at a specified distance."],
  "129": ["Maximum number of smoke detectors per zone in an addressable system:", ["12", "20", "30", "No specific limit"], "Addressable systems have no specific limit on detectors per zone."],
  "130": ["Which body is responsible for enforcing the Construction Code in Quebec (Chapter V)?", ["CMEQ", "RBQ (Régie du bâtiment du Québec)", "Hydro-Québec", "CNESST"], "The RBQ administers the Quebec Construction Code, Chapter V — Electricity."],
  "131": ["What is the name of the Code that governs electrical installations in Quebec?", ["National Electrical Code", "Quebec Construction Code, Chapter V", "Canadian Electrical Code", "CSA C22.1"], "The Quebec Construction Code, Chapter V — Electricity is the adopted version of the CEC with amendments."],
  "132": ["Maximum total voltage drop between source and final utilization:", ["2%", "3%", "5%", "10%"], "Art. 8-102: max 5% total from source to load."],
  "133": ["Maximum voltage drop in a branch circuit alone:", ["1%", "3%", "5%", "8%"], "Art. 8-102: max 3% for a branch circuit."],
  "134": ["What is the load density per m² for a residential building (art. 8-200)?", ["15 VA/m²", "25 VA/m²", "33 VA/m²", "50 VA/m²"], "Art. 8-200: 33 VA/m² for residential lighting."],
  "135": ["What is the minimum service size for a single-family home?", ["60 A", "80 A", "100 A", "125 A"], "Art. 8-200: minimum 100 A for a single-family dwelling."],
  "136": ["An RBQ permit is required for electrical work valued at more than:", ["$500", "$1,000", "$3,000", "$10,000"], "An RBQ permit is required for work over $3,000."],
  "137": ["The Construction Code is typically updated every:", ["1 year", "3-5 years", "10 years", "2 years"], "The Code is updated every 3-5 years."],
  "138": ["Article 26-702 of the Code deals with:", ["Motor installation", "Receptacles — spacing and number required", "Circuit protection", "Grounding"], "Art. 26-702 covers receptacle placement, spacing, and quantity."],
  "139": ["Article 26-710 of the Code covers:", ["Motors", "Residential special-purpose receptacles", "Solar panels", "Transformers"], "Art. 26-710 covers special-purpose receptacles (bathroom, garage, etc.)."],
  "140": ["Article 26-724 requires AFCI protection in:", ["Bathrooms", "Bedrooms and living areas", "Kitchens only", "Exteriors"], "Art. 26-724 requires AFCI in bedrooms and living areas in Quebec."],
  "141": ["Chapter 8 of the Code mainly deals with:", ["Grounding", "Load calculations and service sizing", "Residential wiring", "Motors"], "Chapter 8 covers load calculations and service conductor sizing."],
  "142": ["According to art. 8-200(3), the basic load for small kitchen appliances is:", ["1,500 VA per circuit", "1,500 VA minimum", "2,500 VA", "3,000 VA"], "Art. 8-200(3): 1,500 VA per small appliance circuit."],
  "143": ["What is a provincial amendment to the Code?", ["An error", "A modification specific to Quebec that is more stringent", "A suggestion", "A comment"], "Quebec amendments are additions or modifications to the CEC that are specific to Quebec."],
  "144": ["Article 8-102(1) limits voltage drop in feeder + service to:", ["1%", "2%", "3%", "5%"], "Art. 8-102(1): 3% max for feeder + service conductors."],
  "145": ["According to article 8-200(2), the minimum number of circuits for a residence is:", ["2 15 A circuits", "2 20 A circuits for kitchen + 1 15 A lighting", "3 15 A circuits", "4 20 A circuits"], "Art. 8-200(2): minimum 2 20 A small appliance circuits + 1 15 A lighting circuit."],
  "146": ["Chapter 10 of the Code covers:", ["Load calculations", "Grounding and bonding", "Motors", "Lighting"], "Chapter 10 covers grounding and bonding requirements."],
  "147": ["Chapter 26 of the Code covers:", ["Motor installation", "Residential wiring installation", "Transformers", "Solar panels"], "Chapter 26 covers residential wiring installation."],
  "148": ["Which section of the Code governs solar panel installations?", ["Chapter 26", "Chapter 64", "Chapter 8", "Chapter 46"], "Chapter 64 covers renewable energy systems, including solar PV."],
  "149": ["Minimum height of service conductors above a residential driveway:", ["3.0 m", "3.7 m", "4.5 m", "5.5 m"], "Service conductors must be at least 3.7 m (12 ft) above driveways."],
  "150": ["Article 2-300 requires electrical panels to be:", ["Locked at all times", "Accessible without tools", "Located in the bathroom", "At height only"], "Art. 2-300: electrical equipment must be readily accessible."],
  "151": ["According to art. 4-004, the neutral must be treated as a:", ["Grounded conductor", "Live conductor", "Not required", "Phase conductor"], "The neutral is a grounded (system) conductor."],
  "152": ["Article 26-712 requires a minimum number of receptacles in a kitchen:", ["1 receptacle", "2 receptacles", "As many as needed for each counter space", "4 receptacles"], "Art. 26-712 requires wall receptacles as needed for each counter space ≥ 300 mm."],
  "153": ["The validity period of an RBQ license is:", ["1 year", "2 years", "3 years", "5 years"], "An RBQ license is valid for 3 years."],
  "154": ["Hiring a master electrician is mandatory for work over:", ["$500", "$1,000", "$3,000", "$5,000"], "A master electrician must perform or supervise electrical work over $3,000."],
  "155": ["Article 46-200 of the Code governs:", ["Motors", "Fire alarm and security systems", "Solar panels", "Transformers"], "Art. 46-200 covers fire alarm and security system installation."],
  "156": ["What is the maximum taxable area for the application of 33 VA/m² per art. 8-200?", ["100 m²", "150 m²", "200 m²", "The total floor area of the dwelling"], "The total floor area of the dwelling is used for the 33 VA/m² calculation."],
  "157": ["According to art. 8-104, the minimum lighting load for a non-residential building is:", ["15 VA/m²", "20 VA/m²", "22 VA/m²", "33 VA/m²"], "Art. 8-104: 22 VA/m² minimum for non-residential lighting."],
  "158": ["Article 8-200(5) requires a cooktop ≥ 8 kW. The minimum power to consider is:", ["6,000 VA", "8,000 VA", "10,000 VA", "12,000 VA"], "Art. 8-200(5): if the cooktop is ≥ 8 kW, use the nameplate rating (minimum 8,000 VA)."],
  "159": ["The demand factor for 8 residential ranges according to Table 11 is:", ["60%", "50%", "40%", "30%"], "Table 11: demand factor for 8 ranges is 40%."],
  "160": ["According to article 26-710, bathroom receptacles in a dwelling must be:", ["One per sink within 1 m", "At least 2 receptacles", "One on the ceiling", "No receptacle"], "Art. 26-710: at least one receptacle within 1 m of each bathroom sink."],
  "161": ["Article 8-200(6) requires the dryer load to be taken at:", ["3,000 VA", "5,000 VA", "6,000 VA", "8,000 VA"], "Art. 8-200(6): dryer load shall be a minimum of 6,000 VA."],
  "162": ["Quebec amendments to the Code are published by:", ["Hydro-Québec", "CMEQ", "RBQ", "CSA"], "The RBQ publishes Quebec's amendments to the Canadian Electrical Code."],
  "163": ["Article 2-308 requires a minimum illumination of how many lux in front of an electrical panel?", ["50 lux", "100 lux", "150 lux", "200 lux"], "Art. 2-308: minimum 100 lux illumination at the floor level in front of the panel."],
  "164": ["For a 200 A service with 50 m of conductors, the max drop at 5% on 240 V is:", ["4.8 V", "7.2 V", "12 V", "18 V"], "5% of 240 V = 12 V."],
  "165": ["Article 12-1000 requires conductors exposed to moisture to be:", ["A larger gauge", "Moisture-resistant or protected", "Aluminum", "White in color"], "Conductors in damp/wet locations must be moisture-resistant or protected."],
  "166": ["The maximum number of circuits on a 200 A panel is limited by:", ["The law", "The number of available positions", "The building area", "No limit"], "The number of circuits is limited by the panel's available breaker positions."],
  "167": ["Appendix B of the Code contains:", ["Conductor ampacity tables", "Quebec amendments", "Electrical symbols", "Definitions"], "Appendix B contains the specific Quebec amendments to the CEC."],
  "168": ["According to art. 8-200(4), the water heater is calculated at:", ["Nameplate rating", "3,000 VA if ≤ 3,000 W, otherwise at actual value", "125% of rated value", "33 VA/m²"], "Art. 8-200(4): water heater at 3,000 VA if the nameplate rating is ≤ 3,000 W, otherwise at the actual value."],
  "169": ["A major modification requiring an RBQ permit includes:", ["Changing a receptacle", "Adding a circuit", "Replacing a light fixture", "Adding a service or modifying the panel"], "Adding a service or modifying the main panel requires an RBQ permit."],
  "170": ["In an electrical diagram, the symbol for a resistor is:", ["A circle", "A zigzag line or a rectangle", "A triangle", "An arrow"], "Resistors are shown as a zigzag line (ANSI) or a rectangle (IEC)."],
  "171": ["The symbol for a single-pole switch in a diagram is:", ["A circle with a cross", "A line with an opening", "A rectangle", "A triangle"], "A single-pole switch is shown as a line that can be drawn open or closed."],
  "172": ["The conductor color for AC control circuits is generally:", ["White", "Black or red", "Green", "Orange"], "Control circuit conductors are typically black or red."],
  "173": ["In a motor control diagram, a normally open (NO) contact is shown:", ["Closed, continuous line", "Open, two separate points", "With an arrow", "With a circle"], "NO contacts are shown as two separate points/lines that close when the coil is energized."],
  "174": ["In a control diagram, a contactor coil is represented by:", ["A circle", "A rectangle with a loop", "A zigzag", "A triangle"], "A coil is shown as a rectangle (IEC) or a circle (NEMA) with identification."],
  "175": ["A junction terminal block is identified by the letter:", ["X", "J", "B", "T"], "Terminal blocks are identified by the letter X in industrial schematics."],
  "176": ["The phase conductor in a 120/240 V diagram is generally:", ["Black", "White", "Green", "Blue"], "The phase/hot conductor is typically drawn in black."],
  "177": ["A single-line diagram represents:", ["Each conductor individually", "All three phases with a single line", "Only the neutral", "Symbols in 3D"], "A single-line diagram uses one line to represent all phases of a three-phase system."],
  "178": ["In a classic start/stop control circuit, the stop button is:", ["Normally open (NO)", "Normally closed (NC) in series with the coil", "Single-pole", "Double-pole"], "The stop button is normally closed (NC) and wired in series with the coil."],
  "179": ["In a start/stop circuit, the auxiliary contact of the contactor in parallel with the start button serves to:", ["Protect the motor", "Maintain the coil energized after releasing start button", "Stop the motor", "Indicate status"], "The auxiliary NO contact acts as a seal-in contact to maintain the circuit after the start button is released."],
  "180": ["Terminal numbers on contactors generally follow the standard:", ["DIN (e.g., 13-14, 21-22)", "NEMA (A1-A2)", "IEC 60000", "CSA Z462"], "DIN standard numbers are used: 13-14 for NO auxiliary, 21-22 for NC auxiliary, A1-A2 for the coil."],
  "181": ["Terminals A1-A2 of a contactor correspond to:", ["Power contacts", "The control coil", "Auxiliary contacts", "Ground"], "A1 and A2 are the coil terminals."],
  "182": ["A relay control circuit with a seal-in function requires at minimum:", ["One NO button", "One NO button + one NO relay contact + the relay coil", "One NC button + 2 relays", "A transformer"], "The seal-in uses a NO start button, a NO auxiliary contact in parallel, and the relay coil."],
  "183": ["In a three-phase motor power diagram, contactor contacts are referenced as:", ["1-2, 3-4, 5-6", "R-S-T", "L1-L2-L3", "A-B-C"], "Power contact numbering is 1-2, 3-4, 5-6."],
  "184": ["A transformer in a control diagram is represented by:", ["A circle", "Two facing loops", "A square", "A triangle"], "A transformer is shown as two opposing loops or semicircles."],
  "185": ["The standard for tag numbers in industrial diagrams follows:", ["CSA Z462", "IEC 81346", "NEC 70", "ISO 9001"], "IEC 81346 is the international standard for designation of equipment tags."],
  "186": ["A green indicator light in a diagram typically means:", ["Fault", "Run / in service", "Stop", "Alarm"], "Green indicates the equipment is running or in service."],
  "187": ["A red indicator light in a diagram typically means:", ["Run", "Fault, stop, or alarm", "Available", "Standby"], "Red indicates a fault, stop condition, or alarm."],
  "188": ["In a diagram, the symbol for a fuse is:", ["A rectangle with an S", "A rectangle with an X through the middle", "A circle", "A triangle"], "A fuse is shown as a rectangle with an X inside (IEC)."],
  "189": ["A timed relay (timer) is distinguished in a diagram by:", ["A circle", "A rectangle with a clock symbol", "A triangle", "A zigzag"], "Timers are shown as a rectangle with a clock or timer symbol."],
  "190": ["Auxiliary contacts of a relay are classified as:", ["Power contacts", "Control contacts (NO/NC)", "Ground contacts", "Measurement contacts"], "Auxiliary contacts are low-current control contacts used for logic and feedback."],
  "191": ["In a control diagram, the control circuit is generally protected by:", ["A 5-10 A fuse or breaker", "A GFCI", "An AFCI", "A disconnect switch"], "Control circuits are protected by a small fuse (5-10 A) or a miniature breaker."],
  "192": ["A disconnect switch is shown on a diagram as:", ["A switch with an oblique bar", "A black circle", "A rectangle", "A point"], "A disconnect is shown as a switch with an oblique line indicating the knife blade."],
  "193": ["In an electrical diagram, circuit continuity is represented by:", ["A dashed line", "A solid line between symbols", "An arrow", "A circle"], "Solid lines between symbols represent electrical connections."],
  "194": ["The symbol for a diode in a diagram is:", ["A circle", "A triangle with a bar", "A zigzag", "Two parallel lines"], "A diode is represented by a triangle (arrow) pointing to a vertical bar."],
  "195": ["In a motor control diagram, the thermal overload (OL) contact is:", ["NO, in parallel with the coil", "NC, in series with the coil", "NO, in series", "Independent"], "The OL contact is normally closed (NC) in series with the contactor coil."],
  "196": ["In a single-line diagram, a transformer is represented by:", ["A circle", "A circle with a vertical line", "A rectangle", "Two concentric circles"], "A transformer is shown as a circle with a vertical line through it."],
  "197": ["The symbol for ground (earth) in a diagram is:", ["An arrow", "An inverted triangle with horizontal lines", "A circle", "A square"], "Ground is shown as an inverted triangle with decreasing horizontal lines."],
  "198": ["In a motor control diagram with 2 start buttons in 2 locations, the start wiring is:", ["In series", "In parallel", "One NO, the other NC", "With an auxiliary contact"], "Multiple start buttons are wired in parallel so either can start the motor."],
  "199": ["In a control diagram with 2 stop buttons, the stop wiring is:", ["In parallel", "In series", "Mixed", "With a relay"], "Multiple stop buttons are wired in series so any one can stop the motor."]
};

async function main() {
  const batchNum = 1;
  const batchFile = `/home/chuck/batch_${String(batchNum).padStart(3, "0")}.json`;
  const batchData = JSON.parse(require("fs").readFileSync(batchFile, "utf8"));
  
  console.log(`Batch 001: Processing ${batchData.length} questions...`);
  
  let inserted = 0;
  let errors = 0;
  
  for (let i = 0; i < batchData.length; i++) {
    const frQ = batchData[i];
    const t = BATCH_001[String(i)];
    if (!t) {
      console.error(`No translation for index ${i}: ${frQ.question.substring(0, 50)}`);
      errors++;
      continue;
    }
    
    try {
      await prisma.question.create({
        data: {
          tradeId: frQ.tradeId,
          chapterId: frQ.chapterId,
          type: frQ.type,
          difficulty: frQ.difficulty,
          question: t[0],
          options: t[1],
          answer: frQ.answer,
          explanation: t[2],
          locale: "en"
        }
      });
      inserted++;
    } catch (e) {
      console.error(`Error at index ${i}: ${e.message}`);
      errors++;
    }
  }
  
  console.log(`Batch 001 done. Inserted: ${inserted}/${batchData.length}, Errors: ${errors}`);
}

main().catch(e => { console.error(e); process.exit(1); }).finally(() => prisma.$disconnect());
