const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

// English translations for batch 000 (200 questions, trade: cmrbe6r1d0000eap3fmyxpqfo - Electrician)
// KEYED BY POSITIONAL INDEX (0-199) matching batch_000.json order
const translations = {
  "0": { "question": "What is the formula for electrical power?", "options": ["P = V / I", "P = V × I", "P = V + I", "P = V - I"], "explanation": "Electrical power (P) is the product of voltage (V) and current (I): P = V × I (Joule's law)." },
  "1": { "question": "A motor draws 15 A at 240 V. What is its power?", "options": ["2,400 W", "3,000 W", "3,600 W", "4,200 W"], "explanation": "P = V × I = 240 V × 15 A = 3,600 W." },
  "2": { "question": "What is the resistance of a 120 V circuit that allows 8 A to flow?", "options": ["10 Ω", "12 Ω", "15 Ω", "20 Ω"], "explanation": "R = V / I = 120 V / 8 A = 15 Ω." },
  "3": { "question": "Three resistors 10 Ω, 15 Ω and 25 Ω in series. Total resistance?", "options": ["40 Ω", "45 Ω", "50 Ω", "55 Ω"], "explanation": "Rt = R1 + R2 + R3 = 10 + 15 + 25 = 50 Ω." },
  "4": { "question": "If the voltage in a circuit with constant resistance is doubled, the current:", "options": ["Is halved", "Doubles", "Quadruples", "Stays the same"], "explanation": "I = V/R — if V doubles and R stays constant, I also doubles." },
  "5": { "question": "What is the period of a 60 Hz signal?", "options": ["10 ms", "12.5 ms", "16.67 ms", "20 ms"], "explanation": "T = 1/f = 1/60 ≈ 16.67 ms." },
  "6": { "question": "Two 20 Ω resistors in parallel. Total resistance?", "options": ["5 Ω", "10 Ω", "20 Ω", "40 Ω"], "explanation": "1/Rt = 1/20 + 1/20 = 2/20 → Rt = 20/2 = 10 Ω." },
  "7": { "question": "What is the phase-to-neutral voltage of a 347/600 V system?", "options": ["277 V", "347 V", "480 V", "600 V"], "explanation": "In a 347/600 V system, phase-to-neutral is 347 V and phase-to-phase is 600 V." },
  "8": { "question": "A parallel circuit has R1=5Ω, R2=10Ω, R3=20Ω. Total current at 120 V?", "options": ["15 A", "24 A", "30 A", "42 A"], "explanation": "1/Rt = 1/5+1/10+1/20 = 0.2+0.1+0.05 = 0.35. Rt = 2.86 Ω. It = 120/2.86 = 42 A." },
  "9": { "question": "Main advantage of AC power transmission?", "options": ["Less dangerous", "Ease of voltage transformation", "Perfect efficiency", "Zero cost"], "explanation": "AC can be easily transformed using transformers to reduce losses." },
  "10": { "question": "Which wire for a 40 A range circuit?", "options": ["14 AWG", "12 AWG", "10 AWG", "8 AWG"], "explanation": "A 40 A range requires 8 AWG (capacity 40 A at 60 °C)." },
  "11": { "question": "Spacing between the start of a wall and the first receptacle?", "options": ["0.6 m", "0.9 m", "1.2 m", "1.8 m"], "explanation": "Art. 26-702: no more than 0.9 m from the start of a wall." },
  "12": { "question": "What type of cable to use in an unfinished basement?", "options": ["NM-B", "AC90 (armored)", "NMD90", "Cat5e"], "explanation": "AC90 provides mechanical protection, ideal for basements/garages." },
  "13": { "question": "Minimum service size for a new house?", "options": ["60 A", "100 A", "150 A", "200 A"], "explanation": "Art. 8-200: minimum 100 A for a new single-family dwelling." },
  "14": { "question": "Which wire for a 50 A EV charging station?", "options": ["10 AWG", "8 AWG", "6 AWG", "4 AWG"], "explanation": "50 A requires 6 AWG (capacity 55 A at 60 °C)." },
  "15": { "question": "Which device protects against 5 mA ground faults?", "options": ["Standard breaker", "GFCI", "AFCI", "Fuse"], "explanation": "The GFCI trips at 5 mA to protect people against shocks." },
  "16": { "question": "Which breaker for 12 AWG wire in a kitchen (continuous load)?", "options": ["15 A", "20 A", "25 A", "30 A"], "explanation": "12 AWG has a capacity of 20 A. For continuous load, 20 × 1.25 = 25 A." },
  "17": { "question": "What is the maximum tripping time of a GFCI at 5 mA?", "options": ["10 ms", "25 ms", "50 ms", "100 ms"], "explanation": "The GFCI must trip within 25 ms to protect people." },
  "18": { "question": "In which room are AFCIs mandatory?", "options": ["Kitchen", "Bathroom", "Bedroom", "Garage"], "explanation": "AFCIs are mandatory in bedrooms and living areas (art. 26-724)." },
  "19": { "question": "What does '125% for continuous load' mean?", "options": ["The breaker must be at 125%", "The conductor must be at 125%", "Conductor and protection at 125% of rated current", "None of the above"], "explanation": "Art. 8-104: for continuous loads (≥ 3h), sizing must be at 125%." },
  "20": { "question": "What is the typical inrush current of a motor at startup?", "options": ["2-3× In", "5-8× In", "10-12× In", "15-20× In"], "explanation": "An induction motor can draw 5 to 8 times the rated current at startup." },
  "21": { "question": "Which device varies the speed of an AC motor?", "options": ["Contactor", "VFD", "Thermal overload relay", "Disconnect switch"], "explanation": "The variable frequency drive (VFD) varies the frequency to control speed." },
  "22": { "question": "Maximum distance between disconnect switch and motor?", "options": ["5 m", "9 m", "15 m", "20 m"], "explanation": "Art. 28-600: 9 m (30 ft) within sight of the motor." },
  "23": { "question": "What efficiency for a Premium Efficiency motor?", "options": ["80-85%", "85-90%", "90-96%", "97-99%"], "explanation": "Premium high-efficiency motors have an efficiency of 90 to 96%." },
  "24": { "question": "A three-phase motor loses one phase. What happens?", "options": ["Nothing", "It runs faster", "Current increases 200-300%", "It stops immediately"], "explanation": "The motor continues running on 2 phases, but the current can reach 200-300% of FLA." },
  "25": { "question": "Which panel type offers the best efficiency?", "options": ["Polycrystalline", "Monocrystalline", "Thin film", "Amorphous"], "explanation": "Monocrystalline panels offer 18-22% efficiency." },
  "26": { "question": "What is an inverter used for?", "options": ["Produce electricity", "Convert DC to AC", "Store energy", "Regulate temperature"], "explanation": "The inverter converts DC from panels into AC compatible with the grid." },
  "27": { "question": "What is net metering?", "options": ["A type of panel", "Credit for energy fed into grid", "Safety device", "Solar battery"], "explanation": "Net metering credits solar energy fed into the Hydro-Québec grid." },
  "28": { "question": "120% rule for PV: calculate for 200 A panel + 30 A inverter", "options": ["200 A ≤ 240 A → OK", "200 A ≤ 200 A → OK", "230 A ≤ 250 A → OK", "200 A + 30 A = 230 A"], "explanation": "200 + 30 = 230 ≤ 120% × 200 = 240 → OK." },
  "29": { "question": "At what minimum temperature should panel DC voltage be sized in Quebec?", "options": ["-20 °C", "-30 °C", "-40 °C", "-50 °C"], "explanation": "In Quebec, the minimum temperature can reach -40 °C. This must be considered for max voltage." },
  "30": { "question": "What are the two main types of smoke detectors?", "options": ["Ionization and optical", "Thermal and barrier", "Laser and ultrasonic", "Capacitive and magnetic"], "explanation": "Ionization (fast fires) and optical (smoldering fires) detectors are the most common." },
  "31": { "question": "Which standard governs fire alarm installation in Canada?", "options": ["CSA C22.1", "CAN/ULC-S524", "CAN/ULC-S301", "CSA B44"], "explanation": "Standard CAN/ULC-S524 covers the installation of fire alarm systems." },
  "32": { "question": "Minimum backup battery autonomy for fire alarm systems?", "options": ["4 h", "12 h", "24 h", "48 h"], "explanation": "Standards require 24 hours of autonomy for fire alarm systems." },
  "33": { "question": "Class A loop in a fire alarm system:", "options": ["No end-of-line", "With return to panel", "Open loop", "No resistor"], "explanation": "Class A provides a redundant path: if a break occurs, the system remains functional." },
  "34": { "question": "Power supply for IP network cameras?", "options": ["Local 12 V DC", "24 V AC", "PoE (48 V DC via RJ45)", "120 V direct"], "explanation": "IP cameras use Power over Ethernet (48 V DC) through the network cable." },
  "35": { "question": "Which body administers the Quebec Construction Code - Chapter V (Electricity)?", "options": ["CMEQ", "RBQ", "Hydro-Québec", "CNESST"], "explanation": "Since 2017, the RBQ administers the Quebec Construction Code." },
  "36": { "question": "Maximum total voltage drop (feeder + branch)?", "options": ["1%", "3%", "5%", "10%"], "explanation": "Art. 8-102: max 5% from source to final utilization." },
  "37": { "question": "AFCI protection in Quebec: which rooms?", "options": ["Basements", "Bedrooms and living areas", "Kitchens", "Exteriors"], "explanation": "Quebec requires AFCIs in bedrooms AND living areas (amendment > CEC)." },
  "38": { "question": "Consequence of non-compliance with the Code?", "options": ["Warning", "Fines and revocation", "None", "Reduced premium"], "explanation": "Non-compliance can lead to fines and RBQ license revocation." },
  "39": { "question": "Who inspects electrical work in Quebec?", "options": ["The contractor", "Hydro-Québec", "The RBQ", "The CMMTQ"], "explanation": "The RBQ inspects electrical work to verify Code compliance." },
  "40": { "question": "Which diagram shows the physical routing of conductors?", "options": ["Single-line", "Multi-line", "Wiring", "Schematic"], "explanation": "The wiring diagram shows the actual routing of conductors." },
  "41": { "question": "In a motor control diagram, the power circuit is drawn in:", "options": ["Thin lines", "Thick lines", "Dashed lines", "Red"], "explanation": "Power circuits (high current) are drawn in thick lines, control circuits in thin lines." },
  "42": { "question": "Symbol for a normally open (NO) contact?", "options": ["Two separate lines", "Two lines with a bar", "Circle with cross", "Triangle"], "explanation": "The NO contact is represented by two separated parallel lines." },
  "43": { "question": "Neutral wire color in Canada?", "options": ["Black", "Red", "White", "Green"], "explanation": "The neutral is white (or gray) according to art. 4-026." },
  "44": { "question": "Contact terminal numbering:", "options": ["Letters", "Odd input, even output", "Colors", "Symbols"], "explanation": "Odd terminals (input), even (output) — e.g. 1-2, 3-4." },
  "45": { "question": "Minimum lighting load in residential?", "options": ["22 VA/m²", "33 VA/m²", "40 VA/m²", "50 VA/m²"], "explanation": "Art. 8-200: 33 VA/m² for residential lighting." },
  "46": { "question": "Demand factor for lighting beyond 2,000 VA (residential)?", "options": ["100%", "75%", "50%", "35%"], "explanation": "First 2,000 VA at 100%, the rest at 35%." },
  "47": { "question": "Typical power of an electric range?", "options": ["5,000 W", "8,000-12,000 W", "15,000 W", "20,000 W"], "explanation": "A standard electric range is 8,000 to 12,000 W." },
  "48": { "question": "Current for 40,000 VA at 240 V?", "options": ["100 A", "150 A", "167 A", "200 A"], "explanation": "I = 40,000 / 240 = 166.7 A ≈ 167 A." },
  "49": { "question": "What is a demand factor?", "options": ["Total power", "Coefficient reducing the load", "Rated voltage", "Breaker capacity"], "explanation": "The demand factor reduces the load because not all appliances operate simultaneously." },
  "50": { "question": "What is the unit of measurement for electrical resistance?", "options": ["Volt", "Ampere", "Ohm", "Watt"], "explanation": "Resistance is expressed in ohms (Ω), named after Georg Ohm." },
  "51": { "question": "A 12 V circuit with a current of 3 A has a resistance of:", "options": ["3 Ω", "4 Ω", "6 Ω", "9 Ω"], "explanation": "R = V / I = 12 V / 3 A = 4 Ω." },
  "52": { "question": "If V = 120 V and R = 30 Ω, the current I is:", "options": ["2 A", "3 A", "4 A", "6 A"], "explanation": "I = V / R = 120 V / 30 Ω = 4 A." },
  "53": { "question": "Two 30 Ω resistors in series give a total resistance of:", "options": ["15 Ω", "30 Ω", "60 Ω", "90 Ω"], "explanation": "Rt = R1 + R2 = 30 + 30 = 60 Ω." },
  "54": { "question": "The power dissipated by a 10 Ω resistor with 2 A flowing through it is:", "options": ["20 W", "30 W", "40 W", "50 W"], "explanation": "P = I² × R = 2² × 10 = 4 × 10 = 40 W." },
  "55": { "question": "Which symbol represents electrical current?", "options": ["V", "R", "I", "P"], "explanation": "I (intensity) represents electrical current in amperes." },
  "56": { "question": "In Ohm's triangle, if V is covered, you get:", "options": ["V = I × R", "I = V / R", "R = V / I", "P = V × I"], "explanation": "Ohm's triangle shows V at the top, I and R at the bottom: V = I × R." },
  "57": { "question": "Voltage drop in a conductor is caused by:", "options": ["Power", "Wire resistance", "Frequency", "Inductance"], "explanation": "Voltage drop ∆V = I × R is proportional to the conductor's resistance." },
  "58": { "question": "A 4,500 W water heater at 240 V draws a current of:", "options": ["14.8 A", "16.7 A", "18.75 A", "20.5 A"], "explanation": "I = P / V = 4,500 / 240 = 18.75 A." },
  "59": { "question": "Three resistors 12 Ω, 18 Ω and 30 Ω in series. Current at 120 V?", "options": ["1.5 A", "2.0 A", "2.5 A", "3.0 A"], "explanation": "Rt = 12+18+30 = 60 Ω. I = 120 / 60 = 2 A." },
  "60": { "question": "Two 40 Ω resistors in parallel give an equivalent resistance of:", "options": ["10 Ω", "20 Ω", "40 Ω", "80 Ω"], "explanation": "1/Rt = 1/40 + 1/40 = 2/40 → Rt = 40/2 = 20 Ω." },
  "61": { "question": "A 50 Ω resistor dissipates 200 W. The current through it is:", "options": ["1 A", "2 A", "3 A", "4 A"], "explanation": "P = I²R → I = √(P/R) = √(200/50) = √4 = 2 A." },
  "62": { "question": "What is the total power of a 120 V circuit with R1=20Ω, R2=30Ω in series?", "options": ["144 W", "200 W", "288 W", "360 W"], "explanation": "Rt = 20+30 = 50 Ω. I = 120/50 = 2.4 A. P = V×I = 120×2.4 = 288 W." },
  "63": { "question": "A 50 m wire has a resistance of 0.2 Ω. The voltage drop at 15 A is:", "options": ["1.5 V", "2.0 V", "3.0 V", "7.5 V"], "explanation": "∆V = I × R = 15 × 0.2 = 3.0 V." },
  "64": { "question": "In a parallel circuit with R1=10Ω, R2=20Ω at 120 V, current through R2:", "options": ["6 A", "8 A", "10 A", "12 A"], "explanation": "I₂ = V / R₂ = 120 / 20 = 6 A." },
  "65": { "question": "R1=15Ω, R2=15Ω in parallel. What resistance to add in series for Rt=15Ω?", "options": ["5 Ω", "7.5 Ω", "10 Ω", "15 Ω"], "explanation": "R1//R2 = 7.5 Ω. For Rt=15 Ω, R_series = 15-7.5 = 7.5 Ω." },
  "66": { "question": "What is the power formula using only current and resistance?", "options": ["P = V²/R", "P = I² × R", "P = V × I", "P = V² × I"], "explanation": "Joule's law: P = I² × R expresses power as a function of current and resistance." },
  "67": { "question": "A 1,500 W baseboard heater at 240 V. What is its internal resistance?", "options": ["24.4 Ω", "32.6 Ω", "38.4 Ω", "45.2 Ω"], "explanation": "R = V²/P = 240²/1500 = 57,600/1500 = 38.4 Ω." },
  "68": { "question": "If voltage doubles in a circuit with constant resistance, the power:", "options": ["Doubles", "Triples", "Quadruples", "Stays the same"], "explanation": "P = V²/R. If V × 2, then P × 4." },
  "69": { "question": "Four identical resistors in parallel, Rt = 5 Ω. Value of each?", "options": ["10 Ω", "15 Ω", "20 Ω", "25 Ω"], "explanation": "R/4 = 5 → R = 5×4 = 20 Ω." },
  "70": { "question": "A 120 V circuit powers R1=30Ω and R2=60Ω in parallel. Total current?", "options": ["4 A", "5 A", "6 A", "8 A"], "explanation": "1/Rt = 1/30+1/60 = 3/60 → Rt=20Ω. I=120/20=6A." },
  "71": { "question": "The maximum recommended voltage drop in a branch circuit is:", "options": ["1%", "3%", "5%", "10%"], "explanation": "Art. 8-102: max 3% for branch circuit, 5% total." },
  "72": { "question": "A 20 Ω resistor dissipates 500 W. The voltage across it is:", "options": ["50 V", "80 V", "100 V", "120 V"], "explanation": "V = √(P×R) = √(500×20) = √10,000 = 100 V." },
  "73": { "question": "R1=8Ω, R2=12Ω, R3=24Ω in parallel. Equivalent resistance?", "options": ["2 Ω", "4 Ω", "6 Ω", "8 Ω"], "explanation": "1/Rt = 1/8+1/12+1/24 = 3/24+2/24+1/24 = 6/24 → Rt=24/6=4Ω." },
  "74": { "question": "Ohm's law states that current is:", "options": ["Directly proportional to R", "Inversely proportional to V", "Directly proportional to V, inversely to R", "Independent of V"], "explanation": "I = V/R: current increases with voltage and decreases with resistance." },
  "75": { "question": "An AWG 12 copper wire has a resistance of 1.6 Ω/km. For 30 m, the resistance is:", "options": ["0.048 Ω", "0.48 Ω", "1.6 Ω", "4.8 Ω"], "explanation": "30 m = 0.03 km → R = 1.6 × 0.03 = 0.048 Ω." },
  "76": { "question": "In a series circuit, if a resistor is defective (open):", "options": ["Current continues in the others", "The circuit is open, no more current", "The voltage drops to zero", "Nothing changes"], "explanation": "In series, an open circuit stops current in the entire circuit." },
  "77": { "question": "A 2,000 W heater at 240 V. At 208 V, its power becomes:", "options": ["1,200 W", "1,500 W", "1,800 W", "2,000 W"], "explanation": "R = V²/P = 240²/2000 = 28.8 Ω. P' = 208²/28.8 = 43,264/28.8 = 1,502 W ≈ 1,500 W." },
  "78": { "question": "Series circuit: R1=10Ω, R2=20Ω, R3=30Ω, supplied at 120 V. Voltage across R2?", "options": ["20 V", "30 V", "40 V", "60 V"], "explanation": "I = 120/(10+20+30) = 2 A. V_R2 = 2 × 20 = 40 V." },
  "79": { "question": "Parallel circuit R1=40Ω, R2=60Ω, R3=120Ω at 120 V. Current through R1?", "options": ["1 A", "2 A", "3 A", "4 A"], "explanation": "I₁ = V / R₁ = 120 / 40 = 3 A." },
  "80": { "question": "P = 3,600 W, V = 240 V, R = ?", "options": ["12 Ω", "14 Ω", "16 Ω", "18 Ω"], "explanation": "I = P/V = 3600/240 = 15 A. R = V/I = 240/15 = 16 Ω. Or R = V²/P = 57,600/3,600 = 16 Ω." },
  "81": { "question": "Mixed circuit: R1=10Ω in series with (R2=20Ω // R3=30Ω). Total resistance?", "options": ["12 Ω", "18 Ω", "22 Ω", "28 Ω"], "explanation": "R2//R3 = (20×30)/(20+30) = 600/50 = 12 Ω. Rt = 10+12 = 22 Ω." },
  "82": { "question": "A 240 V, 40 A circuit. A 20 A load is added. The voltage drop in the 0.1 Ω conductor is:", "options": ["2 V", "4 V", "6 V", "8 V"], "explanation": "I_total = 40+20 = 60 A. ∆V = 60 × 0.1 = 6 V." },
  "83": { "question": "Three resistors: R1=5Ω in series with (R2=10Ω // R3=10Ω). Total current at 120 V?", "options": ["8 A", "10 A", "12 A", "15 A"], "explanation": "R2//R3 = 5Ω. Rt = 5+5 = 10Ω. I = 120/10 = 12 A." },
  "84": { "question": "What is the equivalent resistance of: 10Ω // (20Ω in series 30Ω)?", "options": ["6.7 Ω", "8.3 Ω", "10 Ω", "12.5 Ω"], "explanation": "Series branch = 20+30 = 50Ω. 1/Rt = 1/10 + 1/50 = 5/50+1/50 = 6/50. Rt = 50/6 ≈ 8.33 Ω." },
  "85": { "question": "A 5,000 W load at 240 V on a 50 m wire. Voltage drop if R_wire=0.2 Ω?", "options": ["2.2 V", "3.5 V", "4.2 V", "5.0 V"], "explanation": "I = 5,000/240 = 20.83 A. ∆V = 20.83 × 0.2 = 4.17 V ≈ 4.2 V." },
  "86": { "question": "If V = 347 V, I = 10 A, R = ?", "options": ["20.7 Ω", "28.3 Ω", "34.7 Ω", "41.2 Ω"], "explanation": "R = V / I = 347 / 10 = 34.7 Ω." },
  "87": { "question": "Two resistors in parallel: R1 = 6Ω, R2 = 12Ω. The equivalent resistance is:", "options": ["2 Ω", "3 Ω", "4 Ω", "6 Ω"], "explanation": "1/Rt = 1/6+1/12 = 2/12+1/12 = 3/12 = 1/4 → Rt = 4 Ω." },
  "88": { "question": "A 120 V, 60 W soldering iron. Current and resistance?", "options": ["0.5 A, 240 Ω", "0.75 A, 160 Ω", "1 A, 120 Ω", "1.5 A, 80 Ω"], "explanation": "I = 60/120 = 0.5 A. R = 120/0.5 = 240 Ω." },
  "89": { "question": "A 120 V, 100 W light bulb. Its hot resistance is:", "options": ["100 Ω", "120 Ω", "144 Ω", "200 Ω"], "explanation": "R = V²/P = 120²/100 = 14,400/100 = 144 Ω." },
  "90": { "question": "The RMS value of a 170 V peak AC voltage is:", "options": ["100 V", "120 V", "150 V", "170 V"], "explanation": "Vrms = Vpeak / √2 = 170 / 1.414 = 120.2 V ≈ 120 V." },
  "91": { "question": "What is the frequency of the electrical grid in Quebec?", "options": ["50 Hz", "60 Hz", "120 Hz", "400 Hz"], "explanation": "The North American electrical grid operates at 60 Hz." },
  "92": { "question": "The peak value of a 120 V RMS voltage is:", "options": ["120 V", "150 V", "170 V", "208 V"], "explanation": "Vpeak = Vrms × √2 = 120 × 1.414 = 169.7 V ≈ 170 V." },
  "93": { "question": "In a three-phase 120/208 V system, the phase-to-phase voltage is:", "options": ["120 V", "208 V", "277 V", "347 V"], "explanation": "Vphase-phase = Vphase-neutral × √3 = 120 × 1.732 = 208 V." },
  "94": { "question": "In a three-phase 347/600 V system, the phase-to-phase voltage is:", "options": ["347 V", "480 V", "600 V", "1,000 V"], "explanation": "Vphase-phase = 347 × √3 = 600 V." },
  "95": { "question": "What is a step-down transformer?", "options": ["Increases voltage", "Decreases voltage", "Increases frequency", "Converts AC to DC"], "explanation": "A step-down transformer has more turns on the primary than the secondary." },
  "96": { "question": "What is the period of a 60 Hz signal?", "options": ["10 ms", "12.5 ms", "16.67 ms", "20 ms"], "explanation": "T = 1/f = 1/60 = 0.01667 s = 16.67 ms." },
  "97": { "question": "Direct current (DC) flows:", "options": ["In one direction only", "Alternatingly", "In pulses", "Randomly"], "explanation": "DC always flows in the same direction, unlike AC." },
  "98": { "question": "Power in a single-phase AC circuit is calculated as:", "options": ["P = V × I", "P = V × I × cos φ", "P = V × I × √3", "P = V² × I"], "explanation": "In single-phase AC, P = V × I × power factor (cos φ)." },
  "99": { "question": "A 600/347 V, 100 kVA transformer. Full-load secondary current?", "options": ["167 A", "200 A", "288 A", "347 A"], "explanation": "I = S / V = 100,000 / 347 = 288.2 A." },
  "100": { "question": "The peak-to-peak voltage of a 120 V RMS sine wave is:", "options": ["170 V", "240 V", "340 V", "480 V"], "explanation": "Vpp = 2 × Vpeak = 2 × (120 × √2) = 2 × 170 = 340 V." },
  "101": { "question": "In a star (wye) connection, the line current is:", "options": ["Equal to the phase current", "√3 × phase current", "Phase current / √3", "2 × phase current"], "explanation": "In a wye connection, I_line = I_phase. Only voltage differs (V_line = V_phase × √3)." },
  "102": { "question": "An ideal 120/24 V, 120 VA transformer. Full-load primary current?", "options": ["0.5 A", "1 A", "2 A", "5 A"], "explanation": "I_primary = S / V_primary = 120 / 120 = 1 A." },
  "103": { "question": "To supply 208 V three-phase equipment, how many conductors are needed?", "options": ["2 wires", "3 wires", "4 wires", "5 wires"], "explanation": "Three-phase 208 V requires 3 phases + 1 neutral = 4 wires." },
  "104": { "question": "What is the voltage between two phases of a 347/600 V system?", "options": ["277 V", "347 V", "480 V", "600 V"], "explanation": "V_phase-phase = 347 × √3 = 600 V." },
  "105": { "question": "An AC signal with a zero average value is:", "options": ["A pure sine wave", "A rectified signal", "A DC signal", "A square wave"], "explanation": "A pure sine wave has a zero average value because positive and negative alternations cancel out." },
  "106": { "question": "A rectifier converts:", "options": ["AC to DC", "DC to AC", "Low voltage to high voltage", "Frequency to voltage"], "explanation": "The rectifier (diode bridge) converts alternating current to pulsating direct current." },
  "107": { "question": "In a balanced three-phase circuit, total power P =", "options": ["3 × Vph × Iph × cos φ", "√3 × V_L × I_L × cos φ", "V × I × cos φ", "V × I × √2"], "explanation": "P_total = √3 × V_line × I_line × cos φ for a balanced three-phase system." },
  "108": { "question": "What is the crest factor of a sine wave?", "options": ["1", "1.414", "1.732", "2"], "explanation": "Crest factor = Vpeak / Vrms = √2 ≈ 1.414." },
  "109": { "question": "A 75 kVA, 600/208-120 V transformer. Primary current?", "options": ["72 A", "104 A", "125 A", "208 A"], "explanation": "I_primary = S/(√3×V) = 75,000/(1.732×600) = 72.2 A." },
  "110": { "question": "The neutral of a 120/208 V system is needed for:", "options": ["Supplying 120 V loads", "Grounding the system", "Increasing capacity", "Avoiding harmonics"], "explanation": "The neutral allows obtaining 120 V between a phase and neutral in a 120/208 V system." },
  "111": { "question": "The impedance Z of an RL circuit is measured in:", "options": ["Watts", "Ohms", "Henrys", "Farads"], "explanation": "Impedance, like resistance, is expressed in ohms (Ω)." },
  "112": { "question": "A VFD first converts AC to DC, then:", "options": ["DC to AC at variable frequency", "DC to DC", "AC to AC unchanged", "DC to regulated DC"], "explanation": "The VFD rectifies AC to DC, then generates variable-frequency AC to control motor speed." },
  "113": { "question": "The turns ratio of a 600 V / 120 V transformer is:", "options": ["2:1", "3:1", "5:1", "6:1"], "explanation": "Ratio = Vprimary / Vsecondary = 600/120 = 5:1." },
  "114": { "question": "A 347 V RMS AC voltage has a peak value of:", "options": ["347 V", "480 V", "490 V", "600 V"], "explanation": "Vpeak = 347 × √2 = 347 × 1.414 = 490.7 V." },
  "115": { "question": "In an unbalanced three-phase system, the neutral:", "options": ["Carries no current", "Carries the unbalanced current", "Is optional", "Is always at 0 V"], "explanation": "The neutral carries the vector sum of phase currents; in an imbalance, it carries current." },
  "116": { "question": "The ripple frequency of a full-wave rectifier bridge on a 60 Hz grid is:", "options": ["60 Hz", "100 Hz", "120 Hz", "180 Hz"], "explanation": "A full-wave bridge rectifies both half-cycles → 2 × 60 = 120 Hz." },
  "117": { "question": "A 300/24 V, 150 VA transformer. The maximum secondary current is:", "options": ["3.5 A", "5.2 A", "6.25 A", "12.5 A"], "explanation": "I_secondary = 150 / 24 = 6.25 A." },
  "118": { "question": "A three-phase 600 V, 50 A motor, cos φ = 0.85. Active power?", "options": ["30 kW", "37 kW", "44 kW", "51 kW"], "explanation": "P = √3 × V × I × cos φ = 1.732 × 600 × 50 × 0.85 = 44,166 W ≈ 44 kW." },
  "119": { "question": "In a delta connection, line voltage compared to phase voltage is:", "options": ["V_line = V_phase", "V_line = V_phase × √3", "V_line = V_phase / √3", "V_line = V_phase × 2"], "explanation": "In delta, V_line = V_phase. It is the current that differs: I_line = I_phase × √3." },
  "120": { "question": "A 225 kVA three-phase transformer, 600/208-120 V. Maximum secondary current per phase?", "options": ["375 A", "450 A", "541 A", "625 A"], "explanation": "I_line = S/(√3×V) = 225,000/(1.732×208) = 625 A." },
  "121": { "question": "Harmonics in AC are mainly caused by:", "options": ["Linear motors", "Non-linear loads (VFD, LED)", "Unloaded transformers", "Overly long cables"], "explanation": "Non-linear loads like VFDs and switching power supplies generate harmonics." },
  "122": { "question": "A 600 V / 120-0-120 V transformer with 50 A secondary. Apparent power?", "options": ["6 kVA", "9 kVA", "12 kVA", "15 kVA"], "explanation": "Total secondary voltage = 240 V. S = 240 × 50 = 12,000 VA." },
  "123": { "question": "The inductive reactance XL at 60 Hz for a 0.1 H coil is:", "options": ["18.8 Ω", "24.2 Ω", "37.7 Ω", "60.0 Ω"], "explanation": "XL = 2πfL = 2 × 3.1416 × 60 × 0.1 = 37.7 Ω." },
  "124": { "question": "A 10 kW load, cos φ = 0.8, at 240 V single-phase. Current?", "options": ["41.7 A", "48.1 A", "52.1 A", "60.1 A"], "explanation": "I = P / (V × cos φ) = 10,000 / (240 × 0.8) = 10,000 / 192 = 52.08 A." },
  "125": { "question": "In a series RLC circuit at resonance:", "options": ["XL = XC", "XL > XC", "XL < XC", "Z = infinity"], "explanation": "At resonance, reactances cancel out: XL = XC, impedance is minimum = R." },
  "126": { "question": "Voltage of a 600 V system between phase and neutral?", "options": ["277 V", "347 V", "480 V", "600 V"], "explanation": "V_phase-neutral = 600 / √3 = 600 / 1.732 = 346.4 V ≈ 347 V." },
  "127": { "question": "A three-phase 600 V, 200 A line, cos φ = 0.9. What active power is transmitted?", "options": ["155 kW", "175 kW", "187 kW", "208 kW"], "explanation": "P = √3 × 600 × 200 × 0.9 = 1.732 × 600 × 200 × 0.9 = 187,056 W ≈ 187 kW." },
  "128": { "question": "To correct power factor from 0.7 to 0.95, you install:", "options": ["Resistors", "Capacitors", "Inductors", "Transformers"], "explanation": "Capacitor banks compensate inductive reactive energy and improve cos φ." },
  "129": { "question": "An inverter converts:", "options": ["AC to DC", "DC to AC", "Low to high voltage", "AC to AC with frequency change"], "explanation": "The inverter converts direct current to alternating current." },
  "130": { "question": "Which cable type is most commonly used for indoor residential wiring in Quebec?", "options": ["TECK90", "AC90", "NMD90", "Cat5e"], "explanation": "NMD90 is the standard for residential: PVC sheath, copper conductors, 90 °C insulation." },
  "131": { "question": "What is the minimum conductor size for a general lighting circuit?", "options": ["18 AWG", "16 AWG", "14 AWG", "12 AWG"], "explanation": "The minimum size for a lighting circuit is 14 AWG (15 A)." },
  "132": { "question": "At what maximum height should a receptacle be installed above the floor?", "options": ["30 cm", "45 cm", "60 cm", "90 cm"], "explanation": "Receptacles are generally installed between 30 and 45 cm from the finished floor." },
  "133": { "question": "What is the color of the ground conductor?", "options": ["White", "Black", "Green or bare", "Red"], "explanation": "The ground conductor is green, green-yellow, or bare (bare copper)." },
  "134": { "question": "What wire size for a 40 A range circuit?", "options": ["12 AWG", "10 AWG", "8 AWG", "6 AWG"], "explanation": "40 A requires an 8 AWG conductor (capacity 40 A at 60 °C)." },
  "135": { "question": "TECK90 cable is mainly used for:", "options": ["Indoor dry locations", "Outdoor and buried", "Audio wiring", "Computer networks"], "explanation": "TECK90 resists UV and moisture, ideal for outdoor and buried installations." },
  "136": { "question": "How many 15 A circuits maximum in a single residential technical raceway?", "options": ["6 circuits", "8 circuits", "12 circuits", "No limit"], "explanation": "According to the Code, maximum 12 circuits per conduit/raceway or based on 40% fill." },
  "137": { "question": "What is the color of the neutral conductor in Quebec?", "options": ["Green", "Black", "White", "Red"], "explanation": "The neutral conductor is identified by white (or light gray) color." },
  "138": { "question": "The maximum spacing between receptacles along a residential wall is:", "options": ["1.5 m", "1.8 m", "2.0 m", "2.5 m"], "explanation": "Art. 26-702: no more than 1.8 m between two consecutive receptacles." },
  "139": { "question": "The maximum distance between the start of a wall and the first receptacle is:", "options": ["0.6 m", "0.9 m", "1.2 m", "1.5 m"], "explanation": "Art. 26-702: no more than 0.9 m (3 ft) from the start of a wall." },
  "140": { "question": "In a bathroom, the GFCI receptacle must be located:", "options": ["At least 0.5 m from the tub", "At least 1.0 m from the tub", "Inside the shower itself", "Anywhere"], "explanation": "Art. 26-702: receptacles must be ≥ 1 m from the tub or shower." },
  "141": { "question": "What type of cable to use in a suspended ceiling of a dry basement?", "options": ["NMD90", "TECK90", "AC90 armored", "Cat6"], "explanation": "NMD90 is acceptable in dry locations, even in suspended ceilings." },
  "142": { "question": "A 20 A circuit for kitchen receptacles must use wire size:", "options": ["14 AWG", "12 AWG", "10 AWG", "8 AWG"], "explanation": "12 AWG has a capacity of 20 A at 60 °C, required for a 20 A circuit." },
  "143": { "question": "What is the ampacity of a 10 AWG conductor at 60 °C?", "options": ["20 A", "25 A", "30 A", "35 A"], "explanation": "According to Table 2 of the Code, 10 AWG at 60 °C = 30 A." },
  "144": { "question": "In a dwelling, kitchen receptacles must be supplied by at least:", "options": ["1 15 A circuit", "2 20 A circuits", "1 20 A circuit", "3 15 A circuits"], "explanation": "Art. 26-712: minimum 2 20 A circuits for small kitchen appliances." },
  "145": { "question": "The ampacity of a 6 AWG copper conductor at 75 °C is:", "options": ["55 A", "65 A", "75 A", "85 A"], "explanation": "6 AWG copper at 75 °C = 65 A according to Table 2 of the Code." },
  "146": { "question": "An NMD90 14/2 cable contains:", "options": ["2 conductors 14 AWG + ground", "3 conductors 14 AWG + ground", "14 conductors AWG 2", "2 conductors 14 AWG without ground"], "explanation": "14/2 means 2 insulated 14 AWG conductors (hot + neutral) + ground wire." },
  "147": { "question": "A 4,500 W water heater at 240 V requires a breaker of:", "options": ["15 A", "20 A", "25 A", "30 A"], "explanation": "I = 4,500/240 = 18.75 A. × 125% = 23.4 A → 25 A standard breaker." },
  "148": { "question": "What is the minimum neutral conductor size for a 200 A service?", "options": ["4 AWG", "3 AWG", "2 AWG", "1/0 AWG"], "explanation": "The neutral can be reduced per art. 4-022. For 200 A, 2 AWG copper is often sufficient." },
  "149": { "question": "Which cable type is mandatory for buried service connections?", "options": ["NMD90", "AC90", "TECK90", "NM-B"], "explanation": "Art. 16-100: TECK90 is required for buried or outdoor service connections." },
  "150": { "question": "A 15 A lighting circuit can supply how many 150 W fixtures (120 V)?", "options": ["8", "10", "12", "15"], "explanation": "Max I_total = 15 A. Each fixture = 150/120 = 1.25 A. 15/1.25 = 12 fixtures." },
  "151": { "question": "Phase conductors in a three-phase system are identified by colors:", "options": ["Black, white, green", "Black, red, blue", "Black, red, white", "Red, white, green"], "explanation": "In Quebec, phases are identified: black (A), red (B), blue (C)." },
  "152": { "question": "A 4 AWG copper wire at 75 °C can carry:", "options": ["70 A", "85 A", "100 A", "115 A"], "explanation": "4 AWG copper at 75 °C = 85 A according to Table 2." },
  "153": { "question": "What is the maximum number of 12 AWG conductors in a 1 in (DN 27) conduit?", "options": ["4", "6", "9", "12"], "explanation": "According to the fill table, a 1 in conduit can contain up to 9 12 AWG conductors (40% fill)." },
  "154": { "question": "For a dishwasher, the breaker must be:", "options": ["15 A max", "20 A max", "At rated capacity or 125%", "30 A max"], "explanation": "Art. 28-704: protection of a fixed appliance must be sized at 125% of rated current if continuous load." },
  "155": { "question": "AC90 cable differs from NMD90 by:", "options": ["Its white color", "Its metal armored sheath", "Its lower price", "Its flexibility"], "explanation": "AC90 has a metallic armor that provides mechanical protection and serves as a ground conductor." },
  "156": { "question": "Ampacity of an 8 AWG copper conductor at 60 °C:", "options": ["30 A", "40 A", "50 A", "55 A"], "explanation": "8 AWG at 60 °C = 40 A according to Table 2." },
  "157": { "question": "What is the minimum height of an electrical panel from the floor?", "options": ["1.0 m", "1.2 m", "1.5 m", "2.0 m"], "explanation": "The panel center must be at max 1.7 m and min 1.2 m from the floor." },
  "158": { "question": "A 5 HP, 240 V single-phase motor, FLA = 28 A. Conductor size?", "options": ["10 AWG", "8 AWG", "6 AWG", "4 AWG"], "explanation": "125% × 28 = 35 A. 8 AWG at 60 °C = 40 A, adequate." },
  "159": { "question": "Four 4/0 AWG aluminum conductors in a conduit. The grouping correction for 4 conductors is:", "options": ["100%", "90%", "80%", "70%"], "explanation": "Table 5C: 4-6 conductors → correction factor 80%." },
  "160": { "question": "A 12 AWG conductor at 90 °C, 30 °C ambient, 4 bundled conductors. Adjusted ampacity?", "options": ["20 A", "22.5 A", "25 A", "27.5 A"], "explanation": "12 AWG 90 °C = 25 A. Grouping correction 4 cond. = 80% → 25 × 0.8 = 20 A." },
  "161": { "question": "In a residential garage, a 120 V 15 A receptacle is required:", "options": ["On the ceiling", "On each wall", "At least one per 6 m of wall", "Near the door"], "explanation": "Art. 26-710(d): at least one GFCI receptacle per 6 m of wall in a garage." },
  "162": { "question": "A 350 kcmil copper wire at 75 °C has an ampacity of:", "options": ["250 A", "310 A", "350 A", "400 A"], "explanation": "350 kcmil copper at 75 °C = 310 A according to Table 2." },
  "163": { "question": "For a 200 A aluminum service, the minimum size is:", "options": ["2/0 AWG", "3/0 AWG", "4/0 AWG", "250 kcmil"], "explanation": "4/0 AWG aluminum at 75 °C = 205 A, adequate for a 200 A service." },
  "164": { "question": "What is the minimum clearance in front of an electrical panel?", "options": ["0.6 m", "0.9 m", "1.0 m", "1.2 m"], "explanation": "Art. 2-308: minimum 1 m clearance in front of the panel." },
  "165": { "question": "In a child's bedroom, receptacles must be:", "options": ["GFCI", "AFCI", "Standard 15 A", "Lockable"], "explanation": "Art. 26-724(f): bedroom receptacles must be protected by AFCI." },
  "166": { "question": "A 240 V 30 A dryer circuit. Length 25 m, max voltage drop 3% of 240 V. Max drop in volts?", "options": ["4.8 V", "6.0 V", "7.2 V", "9.6 V"], "explanation": "3% of 240 V = 0.03 × 240 = 7.2 V." },
  "167": { "question": "A 25 HP three-phase 600 V motor, FLA = 27 A. Breaker size?", "options": ["30 A", "35 A", "40 A", "45 A"], "explanation": "125% × 27 = 33.75 A → 35 A breaker (next standard size up)." },
  "168": { "question": "What is the minimum section of the bonding conductor?", "options": ["14 AWG", "12 AWG", "10 AWG", "6 AWG"], "explanation": "Art. 10-612: bonding conductor ≥ 6 AWG copper." },
  "169": { "question": "NMD90 14/3 cable contains how many insulated conductors?", "options": ["2", "3", "4", "5"], "explanation": "14/3 = 3 insulated 14 AWG conductors (black, red, white) + ground wire = 4 conductors total." },
  "170": { "question": "Which device protects circuits against overloads and short circuits?", "options": ["A fuse", "A disconnect switch", "A junction block", "A transformer"], "explanation": "Fuses and circuit breakers protect against overloads and short circuits." },
  "171": { "question": "A GFCI trips starting at a leakage current of:", "options": ["1 mA", "5 mA", "10 mA", "30 mA"], "explanation": "The GFCI is calibrated at 5 mA for personal protection." },
  "172": { "question": "Where is a GFCI required in a residence?", "options": ["Bedrooms", "Bathroom, kitchen, exterior", "Garage only", "Basement"], "explanation": "Art. 26-702: GFCI required in bathrooms, kitchens, exteriors, garages." },
  "173": { "question": "What does the acronym AFCI stand for?", "options": ["Arc Fault Circuit Interrupter", "Arc Flash Circuit Interrupter", "Automatic Fault Circuit Interrupter", "Alternating Frequency Circuit Interrupter"], "explanation": "AFCI = Arc Fault Circuit Interrupter (DFARC in French)." },
  "174": { "question": "A 20 A breaker protects a minimum wire size of:", "options": ["14 AWG", "12 AWG", "10 AWG", "8 AWG"], "explanation": "A 20 A breaker protects a 12 AWG conductor (capacity 20 A)." },
  "175": { "question": "The maximum tripping time of a GFCI at 5 mA is:", "options": ["10 ms", "25 ms", "50 ms", "100 ms"], "explanation": "The GFCI must trip within ≤ 25 ms to effectively protect people." },
  "176": { "question": "A continuous load is defined as a load that is maintained for:", "options": ["30 minutes or more", "1 hour or more", "3 hours or more", "8 hours or more"], "explanation": "Art. 8-104: a continuous load is intended to last 3 hours or more." },
  "177": { "question": "Which device is resettable after a fault?", "options": ["Fuse", "Breaker", "Thermal relay", "Disconnect switch"], "explanation": "A breaker can be reset. A fuse must be replaced." },
  "178": { "question": "The sizing factor for a continuous load is:", "options": ["110%", "120%", "125%", "150%"], "explanation": "Art. 8-104: sizing at 125% of rated current for continuous loads." },
  "179": { "question": "A 16 A continuous load on a 120 V circuit requires a breaker of:", "options": ["15 A", "20 A", "25 A", "30 A"], "explanation": "16 A × 125% = 20 A → 20 A breaker." },
  "180": { "question": "Where are AFCIs required in Quebec?", "options": ["Bathrooms only", "Kitchens and bathrooms", "Bedrooms and living areas", "Garages and workshops"], "explanation": "In Quebec, AFCIs are mandatory in bedrooms AND living areas (art. 26-724)." },
  "181": { "question": "A type D (time-delay) fuse is used for:", "options": ["Lighting", "Motor circuits with inrush current", "Receptacle circuits", "Electronic circuits"], "explanation": "Time-delay fuses accept motor starting current without blowing." },
  "182": { "question": "What maximum fault current can a standard 20 A breaker interrupt?", "options": ["2 kA", "5 kA", "10 kA", "14 kA"], "explanation": "Standard residential breakers have an interrupting capacity of 10 kA." },
  "183": { "question": "How many 15 A circuits can be placed on a 100 A panel?", "options": ["6", "8", "10", "12+"], "explanation": "There is no fixed limit. The total load must not exceed 100 A, but up to 24 circuits are possible." },
  "184": { "question": "Selective coordination of protections aims to:", "options": ["Trip all breakers", "Isolate only the fault", "Increase current", "Reduce voltage"], "explanation": "Selective coordination ensures only the device immediately upstream of the fault trips." },
  "185": { "question": "A 30 A breaker protecting a 10 AWG wire is correct if:", "options": ["Always", "Never, 10 AWG max 30 A", "For resistive load only", "For motor load"], "explanation": "A 10 AWG conductor at 60 °C = 30 A. The breaker must be ≤ 30 A, so 30 A is correct if the load is ≤ 24 A continuous." },
  "186": { "question": "What is a Residual Current Device (RCD)?", "options": ["A type of AFCI", "A type of GFCI for 3-phase systems", "A high-voltage breaker", "A disconnect switch"], "explanation": "The RCD is the equivalent of GFCI for three-phase installations (protects against ground leaks)." },
  "187": { "question": "For a washing machine, what type of protection is required?", "options": ["Standard breaker", "GFCI", "AFCI", "Time-delay fuse"], "explanation": "Art. 26-702: laundry room receptacles require GFCI protection." },
  "188": { "question": "A 15 A breaker protects a 14 AWG circuit. The maximum continuous load is:", "options": ["10 A", "12 A", "15 A", "18 A"], "explanation": "15 A × 80% (continuous load ≥ 3 h must be ≤ 80% of rating) = 12 A." },
  "189": { "question": "Which type of breaker is indicated for a motor?", "options": ["Standard", "Type D (curve D)", "Type B", "AFCI"], "explanation": "Type D breakers accept the high inrush currents (10-20× In) of motors." },
  "190": { "question": "The interrupting capacity of a breaker must be:", "options": ["Greater than the available short-circuit current", "Equal to the rated current", "Less than the rated voltage", "Defined by the user"], "explanation": "The interrupting capacity must be ≥ the maximum short-circuit current at the installation point." },
  "191": { "question": "A GFCI protects against:", "options": ["Overloads", "Short circuits", "Ground leakage currents", "Overvoltages"], "explanation": "The GFCI detects ground leakage currents (phase-neutral imbalance) ≥ 5 mA." },
  "192": { "question": "What is the difference between a breaker and a fuse?", "options": ["None", "A breaker is resettable, a fuse is replaced", "A fuse is faster", "A breaker protects better"], "explanation": "A breaker can be reset after a fault; a fuse must be removed and replaced." },
  "193": { "question": "The guaranteed number of operating cycles of a standard breaker is:", "options": ["1,000", "5,000", "10,000", "50,000"], "explanation": "Standard breakers are tested for 10,000 operating cycles." },
  "194": { "question": "AFCI detects:", "options": ["Ground leaks", "Dangerous electrical arcs", "Overvoltages", "Low voltages"], "explanation": "AFCI detects electrical arcs (sparks) in wiring that could cause a fire." },
  "195": { "question": "To protect a 347 V circuit, what type of GFCI is needed?", "options": ["Standard 120 V GFCI", "Specific 347 V GFCI", "AFCI", "Fuse"], "explanation": "GFCIs have a rated voltage: a 347 V model is required for 347 V circuits." },
  "196": { "question": "A 40 A breaker protects an 8 AWG wire. Maximum continuous load?", "options": ["32 A", "35 A", "40 A", "50 A"], "explanation": "40 A × 80% = 32 A for a continuous load." },
  "197": { "question": "In an electrical panel, the main switch must be:", "options": ["Visible and accessible", "Hidden in the wall", "Locked", "Outside"], "explanation": "Art. 6-200: the main switch must be readily accessible and visible." },
  "198": { "question": "A 200 A panel, ambient temperature 40 °C. Temperature correction for breakers?", "options": ["No correction", "80% of rating", "85% of rating", "90% of rating"], "explanation": "At 40 °C, breakers must be derated to 85% to compensate for ambient heat." },
  "199": { "question": "The maximum short-circuit current in a typical residence is on the order of:", "options": ["500 A", "2 kA", "5 kA", "10 kA"], "explanation": "The available short-circuit current in a residence can reach 10 kA near the main panel." }
};

async function main() {
  const batchData = JSON.parse(require("fs").readFileSync("/home/chuck/batch_000.json", "utf8"));
  console.log(`Processing ${Object.keys(translations).length} questions...`);
  
  let inserted = 0;
  let errors = 0;
  
  for (let i = 0; i < batchData.length; i++) {
    const frQ = batchData[i];
    const t = translations[String(i)];
    if (!t) {
      console.error(`No translation for index ${i}: ${frQ.question.substring(0, 40)}`);
      errors++;
      continue;
    }
    
    try {
      await prisma.question.create({
        data: {
          tradeId: frQ.tradeId,
          chapterId: frQ.chapterId,
          type: frQ.type,
          difficulty: frQ.difficulty,
          question: t.question,
          options: t.options,
          answer: frQ.answer,
          explanation: t.explanation,
          locale: "en"
        }
      });
      inserted++;
    } catch (e) {
      console.error(`Error at index ${i}: ${e.message}`);
      errors++;
    }
  }
  
  console.log(`Done. Inserted: ${inserted}, Errors: ${errors}`);
}

main().catch(e => { console.error(e); process.exit(1); }).finally(() => prisma.$disconnect());
