"""Generate additional questions for Entrepreneur général chapters 2, 3, 4 (45 each = 135 total)."""
import json, re, psycopg2

db_url = open("/home/chuck/projects/metierium/server/.env").read()
m = re.search(r'DATABASE_URL=postgresql://([^:]+):([^@]+)@localhost:5432/metierium', db_url)
user, pw = m.group(1), m.group(2)

conn = psycopg2.connect(f"postgresql://{user}:{pw}@localhost:5432/metierium")
cur = conn.cursor()

TRADE = 'cmt_entrepreneur_general_001'
TS = '2026-07-09T03:00:00.000Z'

# Extra questions for chapters 2, 3, 4 (45 each)
CHAPTERS = {
    'ch_entgen_02': {
        'name': 'Gestion d\'entreprise',
        'questions': [
            # --- 45 questions: comptabilité, paie, CCQ, conventions, taxes ---
            ('Quel organisme gère les régimes de retraite et assurances collectives dans la construction au Québec?', ['CCQ', 'RBQ', 'CNESST', 'Revenu Québec'], 'A', 'La Commission de la construction du Québec (CCQ) gère les régimes de retraite, assurances et avantages sociaux des travailleurs de la construction.'),
            ('Quel est le taux de cotisation patronale à la CCQ pour un entrepreneur général?', ['Variable selon la masse salariale', '15% du salaire brut', 'Fixe, déterminé annuellement par la CCQ', '5% du salaire brut'], 'C', 'Le taux de cotisation à la CCQ est fixé annuellement et s\'applique à toutes les heures travaillées par les employés de la construction.'),
            ('Qu\'est-ce que le "droit de gérance" dans le contexte de la construction?', ['Le droit de l\'entrepreneur de gérer son chantier sans ingérence syndicale', 'Le droit du syndicat de nommer un contremaître', 'L\'obligation de tenir des réunions de chantier', 'Le droit des employés de choisir leur horaire'], 'A', 'Le droit de gérance permet à l\'entrepreneur de diriger son entreprise et son chantier, notamment en matière d\'organisation du travail, dans le respect des conventions collectives.'),
            ('Quelle est la fréquence de production du rapport de paie pour la CCQ?', ['Mensuelle', 'Hebdomadaire', 'Trimestrielle', 'Annuelle'], 'A', 'Les employeurs doivent produire un rapport de paie mensuel à la CCQ, déclarant les heures travaillées et les cotisations dues.'),
            ('Qu\'est-ce qu\'un "reçu de cotisation" de la CCQ?', ['Un document prouvant le paiement des cotisations pour chaque employé', 'Une facture pour les services de la CCQ', 'Un relevé d\'impôt annuel', 'Un certificat de compétence'], 'A', 'Le reçu de cotisation est émis par la CCQ pour confirmer le versement des cotisations sociales pour un employé donné.'),
            ('Quels impôts un entrepreneur général doit-il percevoir sur ses travaux de construction?', ['TPS et TVQ', 'Seulement la TPS', 'Aucune taxe sur les travaux de construction', 'Taxe spécifique à la construction'], 'A', 'L\'entrepreneur général doit facturer et percevoir la TPS (5%) et la TVQ (9.975%) sur ses travaux de construction, sauf exceptions.'),
            ('Qu\'est-ce que le "sous-traitant" dans le contexte de la construction?', ['Une entreprise qui exécute des travaux pour l\'entrepreneur général', 'Un employé spécialisé de l\'entrepreneur', 'Un fournisseur de matériaux', 'Un inspecteur externe'], 'A', 'Le sous-traitant est une entreprise distincte engagée par l\'entrepreneur général pour réaliser une partie spécifique des travaux.'),
            ('Quel est le délai maximum pour émettre un relevé d\'emploi après la fin d\'un contrat?', ['5 jours ouvrables', '30 jours', '15 jours', '10 jours'], 'A', 'L\'employeur doit remettre le relevé d\'emploi dans les 5 jours ouvrables suivant la fin du contrat ou l\'arrêt de rémunération.'),
            ('Qu\'est-ce que la déclaration trimestrielle de Revenu Québec pour un entrepreneur?', ['Une déclaration des taxes perçues et des crédits d\'impôt', 'Une déclaration de revenus annuelle', 'Un rapport de paie', 'Une demande de permis'], 'A', 'Les entrepreneurs doivent produire une déclaration de TPS/TVQ trimestrielle ou mensuelle selon leur chiffre d\'affaires.'),
            ('Quelle est la différence entre un employé et un travailleur autonome en construction?', ['Lien de subordination et contrôle de l\'exécution du travail', 'Le taux horaire', 'La durée du contrat', 'Le type d\'outillage utilisé'], 'A', 'Le critère principal est le lien de subordination : un employé est sous la direction de l\'entrepreneur, tandis qu\'un travailleur autonome conserve son autonomie.'),
            ('Qu\'est-ce que le "fonds de formation" de la CCQ?', ['Un fonds finançant la formation professionnelle des travailleurs', 'Un fonds de retraite', 'Une assurance-emploi', 'Un compte d\'épargne'], 'A', 'Le fonds de formation de la CCQ finance les programmes de formation et de perfectionnement des travailleurs de la construction.'),
            ('Quel est le pourcentage maximum de retenue de garantie sur un contrat public?', ['10%', '5%', '15%', '20%'], 'A', 'La retenue de garantie sur les contrats publics est généralement limitée à 10% du montant du contrat, libérable par tranches.'),
            ('Qu\'est-ce que la Loi sur les relations du travail dans la construction?', ['La loi qui régit les relations de travail, négociations et grèves dans l\'industrie', 'La loi sur la sécurité incendie', 'Le code de déontologie des entrepreneurs', 'Le règlement sur les permis'], 'A', 'Cette loi encadre les relations patronales-syndicales, la négociation collective et les conditions de travail dans l\'industrie de la construction.'),
            ('Qu\'est-ce que la "mobilité de la main-d\'œuvre" dans la construction?', ['La capacité des travailleurs à se déplacer entre chantiers sans perdre leurs avantages', 'Le transport collectif des employés', 'La flexibilité des horaires', 'Le télétravail dans la construction'], 'A', 'La mobilité de la main-d\'œuvre permet aux travailleurs de passer d\'un employeur à l\'autre sans perdre leurs droits accumulés (ancienneté, avantages sociaux).'),
            ('Comment est calculée la contribution au fonds de santé et sécurité?', ['Basée sur la masse salariale et le taux de risque de l\'entreprise', 'Un montant fixe par employé', 'Un pourcentage du chiffre d\'affaires', 'Une prime annuelle unique'], 'A', 'La CNESST fixe un taux de cotisation basé sur le risque de l\'activité et la masse salariale de l\'entreprise.'),
            ('Qu\'est-ce qu\'un "avis de cotisation" de la CCQ?', ['Un avis officiel du montant dû par l\'employeur à la CCQ', 'Un reçu de paiement', 'Une demande de remboursement', 'Un constat d\'infraction'], 'A', 'L\'avis de cotisation est envoyé par la CCQ pour informer l\'employeur des montants dus pour ses employés de la construction.'),
            ('Quelle est la période de rétention des registres de paie en construction?', ['7 ans', '3 ans', '5 ans', '10 ans'], 'A', 'Les registres de paie et documents comptables doivent être conservés pendant 7 ans conformément à la Loi sur les normes du travail et Revenu Québec.'),
            ('Qu\'est-ce que le "pro rata" dans le calcul des vacances pour un travailleur de la construction?', ['Le calcul proportionnel des vacances selon les heures travaillées', 'Le taux horaire majoré', 'La prime de fin d\'année', 'L\'indemnité de transport'], 'A', 'Le pro rata des vacances est calculé en fonction du nombre d\'heures réellement travaillées par rapport à une année complète.'),
            ('Qu\'est-ce qu\'une "convention collective" dans la construction?', ['Un contrat négocié entre associations patronales et syndicats régissant les conditions de travail', 'Un contrat d\'assurance', 'Un accord entre entrepreneur et client', 'Un permis de construire'], 'A', 'La convention collective est le résultat de négociations entre les associations d\'employeurs et les syndicats, fixant salaires et conditions de travail.'),
            ('Quel pourcentage des heures travaillées doit être déclaré à la CCQ?', ['100% des heures travaillées dans la construction', 'Seulement les heures supplémentaires', 'Les heures régulières seulement', '50% des heures'], 'A', 'Toutes les heures travaillées par les employés de la construction doivent être déclarées à la CCQ, sans exception.'),
            ('Qu\'est-ce que le "décrochage" dans le contexte des cotisations CCQ?', ['Le fait de perdre ses droits et avantages faute d\'heures suffisantes', 'L\'arrêt volontaire de travail', 'Une grève légale', 'Un congé sans solde'], 'A', 'Le décrochage survient lorsqu\'un travailleur cumule moins de 500 heures de travail par année civile, entraînant la perte de certains avantages sociaux.'),
            ('Quel est l\'impact fiscal de l\'achat d\'un véhicule utilitaire pour un entrepreneur?', ['Déduction partielle selon l\'usage professionnel', 'Aucune déduction possible', 'Déduction complète du prix d\'achat', 'Crédit d\'impôt automatique'], 'A', 'L\'entrepreneur peut déduire une partie des coûts du véhicule proportionnellement à son utilisation professionnelle pour les chantiers.'),
            ('Qu\'est-ce que le "compte de TVQ" auprès de Revenu Québec?', ['Un compte de taxe de vente provinciale pour percevoir et remettre la TVQ', 'Un compte bancaire dédié', 'Un relevé de transactions', 'Un compte d\'épargne entreprise'], 'A', 'Tout entrepreneur doit s\'inscrire au fichier de la TVQ auprès de Revenu Québec dès qu\'il effectue des activités taxables au Québec.'),
            ('Qu\'est-ce qu\'un "engagement" dans le cadre de la Loi sur la construction?', ['Un document garantissant qu\'un employé sera déclaré à la CCQ', 'Un contrat de travail signé', 'Un permis de travail', 'Une soumission acceptée'], 'A', 'L\'engagement est un formulaire transmis à la CCQ pour déclarer l\'embauche d\'un travailleur et entamer ses cotisations sociales.'),
            ('Quelle est la conséquence du défaut de produire les rapports de paie à la CCQ?', ['Amendes, pénalités et intérêts sur les montants dus', 'Suspension du permis RBQ', 'Avertissement écrit', 'Annulation des contrats en cours'], 'A', 'Le défaut de produire les rapports de paie expose l\'entrepreneur à des amendes, pénalités et intérêts sur les cotisations impayées.'),
            ('Qu\'est-ce que le "taux de risque" en santé et sécurité?', ['Un taux basé sur l\'historique des lésions de l\'industrie pour calculer la cotisation', 'Le nombre d\'accidents par chantier', 'Le pourcentage d\'arrêts de travail', 'La prime d\'assurance'], 'A', 'Le taux de risque est déterminé par la CNESST selon le secteur d\'activité et sert au calcul de la cotisation annuelle de l\'employeur.'),
            ('Comment sont classées les entreprises de construction par la CCQ?', ['Par secteur d\'activité et catégorie de métiers exercés', 'Par chiffre d\'affaires', 'Par nombre d\'employés', 'Par région administrative'], 'A', 'La CCQ classe les entreprises selon les secteurs (génie civil, industriel, commercial-institutionnel, résidentiel) et les métiers qu\'elles emploient.'),
            ('Qu\'est-ce que le "fonds de retraite" géré par la CCQ?', ['Un régime de retraite collectif pour les travailleurs de la construction', 'Un fonds d\'investissement', 'Une assurance-vie', 'Un REER collectif'], 'A', 'La CCQ gère le Régime de retraite des employés de l\'industrie de la construction (REIC), un régime obligatoire pour les travailleurs.'),
            ('Quel est le délai de transmission du rapport de paie à la CCQ?', ['Avant le 15e jour du mois suivant', 'À la fin du trimestre', 'Le dernier jour du mois', 'Dans les 30 jours suivant la paie'], 'A', 'Le rapport de paie mensuel doit être transmis à la CCQ avant le 15e jour du mois suivant la période déclarée.'),
            ('Qu\'est-ce que le "droit d\'accès aux dossiers" par la CCQ?', ['Le droit de la CCQ d\'inspecter les registres de l\'entrepreneur', 'Le droit de l\'employé de consulter son dossier', 'Le droit du public d\'accéder aux permis', 'Le droit de consulter les conventions'], 'A', 'La CCQ peut exiger la production de tout document nécessaire à la vérification des déclarations de paie et des cotisations.'),
            ('Qu\'est-ce qu\'un "certificat de conformité" de la CCQ?', ['Un document attestant que l\'employeur respecte ses obligations de déclaration', 'Un permis de construire', 'Une attestation d\'assurance', 'Un certificat de compétence'], 'A', 'Le certificat de conformité est émis par la CCQ pour confirmer qu\'un employeur est en règle avec ses obligations déclaratives.'),
            ('Qu\'est-ce que le "salaire courant" dans l\'industrie de la construction?', ['Les taux de salaire minimum établis par les conventions collectives pour chaque métier', 'Le salaire minimum légal', 'Le salaire moyen du marché', 'Le taux horaire négocié individuellement'], 'A', 'Les conventions collectives fixent les taux de salaire minimum pour chaque métier et chaque secteur de la construction.'),
            ('Quel est le rôle de l\'Association sectorielle paritaire (ASP)?', ['Offrir des services de formation et de consultation en SST aux entreprises', 'Délivrer les permis de construction', 'Gérer les cotisations syndicales', 'Inspecter les chantiers'], 'A', 'Les ASP Construction offrent des services de formation, d\'information et de conseil en santé et sécurité du travail adaptés au secteur.'),
            ('Qu\'est-ce que la "déclaration d\'ouverture de chantier"?', ['Un avis transmis à la CCQ avant le début des travaux', 'Le permis de construire', 'Le contrat signé par le client', 'L\'affichage obligatoire sur le chantier'], 'A', 'L\'entrepreneur doit transmettre une déclaration d\'ouverture de chantier à la CCQ pour informer du début des travaux.'),
            ('Qu\'est-ce que le "carnet de chantier"?', ['Un document officiel consignant la main-d\'œuvre présente et les travaux exécutés quotidiennement', 'Un registre des accidents', 'Un journal de bord personnel', 'Un rapport financier'], 'A', 'Le carnet de chantier est obligatoire et contient la liste des employés présents, leurs heures et les travaux effectués chaque jour.'),
            ('Quelle est la différence entre un métier réglementé et non réglementé?', ['Le métier réglementé nécessite un certificat de compétence de la CCQ', 'Le salaire est différent', 'La durée de la formation', 'Le type de contrat'], 'A', 'Certains métiers de la construction sont réglementés et exigent un certificat de compétence pour être exercés légalement.'),
            ('Comment est calculée l\'indemnité de vacances pour un travailleur de la construction?', ['Un pourcentage du salaire brut versé via la CCQ', 'Une somme forfaitaire annuelle', '2 semaines par an sans solde', 'Un montant négocié par contrat'], 'A', 'L\'indemnité de vacances est calculée selon un pourcentage du salaire brut (généralement 4% à 6%) et versée par la CCQ.'),
            ('Qu\'est-ce qu\'un "compte de fonds" à la CCQ?', ['Un compte individuel qui cumule les droits et avantages sociaux du travailleur', 'Un compte bancaire d\'entreprise', 'Un fonds d\'investissement', 'Un régime de retraite'], 'A', 'Chaque travailleur de la construction a un compte de fonds à la CCQ qui enregistre ses heures et accumule ses droits.'),
            ('Quel est le rôle de la CNESST en matière de lésions professionnelles?', ['Indemniser les travailleurs victimes d\'accidents du travail et gérer leur réadaptation', 'Délivrer les permis', 'Former les inspecteurs', 'Financer les chantiers'], 'A', 'La CNESST administre le régime d\'indemnisation pour les lésions professionnelles et assure le retour au travail des travailleurs blessés.'),
            ('Qu\'est-ce que le "taux horaire net" pour un travailleur?', ['Le salaire après déductions des cotisations sociales et impôts', 'Le salaire brut', 'Le taux syndical', 'Le minimum légal'], 'A', 'Le taux horaire net est le montant que reçoit réellement le travailleur après toutes les déductions obligatoires.'),
            ('Qu\'est-ce qu\'un "registre des employés"?', ['Un document obligatoire contenant les informations personnelles et les heures de chaque employé', 'Une liste de paie', 'Un contrat de travail', 'Un formulaire d\'embauche'], 'A', 'Le registre des employés est un document légal que tout entrepreneur doit tenir à jour avec les coordonnées, dates d\'embauche et heures travaillées.'),
            ('Qu\'est-ce que le "Code de construction" en matière de gestion administrative?', ['Les obligations administratives de l\'entrepreneur pour assurer la conformité des travaux', 'Un plan de construction', 'Un guide de gestion', 'Un règlement municipal'], 'A', 'La gestion administrative du Code de construction implique des obligations de documentation, de déclaration et de tenue de registres.'),
            ('Quels sont les documents requis pour l\'embauche d\'un travailleur de la construction?', ['Carnet de compétence, NAS, relevé d\'emploi antérieur, formulaire d\'engagement CCQ', 'CV et lettres de recommandation', 'Permis de conduire', 'Diplômes seulement'], 'A', 'L\'embauche d\'un travailleur nécessite la vérification de ses qualifications et la transmission des documents requis à la CCQ.'),
            ('Qu\'est-ce que la "cotisation syndicale" dans la construction?', ['Une contribution prélevée sur le salaire pour financer le syndicat représentant le travailleur', 'Une taxe gouvernementale', 'Une assurance', 'Un frais de permis'], 'A', 'Les travailleurs syndiqués paient une cotisation syndicale, généralement prélevée à la source et versée à l\'association accréditée.'),
            ('Qu\'est-ce que le "droit de priorité d\'embauche"?', ['Le droit des travailleurs locaux d\'être embauchés avant les travailleurs d\'autres régions', 'Le droit syndical', 'La préférence de l\'employeur', 'Le droit du plus ancien'], 'A', 'Dans certaines régions, les travailleurs locaux ont priorité d\'embauche avant que l\'entrepreneur puisse faire appel à de la main-d\'œuvre d\'autres régions.'),
            ('Quel est le rôle du "commissaire industriel" dans la construction?', ['Enquêter sur les plaintes et violations des normes du travail et de la construction', 'Délivrer les permis', 'Gérer les appels d\'offres', 'Former les apprentis'], 'A', 'Le commissaire industriel enquête sur les plaintes concernant les infractions aux lois et règlements régissant l\'industrie de la construction.'),
        ]
    },
    'ch_entgen_03': {
        'name': 'Contrats et droit de la construction',
        'questions': [
            # --- 45 questions: types de contrats, Code civil, sous-traitance, privilèges ---
            ('Quels sont les trois types principaux de contrats de construction?', ['Forfaitaire, à prix unitaire, à frais remboursables', 'Oral, écrit, tacite', 'Public, privé, mixte', 'Court, moyen, long terme'], 'A', 'Les trois grands types sont le contrat à forfait (prix fixe), le contrat à prix unitaire (quantités variables), et le contrat à frais remboursables (coût + marge).'),
            ('Qu\'est-ce qu\'un contrat à forfait en construction?', ['Un contrat où le prix est fixé à l\'avance pour l\'ensemble des travaux', 'Un contrat sans prix déterminé', 'Un contrat horaire', 'Un contrat à durée indéterminée'], 'A', 'Le contrat à forfait fixe un prix global et définitif pour l\'exécution complète des travaux décrits aux plans et devis.'),
            ('Qu\'est-ce que la Loi sur le bâtiment prévoit en matière de contrat?', ['Les exigences de licence et les obligations contractuelles des entrepreneurs', 'Les normes de sécurité', 'Les règles d\'urbanisme', 'Les taxes applicables'], 'A', 'La Loi sur le bâtiment encadre les exigences de licence RBQ et les obligations des entrepreneurs dans leurs contrats.'),
            ('Qu\'est-ce qu\'un "privilège" dans le domaine de la construction?', ['Une garantie légale de paiement pour les fournisseurs et sous-traitants', 'Un avantage concurrentiel', 'Un permis spécial', 'Une réduction d\'impôt'], 'A', 'Le privilège de construction est une sûreté légale qui garantit le paiement des personnes ayant participé à la construction ou rénovation d\'un immeuble.'),
            ('Quel est le délai pour enregistrer un privilège de construction?', ['30 jours après la fin des travaux', '60 jours', '90 jours', '15 jours'], 'A', 'Le privilège doit être enregistré au Bureau de la publicité des droits dans les 30 jours suivant la fin des travaux ou la cessation du contrat.'),
            ('Qu\'est-ce qu\'un "sous-contrat" en construction?', ['Un contrat entre l\'entrepreneur général et un sous-traitant spécialisé', 'Un contrat de sous-location', 'Un contrat à rabais', 'Un accord verbal'], 'A', 'Le sous-contrat est un contrat par lequel l\'entrepreneur général confie une partie des travaux à un sous-traitant spécialisé.'),
            ('Qu\'est-ce que le "droit de résiliation" d\'un contrat de construction?', ['Le droit de mettre fin au contrat pour manquement grave ou inexécution', 'Le droit de changer d\'avis', 'Le droit de renégocier le prix', 'Le droit de suspendre les travaux'], 'A', 'Le droit de résiliation permet à une partie de mettre fin au contrat si l\'autre partie manque gravement à ses obligations.'),
            ('Qu\'est-ce que la "cautionnement de soumission"?', ['Une garantie financière accompagnant une soumission pour assurer sa validité', 'Un dépôt de garantie', 'Une assurance', 'Un contrat de prêt'], 'A', 'Le cautionnement de soumission garantit que l\'entrepreneur signera le contrat s\'il obtient le projet et fournira les cautionnements requis.'),
            ('Qu\'est-ce que l\'"avis de projet" dans un contrat public?', ['Un avis publié pour solliciter des soumissions pour un projet public', 'Une annonce de début de travaux', 'Un communiqué de presse', 'Un ordre de changement'], 'A', 'L\'avis de projet est la publication officielle invitant les entrepreneurs à soumissionner pour un contrat public.'),
            ('Qu\'est-ce qu\'un "ordre de changement" en construction?', ['Un document modifiant la portée, le coût ou les délais des travaux', 'Une résiliation de contrat', 'Un nouveau contrat', 'Un plan révisé'], 'A', 'L\'ordre de changement est un document formel qui autorise une modification aux travaux et ajuste le prix et/ou l\'échéancier.'),
            ('Qu\'est-ce que la "clause de pénalité" dans un contrat de construction?', ['Une clause prévoyant des dommages liquidés pour retard d\'exécution', 'Une clause de résiliation', 'Une clause d\'indexation', 'Une clause de force majeure'], 'A', 'La clause de pénalité fixe à l\'avance le montant payable par jour de retard, à titre de dommages liquidés.'),
            ('Qu\'est-ce que le "prix unitaire" dans un contrat?', ['Un prix par unité de mesure (m², m³, heure) pour des quantités estimées', 'Le prix total du projet', 'Le prix par mètre carré', 'Le prix forfaitaire'], 'A', 'Le prix unitaire est fixé par unité de mesure et le montant total est déterminé par les quantités réellement exécutées.'),
            ('Qu\'est-ce qu\'un "vice caché" en construction?', ['Un défaut non apparent au moment de la réception qui rend l\'ouvrage impropre à son usage', 'Un défaut esthétique', 'Une non-conformité mineure', 'Un dommage accidentel'], 'A', 'Le vice caché est un défaut grave qui existait au moment de la réception mais n\'était pas visible. L\'entrepreneur en est responsable pendant 5 ans.'),
            ('Qu\'est-ce que la "garantie de bon fonctionnement"?', ['La garantie légale couvrant les défauts de construction pendant 1 à 5 ans', 'La garantie des électroménagers', 'La garantie des matériaux', 'L\'assurance responsabilité'], 'A', 'La garantie de bon fonctionnement (ou garantie légale) protège le client contre les vices et défauts de construction pour des durées variant selon le type de défaut.'),
            ('Qu\'est-ce que la "soumission" en construction?', ['Une offre de service détaillée avec prix pour réaliser des travaux', 'Un devis descriptif', 'Un plan architectural', 'Un contrat signé'], 'A', 'La soumission est l\'offre formelle de l\'entrepreneur pour exécuter des travaux à un prix déterminé, dans des délais précis.'),
            ('Qu\'est-ce que le "devis" dans un contrat de construction?', ['Le document détaillant les spécifications techniques et matériaux requis', 'Le prix des travaux', 'Le plan d\'architecte', 'Le calendrier'], 'A', 'Le devis décrit en détail les matériaux, équipements, méthodes et normes à respecter pour les travaux.'),
            ('Qu\'est-ce que le "cautionnement d\'exécution"?', ['Une garantie assurant que l\'entrepreneur exécutera les travaux conformément au contrat', 'Une assurance construction', 'Un dépôt de garantie', 'Une lettre de crédit'], 'A', 'Le cautionnement d\'exécution garantit au donneur d\'ouvrage que l\'entrepreneur remplira ses obligations contractuelles.'),
            ('Qu\'est-ce qu\'un "avenant" au contrat?', ['Un document modifiant certaines clauses du contrat original', 'Une annexe au devis', 'Un ordre de changement', 'Une facture supplémentaire'], 'A', 'L\'avenant est un document signé par les deux parties qui modifie des dispositions du contrat original (prix, délais, portée).'),
            ('Qu\'est-ce que la "responsabilité solidaire" en construction?', ['La responsabilité partagée entre entrepreneur général et sous-traitants pour les dettes sociales', 'La responsabilité exclusive de l\'entrepreneur', 'La responsabilité du client', 'L\'assurance responsabilité'], 'A', 'Dans certains cas, l\'entrepreneur général et ses sous-traitants sont solidairement responsables des dettes envers la CCQ et les autorités fiscales.'),
            ('Qu\'est-ce que la "LOI 122" concernant la construction?', ['Une loi modifiant les règles de la publicité des droits et privilèges', 'Une loi sur la sécurité', 'Une loi fiscale', 'Une loi sur l\'environnement'], 'A', 'La Loi 122 a réformé le régime des privilèges et de la publicité des droits dans l\'industrie de la construction.'),
            ('Qu\'est-ce qu\'un "appel d\'offres public"?', ['Une procédure transparente invitant tous les entrepreneurs qualifiés à soumissionner', 'Une invitation privée', 'Un concours d\'architecture', 'Une vente aux enchères'], 'A', 'L\'appel d\'offres public est un processus encadré par la loi pour assurer l\'équité et la transparence dans l\'attribution des contrats publics.'),
            ('Qu\'est-ce que le "droit de regard" du donneur d\'ouvrage?', ['Le droit du client de surveiller l\'avancement et la qualité des travaux', 'Le droit de modifier les plans', 'Le droit d\'arrêter le chantier', 'Le droit de changer d\'entrepreneur'], 'A', 'Le donneur d\'ouvrage (client) a le droit de surveiller l\'exécution des travaux, sans toutefois ingérer dans la direction du chantier.'),
            ('Qu\'est-ce qu\'un "certificat de paiement" en construction?', ['Un document attestant que des travaux ont été réalisés et autorisant le versement', 'Une facture', 'Un reçu', 'Un chèque'], 'A', 'Le certificat de paiement est émis par l\'architecte ou ingénieur pour confirmer l\'avancement et autoriser le paiement à l\'entrepreneur.'),
            ('Qu\'est-ce que la "réception provisoire" des travaux?', ['La constatation que les travaux sont suffisamment avancés pour une prise de possession', 'La fin définitive des travaux', 'L\'inspection finale', 'La signature du contrat'], 'A', 'La réception provisoire permet au client de prendre possession des lieux avant la réception définitive, avec une liste de réserves.'),
            ('Qu\'est-ce que la "réception définitive"?', ['L\'acceptation finale des travaux par le client, sans réserve majeure', 'La fin du chantier', 'Le dernier paiement', 'La fermeture du dossier'], 'A', 'La réception définitive marque l\'acceptation finale des travaux et le début des garanties de bon fonctionnement.'),
            ('Qu\'est-ce que la "liste de réserves"?', ['Une liste des travaux mineurs à corriger ou compléter avant la réception définitive', 'Une liste des matériaux', 'Un inventaire d\'outillage', 'Un rapport de chantier'], 'A', 'La liste de réserves identifie les travaux restants ou défectuosités mineures que l\'entrepreneur s\'engage à corriger.'),
            ('Qu\'est-ce que la "force majeure" dans un contrat?', ['Un événement imprévisible et irrésistible qui suspend les obligations contractuelles', 'Une clause de résiliation', 'Une pénalité', 'Une garantie'], 'A', 'La force majeure (catastrophe naturelle, guerre, pandémie) libère les parties de leurs obligations pendant sa durée.'),
            ('Qu\'est-ce qu\'un "cautionnement de retenue"?', ['Une garantie qui remplace la retenue de garantie détenue par le donneur d\'ouvrage', 'Une assurance', 'Un dépôt', 'Une lettre de crédit'], 'A', 'Le cautionnement de retenue permet à l\'entrepreneur de récupérer la retenue de garantie avant la fin des travaux, en fournissant une garantie bancaire.'),
            ('Qu\'est-ce que la "résiliation pour faute"?', ['La terminaison du contrat due à un manquement grave d\'une partie', 'La fin normale du contrat', 'La démission de l\'entrepreneur', 'L\'annulation par consentement'], 'A', 'La résiliation pour faute intervient quand une partie ne respecte pas ses obligations essentielles (retard, défauts, abandon).'),
            ('Qu\'est-ce que la "médiation" dans les litiges de construction?', ['Un processus de résolution de conflit avec l\'aide d\'un tiers neutre', 'Un procès', 'Un arbitrage', 'Une négociation directe'], 'A', 'La médiation est un mode alternatif de résolution des conflits où un médiateur impartial aide les parties à trouver une entente.'),
            ('Qu\'est-ce qu\'un "contrat à frais remboursables"?', ['Un contrat où le client paie les coûts réels plus une marge de profit convenue', 'Un contrat à prix fixe', 'Un contrat horaire', 'Un contrat sans limite'], 'A', 'Le contrat à frais remboursables est utilisé quand la portée des travaux est difficile à définir, avec des coûts réels + une marge négociée.'),
            ('Qu\'est-ce que la "garantie légale de cinq ans"?', ['La garantie couvrant les vices cachés et défauts majeurs affectant la structure ou l\'étanchéité', 'La garantie des finitions', 'La garantie des équipements', 'L\'assurance habitation'], 'A', 'Cette garantie légale de 5 ans couvre les vices cachés graves qui rendent l\'immeuble impropre à son usage ou qui en diminuent la valeur.'),
            ('Qu\'est-ce que la "garantie de un an"?', ['La garantie couvrant les défauts de finition et de fonctionnement des équipements', 'La garantie structurelle', 'La garantie des matériaux', 'L\'assurance chantier'], 'A', 'La garantie d\'un an couvre les défauts apparents ou cachés non graves, comme les problèmes de finition ou d\'équipements non structurels.'),
            ('Qu\'est-ce qu\'un "contrat clé en main"?', ['Un contrat où l\'entrepreneur livre un projet complet et prêt à utiliser', 'Un contrat de nettoyage', 'Un contrat de fourniture', 'Un contrat d\'entretien'], 'A', 'Le contrat clé en main confie à l\'entrepreneur la responsabilité complète du projet, de la conception à la livraison finale.'),
            ('Qu\'est-ce que le "droit de rétention" en construction?', ['Le droit du constructeur de retenir les lieux pour non-paiement', 'Le droit de l\'employé', 'Le droit du client', 'Une clause de pénalité'], 'A', 'Le constructeur peut refuser de livrer l\'ouvrage ou le retenir tant que le paiement intégral n\'est pas effectué.'),
            ('Qu\'est-ce que "l\'offre irrévocable" en soumission?', ['Une soumission qui ne peut être retirée pendant une période déterminée', 'Une soumission ouverte', 'Un contrat signé', 'Une promesse unilatérale'], 'A', 'L\'offre irrévocable engage l\'entrepreneur à maintenir son prix pendant la période de validité de la soumission.'),
            ('Qu\'est-ce que la "sous-traitance en cascade"?', ['Une chaîne de sous-traitants où le sous-traitant engage lui-même d\'autres sous-traitants', 'Une sous-traitance exclusive', 'Un contrat multiple', 'Une sous-traitance interdite'], 'A', 'La sous-traitance en cascade implique plusieurs niveaux de sous-traitants, ce qui peut complexifier les responsabilités et les recours.'),
            ('Qu\'est-ce que la "Loi sur les contrats des organismes publics"?', ['La loi qui encadre les processus d\'appel d\'offres et d\'attribution des contrats publics', 'La loi sur la construction', 'Le code municipal', 'La loi sur l\'administration publique'], 'A', 'Cette loi régit les modalités de passation des contrats par les municipalités, sociétés d\'État et autres organismes publics.'),
            ('Qu\'est-ce qu\'un "devis quantitatif"?', ['Un document détaillant les quantités estimées de chaque élément de construction', 'Un plan d\'architecte', 'Un calendrier de réalisation', 'Un budget sommaire'], 'A', 'Le devis quantitatif (quantities takeoff) énumère les quantités de matériaux et de main-d\'œuvre nécessaires à la réalisation du projet.'),
            ('Qu\'est-ce que la "clause d\'indexation" dans un contrat?', ['Une clause ajustant le prix selon l\'évolution d\'indices économiques', 'Une clause de résiliation', 'Une clause de pénalité', 'Une clause d\'arbitrage'], 'A', 'La clause d\'indexation permet d\'ajuster le prix du contrat en fonction de l\'inflation ou de la variation du coût des matériaux.'),
            ('Qu\'est-ce que le "cautionnement de garantie"?', ['Une garantie couvrant les défauts de construction après la réception des travaux', 'Une assurance chantier', 'Un dépôt de garantie', 'Une garantie de soumission'], 'A', 'Le cautionnement de garantie assure la correction des défauts de construction qui apparaissent pendant la période de garantie post-réception.'),
            ('Qu\'est-ce que la "propriété intellectuelle" des plans et devis?', ['Les droits d\'auteur de l\'architecte ou ingénieur sur les documents du projet', 'Le droit du constructeur', 'La propriété des matériaux', 'Le droit du client'], 'A', 'Les plans et devis sont protégés par le droit d\'auteur et ne peuvent être réutilisés sans l\'autorisation de leur créateur.'),
            ('Qu\'est-ce que le "contrat de partenariat public-privé" (PPP)?', ['Un contrat où les secteurs public et privé collaborent pour financer et réaliser un projet', 'Un contrat de sous-traitance', 'Une coentreprise', 'Une société en commandite'], 'A', 'Le PPP est un mode de réalisation de projets où le partenaire privé conçoit, finance, construit et parfois exploite l\'infrastructure publique.'),
            ('Qu\'est-ce que "l\'arbitrage" dans les litiges de construction?', ['Un mode de résolution où un arbitre rend une décision exécutoire', 'Une médiation', 'Un procès', 'Une négociation'], 'A', 'L\'arbitrage est un processus où un arbitre impartial entend les parties et rend une sentence qui lie les parties.'),
            ('Qu\'est-ce que la "prescription" en droit de la construction?', ['Le délai après lequel une action en justice n\'est plus recevable', 'Une ordonnance médicale', 'Un permis', 'Une réclamation'], 'A', 'Les recours en construction sont soumis à des délais de prescription (généralement 3 ans pour les vices apparents, etc.).'),
            ('Qu\'est-ce que la "notification de défaut"?', ['Un avis écrit informant l\'entrepreneur d\'une non-conformité ou d\'un défaut', 'Un ordre de changement', 'Une facture', 'Un bon de commande'], 'A', 'La notification de défaut est le document formel par lequel le client ou le consultant informe l\'entrepreneur d\'un travail non conforme.'),
        ]
    },
    'ch_entgen_04': {
        'name': 'Code de construction et plans',
        'questions': [
            # --- 45 questions: Code de construction, lecture de plans, permis, inspections ---
            ('Qu\'est-ce que le Code de construction du Québec?', ['Un règlement établissant les normes techniques minimales pour la construction', 'Un guide de design', 'Un code de déontologie', 'Un manuel de procédures'], 'A', 'Le Code de construction est un ensemble de normes techniques obligatoires visant la sécurité, la santé et l\'accessibilité des bâtiments.'),
            ('Quelle est la fréquence de mise à jour du Code de construction du Québec?', ['Tous les 5 ans', 'Tous les 2 ans', 'Tous les 10 ans', 'Tous les ans'], 'A', 'Le Code de construction est révisé et publié à intervalles d\'environ 5 ans pour intégrer les nouvelles normes et technologies.'),
            ('Qu\'est-ce que le "CNB" (Code national du bâtiment)?', ['Un code modèle canadien servant de base au Code de construction du Québec', 'Le Code de la construction français', 'Une norme américaine', 'Un guide de l\'industrie'], 'A', 'Le Code national du bâtiment (CNB) est un document de référence publié par le CNRC, adapté par le Québec avec des modifications.'),
            ('Qu\'est-ce que la "charge au sol" dans un plan de structure?', ['La force maximale que le sol peut supporter sous les fondations', 'Le poids du bâtiment', 'La pression atmosphérique', 'La résistance des matériaux'], 'A', 'La charge au sol est la capacité portante du terrain, déterminée par une étude géotechnique, essentielle pour dimensionner les fondations.'),
            ('Qu\'est-ce que la "zonage" en urbanisme?', ['La division du territoire en zones avec des usages et normes spécifiques', 'Le marquage au sol', 'La classification des bâtiments', 'La sectorisation des chantiers'], 'A', 'Le zonage est un outil de planification urbaine qui régit les usages permis, la hauteur, le recul et la densité des constructions dans chaque zone.'),
            ('Qu\'est-ce qu\'un "permis de construire"?', ['Une autorisation municipale nécessaire avant le début des travaux', 'Un contrat de construction', 'Une certification professionnelle', 'Une assurance'], 'A', 'Le permis de construire est délivré par la municipalité après vérification de la conformité du projet au Code et aux règlements municipaux.'),
            ('Qu\'est-ce que le "certificat d\'autorisation" de la RBQ?', ['Une autorisation pour réaliser des travaux de construction d\'un certain type', 'Un permis de conduire', 'Une licence d\'exploitation', 'Un certificat de compétence'], 'A', 'Le certificat d\'autorisation RBQ est requis pour les entrepreneurs et constructeurs-propriétaires avant d\'entreprendre certains travaux.'),
            ('Qu\'est-ce que la "schéma d\'aménagement" dans une municipalité?', ['Un document de planification à long terme du développement du territoire', 'Un plan d\'architecte', 'Un devis descriptif', 'Un calendrier de construction'], 'A', 'Le schéma d\'aménagement est un document de planification stratégique qui oriente le développement du territoire sur plusieurs années.'),
            ('Qu\'est-ce qu\'un "plan d\'implantation"?', ['Un plan montrant l\'emplacement du bâtiment sur le terrain', 'Un plan de fondations', 'Un plan d\'étage', 'Un plan de toiture'], 'A', 'Le plan d\'implantation situe le bâtiment sur le terrain et indique les distances par rapport aux limites, les accès et les stationnements.'),
            ('Qu\'est-ce qu\'une "coupe" dans les plans de construction?', ['Une vue en section verticale du bâtiment montrant les différents niveaux', 'Une coupe de bois', 'La découpe d\'un matériau', 'Un plan de détail'], 'A', 'La coupe est une représentation verticale du bâtiment qui montre les hauteurs, les fondations, la toiture et les différents niveaux.'),
            ('Qu\'est-ce que la "résistance au feu" d\'un matériau?', ['La durée pendant laquelle un matériau conserve ses propriétés sous l\'effet du feu', 'La température d\'inflammation', 'Le point de fusion', 'La vitesse de propagation des flammes'], 'A', 'La résistance au feu est mesurée en minutes (15, 45, 60, 90 min) et indique combien de temps un élément résiste au feu avant de perdre ses fonctions.'),
            ('Qu\'est-ce que le "degré de résistance au feu" (DRF)?', ['Une cote de résistance au feu attribuée à un élément de construction', 'La classification des matériaux', 'La température maximale', 'Le pourcentage de protection'], 'A', 'Le DRF est une classification qui détermine la capacité d\'un élément de construction à résister au feu selon les normes du Code.'),
            ('Qu\'est-ce que la "charge permanente" (dead load) dans un calcul structural?', ['Le poids propre de la structure et des éléments fixes du bâtiment', 'Le poids des occupants', 'La charge de neige', 'La pression du vent'], 'A', 'La charge permanente inclut le poids des matériaux de construction, de la structure, des cloisons et des équipements fixes.'),
            ('Qu\'est-ce que la "charge d\'occupation" (live load)?', ['La charge variable due à l\'utilisation normale du bâtiment (personnes, meubles)', 'Le poids de la neige', 'La pression du vent', 'Le poids des équipements fixes'], 'A', 'La charge d\'occupation est une charge variable déterminée par l\'usage du bâtiment (bureau, entrepôt, salle de spectacle).'),
            ('Qu\'est-ce que la "charge de neige" dans le Code?', ['La charge de neige au sol déterminée selon la région et la topographie', 'Le poids des bancs de neige', 'L\'épaisseur de neige prévue', 'La fréquence des chutes de neige'], 'A', 'Le Code fournit des cartes de charge de neige au sol selon les régions du Québec, essentielles pour le calcul des toitures.'),
            ('Qu\'est-ce que la "charge de vent" dans le calcul structural?', ['La pression exercée par le vent sur la structure selon la hauteur et la région', 'La force du vent en km/h', 'La direction des vents dominants', 'La pression atmosphérique'], 'A', 'La charge de vent est calculée selon la vitesse de vent de référence, la hauteur du bâtiment et son exposition.'),
            ('Qu\'est-ce que le "plan de fondations"?', ['Un plan détaillant les semelles, murs de fondation, drains et dalles', 'Un plan de site', 'Un plan d\'implantation', 'Un plan d\'étage'], 'A', 'Le plan de fondations montre en détail la conception des semelles, des murs de fondation, du drainage et de la dalle au sol.'),
            ('Qu\'est-ce qu\'une "étude de sol" (géotechnique)?', ['Une analyse des propriétés du sol pour déterminer sa capacité portante', 'Un sondage archéologique', 'Une analyse de l\'eau souterraine', 'Une carte géologique'], 'A', 'L\'étude de sol est requise pour les bâtiments importants afin de déterminer la nature du sol, sa capacité portante et le type de fondations adapté.'),
            ('Qu\'est-ce qu\'un "inspecteur municipal" dans la construction?', ['Un fonctionnaire qui vérifie la conformité des travaux au Code et permis', 'Un inspecteur de la CCQ', 'Un expert en sinistres', 'Un arpenteur'], 'A', 'L\'inspecteur municipal visite le chantier à différentes étapes pour s\'assurer que la construction respecte le permis et le Code.'),
            ('Qu\'est-ce que le "zonage agricole" (CPTAQ)?', ['Une réglementation protégeant les terres agricoles et limitant la construction', 'Un type de culture', 'Une classification des sols', 'Un programme de subvention'], 'A', 'La Commission de protection du territoire agricole (CPTAQ) régit les constructions en zone agricole, avec des autorisations spécifiques.'),
            ('Qu\'est-ce que l\'"étanchéité à l\'air" d\'un bâtiment?', ['La capacité de l\'enveloppe à limiter les infiltrations d\'air incontrôlées', 'L\'imperméabilité à l\'eau', 'La résistance au vent', 'L\'isolation thermique'], 'A', 'L\'étanchéité à l\'air est essentielle pour l\'efficacité énergétique, le confort et la durabilité du bâtiment, mesurée par un test d\'infiltrométrie.'),
            ('Qu\'est-ce qu\'un "plan de toiture"?', ['Un plan montrant la pente, les matériaux et les détails du système de toiture', 'Un plan d\'étage supérieur', 'Un plan de fondations', 'Un plan d\'implantation'], 'A', 'Le plan de toiture indique les pentes, les matériaux de couverture, les solins, les gouttières et les équipements en toiture.'),
            ('Qu\'est-ce que la "ventilation" selon le Code?', ['Les exigences minimales de renouvellement d\'air pour la santé des occupants', 'La climatisation', 'Le chauffage', 'L\'extraction mécanique'], 'A', 'Le Code de construction prescrit des débits de ventilation minimum selon l\'usage et l\'occupation du bâtiment pour assurer la qualité de l\'air intérieur.'),
            ('Qu\'est-ce que l\'"accessibilité universelle" dans le Code?', ['Les normes obligeant les bâtiments à être accessibles aux personnes handicapées', 'L\'accès libre au public', 'Les sorties de secours', 'Les stationnements'], 'A', 'Le Code impose des normes d\'accessibilité pour les personnes handicapées dans les bâtiments publics et multilogements (portes, rampes, ascenseurs, salles de bain).'),
            ('Qu\'est-ce qu\'un "plan de localisation"?', ['Un plan montrant l\'emplacement exact du bâtiment sur le lot avec dimensions', 'Un plan de région', 'Un plan d\'architecte', 'Un plan de services publics'], 'A', 'Le plan de localisation est préparé par un arpenteur-géomètre et situe précisément le bâtiment par rapport aux limites du terrain.'),
            ('Qu\'est-ce que le "règlement de construction" municipal?', ['Un règlement local complétant le Code de construction avec des exigences spécifiques', 'Le Code de construction', 'La loi sur l\'urbanisme', 'Le permis de construire'], 'A', 'Chaque municipalité peut adopter des règlements de construction supplémentaires adaptés à son territoire, qui s\'ajoutent au Code.'),
            ('Qu\'est-ce qu\'un "plan d\'architecture"?', ['Un plan décrivant l\'apparence, l\'aménagement et les dimensions du bâtiment', 'Un plan structural', 'Un plan de mécanique', 'Un plan d\'électricité'], 'A', 'Le plan d\'architecture montre l\'organisation des espaces, les dimensions, les portes, fenêtres et finitions du bâtiment.'),
            ('Qu\'est-ce que la "classification des bâtiments" selon le Code?', ['Une classification par usage principal et nombre d\'étages déterminant les exigences', 'Une catégorie de permis', 'Un type de construction', 'Une classe d\'assurance'], 'A', 'Le Code classe les bâtiments selon leur usage (A: habitations, B: soins, C: réunions, D: commerces, E: bureaux, F: industries) et leur hauteur.'),
            ('Qu\'est-ce qu\'une "sortie" dans le Code de construction?', ['Un chemin d\'évacuation conforme permettant l\'évacuation sécuritaire des occupants', 'Une porte extérieure', 'Une issue de secours', 'Un escalier'], 'A', 'Les sorties doivent respecter des normes de largeur, d\'éclairage, de signalisation et de distance maximale selon l\'occupation du bâtiment.'),
            ('Qu\'est-ce que la "distance de parcours" pour l\'évacuation?', ['La distance maximale à parcourir pour atteindre une sortie depuis un point du bâtiment', 'La distance entre les sorties', 'La largeur du corridor', 'La hauteur de l\'escalier'], 'A', 'La distance de parcours maximale est prescrite par le Code selon le type d\'occupation et le système de gicleurs présent.'),
            ('Qu\'est-ce qu\'un "escalier de secours"?', ['Un escalier protégé conçu pour l\'évacuation d\'urgence des occupants', 'Un escalier extérieur', 'Un escalier en colimaçon', 'Une échelle de toit'], 'A', 'L\'escalier de secours doit être à l\'épreuve du feu, bien éclairé et dégagé en tout temps, menant directement à l\'extérieur.'),
            ('Qu\'est-ce que le "système de gicleurs"?', ['Un système d\'extinction automatique d\'incendie obligatoire dans certains bâtiments', 'Un système d\'arrosage', 'Un extincteur portatif', 'Une alarme incendie'], 'A', 'Le système de gicleurs est requis selon la hauteur, la superficie et l\'usage du bâtiment pour combattre automatiquement les incendies.'),
            ('Qu\'est-ce qu\'un "plan de niveau" ou "plan d\'étage"?', ['Un plan montrant l\'agencement d\'un étage avec les pièces, portes et fenêtres', 'Un plan de fondations', 'Une coupe transversale', 'Un plan de toiture'], 'A', 'Le plan d\'étage représente la vue en plan d\'un niveau du bâtiment, avec l\'organisation des espaces, les dimensions et les ouvertures.'),
            ('Qu\'est-ce que la "gaine technique" dans un bâtiment?', ['Un conduit vertical pour le passage des installations mécaniques et électriques', 'Une colonne structural', 'Un puits de lumière', 'Une cheminée'], 'A', 'Les gaines techniques permettent le passage des tuyaux, conduits électriques et de ventilation à travers les étages.'),
            ('Qu\'est-ce que la "résistance à la compression" du béton?', ['La capacité du béton à résister à une force de compression, mesurée en MPa', 'La résistance à la traction', 'La dureté du béton', 'L\'élasticité'], 'A', 'La résistance à la compression du béton est exprimée en mégapascals (MPa) et détermine son usage dans les structures (fondations, colonnes, dalles).'),
            ('Qu\'est-ce qu\'un "plan de coffrage"?', ['Un plan montrant la disposition et les dimensions des coffrages pour le béton', 'Un plan d\'architecte', 'Un plan de fondations', 'Un plan de structure métallique'], 'A', 'Le plan de coffrage indique l\'emplacement, les dimensions et les armatures des éléments de béton à couler (dalles, poutres, colonnes).'),
            ('Qu\'est-ce qu\'un "permis de rénovation"?', ['Une autorisation requise pour des travaux de rénovation modifiant la structure ou l\'usage', 'Un permis de construire complet', 'Une simple déclaration', 'Une autorisation verbale'], 'A', 'Des travaux de rénovation majeurs (modification de structure, d\'usage, agrandissement) nécessitent un permis de rénovation.'),
            ('Qu\'est-ce que le "règlement sur les entrées de cour" dans une municipalité?', ['Les normes de localisation et dimensions des entrées de cour pour les véhicules', 'Le Code civil', 'La loi sur l\'aménagement', 'Le Code de sécurité'], 'A', 'Le règlement municipal peut imposer des normes pour les entrées de cour (largeur, pente, revêtement, distance des intersections).'),
            ('Qu\'est-ce que la "servitude" dans un contexte de construction?', ['Une charge imposée sur un terrain au bénéfice d\'un autre terrain (passage, vue, égout)', 'Une taxe foncière', 'Une restriction administrative', 'Une assurance'], 'A', 'La servitude est un droit réel qui limite l\'usage d\'un terrain au profit d\'un autre, par exemple un droit de passage ou d\'égout.'),
            ('Qu\'est-ce qu\'un "plan d\'arpentage"?', ['Un plan officiel délimitant les limites du terrain, établi par un arpenteur-géomètre', 'Un plan d\'implantation', 'Un plan cadastral', 'Un plan de lotissement'], 'A', 'Le plan d\'arpentage est un document officiel qui certifie les limites, les dimensions et la superficie d\'un terrain.'),
            ('Qu\'est-ce que le "règlement sur les nuisances"?', ['Un règlement municipal limitant le bruit, la poussière et les horaires de construction', 'Un règlement de chantier', 'Un code de conduite', 'Une norme environnementale'], 'A', 'Les municipalités ont des règlements sur les nuisances qui encadrent les heures de travaux, le bruit et la gestion de la poussière sur les chantiers.'),
            ('Qu\'est-ce que la "déclaration de conformité" d\'un bâtiment?', ['Une attestation confirmant que la construction respecte le Code et les règlements', 'Un certificat d\'assurance', 'Un permis de construire', 'Un rapport d\'inspection'], 'A', 'La déclaration de conformité est un document signé par le professionnel (architecte, ingénieur) attestant que les travaux respectent les normes applicables.'),
            ('Qu\'est-ce que la "phase 1 environnementale" (étude de sol contaminé)?', ['Une évaluation historique du site pour détecter une contamination potentielle', 'Une analyse de sol détaillée', 'Un forage', 'Un test de l\'eau'], 'A', 'L\'étude environnementale de phase 1 est une recherche documentaire et une visite de site pour identifier les sources de contamination potentielles avant construction.'),
            ('Qu\'est-ce que la "réglementation sur les piscines résidentielles"?', ['Les normes de sécurité obligeant une enceinte et des dispositifs de sécurité', 'Un permis de construire', 'Une certification', 'Un zonage'], 'A', 'La réglementation impose des normes strictes pour les piscines résidentielles (clôture, barrière de sécurité, alarme) pour prévenir les noyades.'),
            ('Qu\'est-ce que le "zonage de densité" dans une municipalité?', ['Une réglementation du nombre de logements ou de la superficie construite par terrain', 'La hauteur maximale', 'Le recul obligatoire', 'Lecoefficient d\'occupation du sol'], 'A', 'Le zonage de densité limite le nombre de logements ou la superficie construite par superficie de terrain (COS - coefficient d\'occupation du sol).'),
        ]
    }
}

# Verify the existing counts
import psycopg2

conn = psycopg2.connect(f"postgresql://{user}:{pw}@localhost:5432/metierium")
cur = conn.cursor()

# Get max question number
cur.execute("""
SELECT COALESCE(MAX(CAST(SUBSTRING(id FROM 'q_entgen_(\\d+)') AS INTEGER)), 0)
FROM "Question" WHERE "tradeId"='cmt_entrepreneur_general_001'
""")
max_num = cur.fetchone()[0]
print(f"Starting question number: {max_num + 1}")

qid = max_num + 1
total = 0

for ch_id, ch_data in CHAPTERS.items():
    print(f"\nGenerating {len(ch_data['questions'])} questions for {ch_id}")
    for q_data in ch_data['questions']:
        q_text, options_list, answer, explanation = q_data
        opt_json = json.dumps(options_list, ensure_ascii=False)
        # Use parameterized query to avoid SQL injection and escaping issues
        cur.execute(f"""
        INSERT INTO "Question" (id, "tradeId", "chapterId", type, difficulty, question, options, answer, explanation, locale, "createdAt", "updatedAt")
        VALUES ('q_entgen_{qid:03d}', %s, %s, 'MCQ', 'MEDIUM', %s, %s, %s, %s, 'fr', %s, %s)
        ON CONFLICT (id) DO NOTHING
        """, (TRADE, ch_id, q_text, opt_json, answer, explanation, TS, TS))
        qid += 1
        total += 1

conn.commit()

# Verify
cur.execute("""
SELECT c.id, COUNT(q.id) as questions
FROM "Chapter" c
LEFT JOIN "Question" q ON q."chapterId"=c.id AND q."tradeId"='cmt_entrepreneur_general_001'
WHERE c."tradeId"='cmt_entrepreneur_general_001'
GROUP BY c.id
ORDER BY c.number
""")
for row in cur.fetchall():
    print(f"  {row[0]}: {row[1]} questions")

cur.execute("SELECT COUNT(*) FROM \"Question\" WHERE \"tradeId\"='cmt_entrepreneur_general_001'")
total_q = cur.fetchone()[0]
print(f"\nTotal ENTREPRENEUR GÉNÉRAL questions: {total_q}")

conn.close()
print(f"\nGenerated {total} new questions ({qid - (max_num + 1)})")
