INSERT INTO "Question" (id,"tradeId","chapterId",question,options,answer,difficulty,type,locale,"createdAt","updatedAt") VALUES
('q_sst_001','cmt_coordsst_001','ch_sst_01','Quelle loi regit la sante et securite du travail au Quebec?','["LST (Loi SST)","Loi sur le batiment","Code civil","Code criminel"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_002','cmt_coordsst_001','ch_sst_01','Quel organisme applique la SST au Quebec?','["CNESST","RBQ","CCQ","CMEQ"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_003','cmt_coordsst_001','ch_sst_01','Quel montant declenche lobligation dun coordonnateur SST sur chantier?','["200 000$","50 000$","500 000$","1 000 000$"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_004','cmt_coordsst_001','ch_sst_02','Quelle methode d''analyse des risques est la plus courante?','["JSA (Job Safety Analysis)","SWOT","PESTEL","PDCA"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_005','cmt_coordsst_001','ch_sst_02','Quel danger cause la silicose?','["Silice cristalline","Amiante","CO","Bruit"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_006','cmt_coordsst_001','ch_sst_02','Quel est le premier niveau de la hierarchie des controles?','["Elimination","Substitution","EPI","Administratif"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_007','cmt_coordsst_001','ch_sst_03','A quelle hauteur la protection antichute est-elle obligatoire?','["3 metres","1 metre","5 metres","10 metres"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_008','cmt_coordsst_001','ch_sst_03','Capacite minimale dun point dancrage antichute?','["5000 lb (22kN)","1000 lb","2000 lb","10000 lb"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_009','cmt_coordsst_001','ch_sst_03','Angle maximal d''une echelle?','["4:1 (75 degres)","3:1","5:1","2:1"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_010','cmt_coordsst_001','ch_sst_04','Defintion espace clos?','["Acces limite, non concu pour occupation continue","Petite piece","Sous-sol","Toiture"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_011','cmt_coordsst_001','ch_sst_04','Niveau O2 acceptable dans un espace clos?','["19.5-23.5%","15-18%","10-15%","25-30%"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_012','cmt_coordsst_001','ch_sst_05','Procedure obligatoire avant intervention electrique?','["Cadenassage (Lockout/Tagout)","Debrancher","Appeler electricien","Couper disjoncteur"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_013','cmt_coordsst_001','ch_sst_05','Temperature d''un arc electrique?','["20 000 C","1 000 C","5 000 C","100 C"]','A','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_014','cmt_coordsst_001','ch_sst_06','Classe d''extincteur pour feu electrique?','["C","A","B","D"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_015','cmt_coordsst_001','ch_sst_06','Frequence exercice evacuation garderie?','["1x/3 mois","1x/6 mois","1x/an","1x/semaine"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_016','cmt_coordsst_001','ch_sst_07','Limite exposition bruit pour 8h?','["85 dB","90 dB","75 dB","100 dB"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_017','cmt_coordsst_001','ch_sst_07','Quel masque pour la silice?','["P100/N95","Masque chirurgical","Masque tissu","Aucun"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_018','cmt_coordsst_001','ch_sst_08','Delai declaration lesion CNESST?','["4 jours","30 jours","1 jour","60 jours"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_019','cmt_coordsst_001','ch_sst_08','Methode enquete accident populaire?','["Arbre des causes","Diagramme Pareto","Flowchart","Brainstorming"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_020','cmt_coordsst_001','ch_sst_01','Sanction pour non-conformite SST?','["Amende 300-10 000$","Suspension licence","Emprisonnement","Avertissement verbal"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_021','cmt_coordsst_001','ch_sst_02','Exposition max CO (monoxyde carbone) travail?','["35 ppm","10 ppm","100 ppm","5 ppm"]','A','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_022','cmt_coordsst_001','ch_sst_03','Longe antichute simple longueur?','["1.8 metres","3 metres","0.5 metre","5 metres"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_023','cmt_coordsst_001','ch_sst_04','Gaz a tester dans espace clos?','["O2, LIE, H2S, CO","CO2, N2, Ar","CH4, C3H8, C4H10","NH3, Cl2, SO2"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_024','cmt_coordsst_001','ch_sst_05','Distance securitaire arc electrique basse tension?','["2-15 pieds","50 pieds","1 pied","100 pieds"]','A','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_025','cmt_coordsst_001','ch_sst_06','Trousse premiers soins type II pour?','["5-25 employes","1-5 employes","25-50 employes","50+ employes"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_026','cmt_coordsst_001','ch_sst_07','Vibration: syndrome main-bras cause par?','["Marteau-piqueur","Ordinateur","Volant","Souris"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_027','cmt_coordsst_001','ch_sst_08','Comite SST requis pour combien demployes?','["5-20 employes","1-5 employes","20-50 employes","50+ employes"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_028','cmt_coordsst_001','ch_sst_01','Quel document doit etre affiche sur chaque chantier?','["Coffret chantier (licences, assurances, SST)","Plan architecte","Budget","Calendrier"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_029','cmt_coordsst_001','ch_sst_02','Quel risque cause le H2S?','["Gaz toxique (odeur oeuf pourri)","Explosion","Irritation peau","Cancer"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_030','cmt_coordsst_001','ch_sst_03','Garde-corps hauteur minimum?','["1 metre (42 pouces)","0.5 metre","1.5 metres","2 metres"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_031','cmt_coordsst_001','ch_sst_04','Role surveillant espace clos?','["Rester exterior, communiquer, ne pas entrer","Entrer avec travailleur","Actionner alarme","Appeler pompiers"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_032','cmt_coordsst_001','ch_sst_05','Verification gants isolants frequence?','["Aux 6 mois","Chaque jour","Aux 2 ans","Jamais"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_033','cmt_coordsst_001','ch_sst_06','Extincteur CO2 utilise pour?','["Classe B et C","Classe A seulement","Classe D","Classe K"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_034','cmt_coordsst_001','ch_sst_07','Poids max manutention femme assis?','["23 kg","34 kg","15 kg","40 kg"]','A','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_035','cmt_coordsst_001','ch_sst_08','Etape initiale enquete accident?','["Securiser les lieux","Identifier temoins","Rediger rapport","Analyse causes"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_036','cmt_coordsst_001','ch_sst_01','ASP Construction est?','["Association sectorielle SST","Ordre professionnel","Syndicat","Ministere"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_037','cmt_coordsst_001','ch_sst_02','Niveau LIE acceptable dans espace clos?','["<10%","<5%","<50%","<1%"]','A','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_038','cmt_coordsst_001','ch_sst_03','Harnais verifie a quelle frequence?','["Annuelle par competent","Jamais","Mensuelle","Quotidienne"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_039','cmt_coordsst_001','ch_sst_04','Permis espace clos requis?','["Oui, signe par coordonnateur","Non","Seulement si gaz detecte","A la discretion travailleur"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_040','cmt_coordsst_001','ch_sst_05','GFCI doit etre installe?','["Prises exterieures et zones humides","Partout","Cuisine seulement","Salle de bain seulement"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_041','cmt_coordsst_001','ch_sst_06','Inspection extincteurs frequence mensuelle?','["Visuelle (pression, goupille, acces)","Pleine recharge","Essai hydrostatique","Nettoyage"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_042','cmt_coordsst_001','ch_sst_07','Periode declaration accident travail CNESST?','["2 ans","6 mois","30 jours","5 ans"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_043','cmt_coordsst_001','ch_sst_08','Exemple cause immediate accident?','["Acte dangereux + condition dangereuse","Manque formation","Procedure inadequate","Culture securite"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_044','cmt_coordsst_001','ch_sst_01','Quel reglement detaille les normes techniques SST?','["RSST","LST","CCQ","CNESST"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_045','cmt_coordsst_001','ch_sst_02','Quel equipement protege contre la silice?','["Aspiration a la source + eau + masque P100","Ventilateur","Casque","Lunettes"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_046','cmt_coordsst_001','ch_sst_03','Echafaudage: qui peut le monter?','["Travailleur forme et qualifie","Nimporte qui","Ingenieur","Coordonnateur SST"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_047','cmt_coordsst_001','ch_sst_04','Equipement necessaire espace clos?','["Detecteur multigaz, harnais, treuil, communication","Lampe torche seulement","Casque et gants","Bottes et lunettes"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_048','cmt_coordsst_001','ch_sst_05','Classe gants isolants 0?','["1000V max","500V max","5000V max","100V max"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_049','cmt_coordsst_001','ch_sst_06','Extincteur poudre ABC utilise pour?','["A, B, C (tout usage)","A seulement","B et C","D seulement"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_050','cmt_coordsst_001','ch_sst_07','Duree max exposition 90 dB bruit?','["4 heures","8 heures","2 heures","1 heure"]','A','HARD','MCQ','fr',NOW(),NOW());