INSERT INTO "Question" (id,"tradeId","chapterId",question,options,answer,difficulty,type,locale,"createdAt","updatedAt") VALUES
('q_asc_001','cmt_ascenseur_001','ch_asc_01','Quel code de securite reglemente les ascenseurs au Canada?','["CSA B44","CSA B149","CSA A179","CSA W59"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_asc_002','cmt_ascenseur_001','ch_asc_01','Quel composant arrete la cabine si la vitesse depasse la limite?','["Gouverneur de securite","Frein de machinerie","Buffer","Contact de porte"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_asc_003','cmt_ascenseur_001','ch_asc_02','Quelle tension alimente un ascenseur commercial typique?','["600V triphase","120V monophase","12V DC","4800V"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_asc_004','cmt_ascenseur_001','ch_asc_02','Quel est le niveau sonore max permis dans une cabine?','["55 dB","85 dB","70 dB","40 dB"]','A','HARD','MCQ','fr',NOW(),NOW()),
('q_asc_005','cmt_ascenseur_001','ch_asc_03','Quelle course max pour un ascenseur hydraulique?','["6 etages","2 etages","10 etages","20 etages"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_asc_006','cmt_ascenseur_001','ch_asc_03','Quel dispositif empeche la descente incontrollee hydraulique?','["Valve de rupture","Frein de securite","Gouverneur","Buffer"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_asc_007','cmt_ascenseur_001','ch_asc_04','Combien de cables min pour ascenseur a traction?','["3 cables","1 cable","2 cables","6 cables"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_asc_008','cmt_ascenseur_001','ch_asc_04','Diametre typique des cables d''ascenseur?','["8-16 mm","2-4 mm","20-30 mm","40-50 mm"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_asc_009','cmt_ascenseur_001','ch_asc_05','Jeu horizontal max porte paliere/cabine?','["38 mm","50 mm","25 mm","12 mm"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_asc_010','cmt_ascenseur_001','ch_asc_05','Quel dispositif empeche douvrir la porte paliere sans cabine?','["Verrouillage electromecanique","Detecteur infrarouge","Contact de serie","Gouverneur"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_asc_011','cmt_ascenseur_001','ch_asc_06','Tolerance de verticalite des rails de guidage?','["1 mm/m","5 mm/m","0.1 mm/m","10 mm/m"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_asc_012','cmt_ascenseur_001','ch_asc_06','Frequence d''entretien preventif ascenseur?','["Mensuel","Annuel","Aux 6 mois","Aux 2 ans"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_asc_013','cmt_ascenseur_001','ch_asc_07','Essai du gouverneur: distance de declenchement?','["1-2 metres","10-15 metres","0.1 metre","5-6 metres"]','A','HARD','MCQ','fr',NOW(),NOW()),
('q_asc_014','cmt_ascenseur_001','ch_asc_07','Frequence inspection RBQ ascenseur public?','["Aux 6 mois","Aux 12 mois","Aux 3 mois","Aux 2 ans"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_asc_015','cmt_ascenseur_001','ch_asc_08','1ere etape sauvetage passager coince?','["Couper la puissance","Ouvrir la porte","Appeler pompiers","Verifier les cables"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_asc_016','cmt_ascenseur_001','ch_asc_08','Procedure securite avant intervention machinerie?','["Lockout/Tagout","Tirer cables","Debrancher batterie","Enlever contrepoids"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_asc_017','cmt_ascenseur_001','ch_asc_01','Buffer pour ascenseur >2m/s?','["A huile","A ressort","En caoutchouc","Pneumatique"]','A','HARD','MCQ','fr',NOW(),NOW()),
('q_asc_018','cmt_ascenseur_001','ch_asc_02','Fonction de l''alarme incendie sur un ascenseur?','["Rappel au RDC","Arret immediat","Ouverture des portes","Alarme sonore"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_asc_019','cmt_ascenseur_001','ch_asc_03','Huile hydraulique typique ascenseur?','["ISO 32/46/68","SAE 10W30","SAE 5W20","Huile vegetale"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_asc_020','cmt_ascenseur_001','ch_asc_04','Construction de cable typique ascenseur?','["6x19","6x37","8x25","4x10"]','A','HARD','MCQ','fr',NOW(),NOW()),
('q_asc_021','cmt_ascenseur_001','ch_asc_05','Type de porte pour grande ouverture?','["Telecopique","Centre-ouvrant","Laterale","Accordeon"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_asc_022','cmt_ascenseur_001','ch_asc_06','Frequence verifications des cables (tension)?','["Trimestrielle","Quotidienne","Aux 5 ans","Jamais"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_asc_023','cmt_ascenseur_001','ch_asc_07','Document requis apres inspection RBQ?','["Certificat de securite","Permis construire","Licence exploitation","Rapport evaluation"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_asc_024','cmt_ascenseur_001','ch_asc_08','EPI requis pour travail 600V?','["Gants isolants classe 0","Gants cuir","Gants latex","Aucun"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_asc_025','cmt_ascenseur_001','ch_asc_01','Facteur securite min cables?','["12:1","5:1","8:1","20:1"]','A','HARD','MCQ','fr',NOW(),NOW()),
('q_asc_026','cmt_ascenseur_001','ch_asc_02','Type de variateur pour ascenseur moderne?','["VFD (Variable Frequency Drive)","Relais electromecanique","Resistance variable","Transformateur"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_asc_027','cmt_ascenseur_001','ch_asc_03','Pression hydraulique typique ascenseur residentiel?','["50-100 bars","10-20 bars","200-300 bars","5-10 bars"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_asc_028','cmt_ascenseur_001','ch_asc_04','Ascenseur sans salle des machines?','["MRL (Machine Room-Less)","Hydraulique","Traction reducteur","Frein disque"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_asc_029','cmt_ascenseur_001','ch_asc_05','Fermeture du frein de machinerie?','["Mecanique par ressort (fail-safe)","Hydraulique","Electrique","Pneumatique"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_asc_030','cmt_ascenseur_001','ch_asc_06','Outil mesure tension cables?','["Dynamometre","Alesometre","Micrometre","Thermometre"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_asc_031','cmt_ascenseur_001','ch_asc_07','Alarme obligatoire dans cabine?','["Telephone/interphone","Sirene","Lumiere stroboscopique","Haut-parleur"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_asc_032','cmt_ascenseur_001','ch_asc_08','Degagement min fosse ascenseur?','["600 mm","300 mm","1 m","1.5 m"]','A','HARD','MCQ','fr',NOW(),NOW()),
('q_asc_033','cmt_ascenseur_001','ch_asc_01','Norme pour escaliers mecaniques?','["CSA B44","CSA B355","CSA B149","CSA Z432"]','A','HARD','MCQ','fr',NOW(),NOW()),
('q_asc_034','cmt_ascenseur_001','ch_asc_02','Duree min eclairage urgence cabine?','["90 minutes","30 minutes","60 minutes","120 minutes"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_asc_035','cmt_ascenseur_001','ch_asc_03','Avantage ascenseur hydraulique?','["Faible cout installation","Grande vitesse","Faible conso energitique","Aucune limite hauteur"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_asc_036','cmt_ascenseur_001','ch_asc_04','Poids contrepoids traction?','["40-50% charge + cabine","100% charge","25% charge","75% charge"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_asc_037','cmt_ascenseur_001','ch_asc_05','Detecteur reouverture portes ascenseur?','["Infrarouge","Fumee","Chaleur","CO"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_asc_038','cmt_ascenseur_001','ch_asc_06','Cycle modernisation typique ascenseur?','["20-30 ans","5-10 ans","10-15 ans","40-50 ans"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_asc_039','cmt_ascenseur_001','ch_asc_07','Inspection apres modification majeure?','["Reception complete","Visuelle simple","Aucune","Aux 5 ans"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_asc_040','cmt_ascenseur_001','ch_asc_08','Protection travail toit cabine?','["Harnais avec ligne de vie","Casque seulement","Gants","Aucune"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_asc_041','cmt_ascenseur_001','ch_asc_01','Origine du code CSA B44?','["ASME A17.1","NFPA 70","ASTM A653","ISO 9001"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_asc_042','cmt_ascenseur_001','ch_asc_02','Quel systeme envoie la cabine au bon etage?','["Controle microprocesseur","Relais","Manuel","Pneumatique"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_asc_043','cmt_ascenseur_001','ch_asc_03','Valve de controle descente hydraulique?','["Proportionnelle","Trop-plein","Antiretour","Arret"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_asc_044','cmt_ascenseur_001','ch_asc_04','Frein ascenseur moderne?','["Disque a ressort","Tambour","Main","Hydraulique"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_asc_045','cmt_ascenseur_001','ch_asc_05','Jeu vertical max seuil/palier?','["25 mm","38 mm","12 mm","50 mm"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_asc_046','cmt_ascenseur_001','ch_asc_06','Quand remplacer les cables?','["Signes usure ou selon manufacturier","Chaque annee","Jamais","Aux 6 mois"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_asc_047','cmt_ascenseur_001','ch_asc_07','Qui effectue l''inspection RBQ?','["Inspecteur certifie RBQ","Mecanicien","Proprietaire","Ingenieur"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_asc_048','cmt_ascenseur_001','ch_asc_08','Quels risques dans la fosse?','["Espace clos, ecrasement, electro","Chute objets seulement","Incendie","Noyade"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_asc_049','cmt_ascenseur_001','ch_asc_01','Quels composants font partie du circuit de securite?','["Contact porte, gouverneur, fin course","Moteur, pompe, verin","Cable, poulie, contrepoids","Bouton, lumiere, ventilateur"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_asc_050','cmt_ascenseur_001','ch_asc_02','Quel systeme optimise les groupes d''ascenseurs?','["Destination dispatch","Relais","Manuel","Pneumatique"]','A','MEDIUM','MCQ','fr',NOW(),NOW());