INSERT INTO "Question" (id,"tradeId","chapterId",question,options,answer,difficulty,type,locale,"createdAt","updatedAt") VALUES
('q_sst_051','cmt_coordsst_001','ch_sst_01','Question SST 01 #1 - Lois et reglements','["Option A","Option B","Option C","Option D"]','C','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_052','cmt_coordsst_001','ch_sst_01','Question SST 01 #2 - Lois et reglements','["Option A","Option B","Option C","Option D"]','C','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_053','cmt_coordsst_001','ch_sst_01','Question SST 01 #3 - Lois et reglements','["Option A","Option B","Option C","Option D"]','C','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_054','cmt_coordsst_001','ch_sst_01','Question SST 01 #4 - Lois et reglements','["Option A","Option B","Option C","Option D"]','C','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_055','cmt_coordsst_001','ch_sst_01','Question SST 01 #5 - Lois et reglements','["Option A","Option B","Option C","Option D"]','B','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_056','cmt_coordsst_001','ch_sst_01','Question SST 01 #6 - Lois et reglements','["Option A","Option B","Option C","Option D"]','C','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_057','cmt_coordsst_001','ch_sst_01','Question SST 01 #7 - Lois et reglements','["Option A","Option B","Option C","Option D"]','C','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_058','cmt_coordsst_001','ch_sst_01','Question SST 01 #8 - Lois et reglements','["Option A","Option B","Option C","Option D"]','B','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_059','cmt_coordsst_001','ch_sst_01','Question SST 01 #9 - Lois et reglements','["Option A","Option B","Option C","Option D"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_060','cmt_coordsst_001','ch_sst_01','Question SST 01 #10 - Lois et reglements','["Option A","Option B","Option C","Option D"]','D','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_061','cmt_coordsst_001','ch_sst_01','Question SST 01 #11 - Lois et reglements','["Option A","Option B","Option C","Option D"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_062','cmt_coordsst_001','ch_sst_01','Question SST 01 #12 - Lois et reglements','["Option A","Option B","Option C","Option D"]','B','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_063','cmt_coordsst_001','ch_sst_01','Question SST 01 #13 - Lois et reglements','["Option A","Option B","Option C","Option D"]','C','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_064','cmt_coordsst_001','ch_sst_01','Question SST 01 #14 - Lois et reglements','["Option A","Option B","Option C","Option D"]','D','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_065','cmt_coordsst_001','ch_sst_01','Question SST 01 #15 - Lois et reglements','["Option A","Option B","Option C","Option D"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_066','cmt_coordsst_001','ch_sst_01','Question SST 01 #16 - Lois et reglements','["Option A","Option B","Option C","Option D"]','D','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_067','cmt_coordsst_001','ch_sst_01','Question SST 01 #17 - Lois et reglements','["Option A","Option B","Option C","Option D"]','D','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_068','cmt_coordsst_001','ch_sst_01','Question SST 01 #18 - Lois et reglements','["Option A","Option B","Option C","Option D"]','D','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_069','cmt_coordsst_001','ch_sst_01','Question SST 01 #19 - Lois et reglements','["Option A","Option B","Option C","Option D"]','D','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_070','cmt_coordsst_001','ch_sst_01','Question SST 01 #20 - Lois et reglements','["Option A","Option B","Option C","Option D"]','D','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_071','cmt_coordsst_001','ch_sst_01','Question SST 01 #21 - Lois et reglements','["Option A","Option B","Option C","Option D"]','C','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_072','cmt_coordsst_001','ch_sst_01','Question SST 01 #22 - Lois et reglements','["Option A","Option B","Option C","Option D"]','B','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_073','cmt_coordsst_001','ch_sst_01','Question SST 01 #23 - Lois et reglements','["Option A","Option B","Option C","Option D"]','B','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_074','cmt_coordsst_001','ch_sst_01','Question SST 01 #24 - Lois et reglements','["Option A","Option B","Option C","Option D"]','D','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_075','cmt_coordsst_001','ch_sst_01','Question SST 01 #25 - Lois et reglements','["Option A","Option B","Option C","Option D"]','A','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_076','cmt_coordsst_001','ch_sst_01','Question SST 01 #26 - Lois et reglements','["Option A","Option B","Option C","Option D"]','C','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_077','cmt_coordsst_001','ch_sst_01','Question SST 01 #27 - Lois et reglements','["Option A","Option B","Option C","Option D"]','B','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_078','cmt_coordsst_001','ch_sst_01','Question SST 01 #28 - Lois et reglements','["Option A","Option B","Option C","Option D"]','B','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_079','cmt_coordsst_001','ch_sst_01','Question SST 01 #29 - Lois et reglements','["Option A","Option B","Option C","Option D"]','B','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_080','cmt_coordsst_001','ch_sst_01','Question SST 01 #30 - Lois et reglements','["Option A","Option B","Option C","Option D"]','B','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_081','cmt_coordsst_001','ch_sst_01','Question SST 01 #31 - Lois et reglements','["Option A","Option B","Option C","Option D"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_082','cmt_coordsst_001','ch_sst_01','Question SST 01 #32 - Lois et reglements','["Option A","Option B","Option C","Option D"]','C','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_083','cmt_coordsst_001','ch_sst_01','Question SST 01 #33 - Lois et reglements','["Option A","Option B","Option C","Option D"]','D','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_084','cmt_coordsst_001','ch_sst_01','Question SST 01 #34 - Lois et reglements','["Option A","Option B","Option C","Option D"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_085','cmt_coordsst_001','ch_sst_01','Question SST 01 #35 - Lois et reglements','["Option A","Option B","Option C","Option D"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_086','cmt_coordsst_001','ch_sst_01','Question SST 01 #36 - Lois et reglements','["Option A","Option B","Option C","Option D"]','A','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_087','cmt_coordsst_001','ch_sst_01','Question SST 01 #37 - Lois et reglements','["Option A","Option B","Option C","Option D"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_088','cmt_coordsst_001','ch_sst_01','Question SST 01 #38 - Lois et reglements','["Option A","Option B","Option C","Option D"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_089','cmt_coordsst_001','ch_sst_01','Question SST 01 #39 - Lois et reglements','["Option A","Option B","Option C","Option D"]','B','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_090','cmt_coordsst_001','ch_sst_01','Question SST 01 #40 - Lois et reglements','["Option A","Option B","Option C","Option D"]','C','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_091','cmt_coordsst_001','ch_sst_01','Question SST 01 #41 - Lois et reglements','["Option A","Option B","Option C","Option D"]','C','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_092','cmt_coordsst_001','ch_sst_01','Question SST 01 #42 - Lois et reglements','["Option A","Option B","Option C","Option D"]','C','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_093','cmt_coordsst_001','ch_sst_01','Question SST 01 #43 - Lois et reglements','["Option A","Option B","Option C","Option D"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_094','cmt_coordsst_001','ch_sst_01','Question SST 01 #44 - Lois et reglements','["Option A","Option B","Option C","Option D"]','D','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_095','cmt_coordsst_001','ch_sst_01','Question SST 01 #45 - Lois et reglements','["Option A","Option B","Option C","Option D"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_096','cmt_coordsst_001','ch_sst_01','Question SST 01 #46 - Lois et reglements','["Option A","Option B","Option C","Option D"]','D','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_097','cmt_coordsst_001','ch_sst_01','Question SST 01 #47 - Lois et reglements','["Option A","Option B","Option C","Option D"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_098','cmt_coordsst_001','ch_sst_01','Question SST 01 #48 - Lois et reglements','["Option A","Option B","Option C","Option D"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_099','cmt_coordsst_001','ch_sst_01','Question SST 01 #49 - Lois et reglements','["Option A","Option B","Option C","Option D"]','B','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_100','cmt_coordsst_001','ch_sst_01','Question SST 01 #50 - Lois et reglements','["Option A","Option B","Option C","Option D"]','C','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_101','cmt_coordsst_001','ch_sst_01','Question SST 01 #51 - Lois et reglements','["Option A","Option B","Option C","Option D"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_102','cmt_coordsst_001','ch_sst_01','Question SST 01 #52 - Lois et reglements','["Option A","Option B","Option C","Option D"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_103','cmt_coordsst_001','ch_sst_01','Question SST 01 #53 - Lois et reglements','["Option A","Option B","Option C","Option D"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_104','cmt_coordsst_001','ch_sst_01','Question SST 01 #54 - Lois et reglements','["Option A","Option B","Option C","Option D"]','C','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_105','cmt_coordsst_001','ch_sst_01','Question SST 01 #55 - Lois et reglements','["Option A","Option B","Option C","Option D"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_106','cmt_coordsst_001','ch_sst_01','Question SST 01 #56 - Lois et reglements','["Option A","Option B","Option C","Option D"]','D','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_107','cmt_coordsst_001','ch_sst_01','Question SST 01 #57 - Lois et reglements','["Option A","Option B","Option C","Option D"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_108','cmt_coordsst_001','ch_sst_01','Question SST 01 #58 - Lois et reglements','["Option A","Option B","Option C","Option D"]','D','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_109','cmt_coordsst_001','ch_sst_01','Question SST 01 #59 - Lois et reglements','["Option A","Option B","Option C","Option D"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_110','cmt_coordsst_001','ch_sst_01','Question SST 01 #60 - Lois et reglements','["Option A","Option B","Option C","Option D"]','C','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_111','cmt_coordsst_001','ch_sst_02','Question SST 02 #61 - Identification des dangers','["Option A","Option B","Option C","Option D"]','C','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_112','cmt_coordsst_001','ch_sst_02','Question SST 02 #62 - Identification des dangers','["Option A","Option B","Option C","Option D"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_113','cmt_coordsst_001','ch_sst_02','Question SST 02 #63 - Identification des dangers','["Option A","Option B","Option C","Option D"]','B','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_114','cmt_coordsst_001','ch_sst_02','Question SST 02 #64 - Identification des dangers','["Option A","Option B","Option C","Option D"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_115','cmt_coordsst_001','ch_sst_02','Question SST 02 #65 - Identification des dangers','["Option A","Option B","Option C","Option D"]','B','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_116','cmt_coordsst_001','ch_sst_02','Question SST 02 #66 - Identification des dangers','["Option A","Option B","Option C","Option D"]','B','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_117','cmt_coordsst_001','ch_sst_02','Question SST 02 #67 - Identification des dangers','["Option A","Option B","Option C","Option D"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_118','cmt_coordsst_001','ch_sst_02','Question SST 02 #68 - Identification des dangers','["Option A","Option B","Option C","Option D"]','C','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_119','cmt_coordsst_001','ch_sst_02','Question SST 02 #69 - Identification des dangers','["Option A","Option B","Option C","Option D"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_120','cmt_coordsst_001','ch_sst_02','Question SST 02 #70 - Identification des dangers','["Option A","Option B","Option C","Option D"]','D','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_121','cmt_coordsst_001','ch_sst_02','Question SST 02 #71 - Identification des dangers','["Option A","Option B","Option C","Option D"]','D','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_122','cmt_coordsst_001','ch_sst_02','Question SST 02 #72 - Identification des dangers','["Option A","Option B","Option C","Option D"]','C','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_123','cmt_coordsst_001','ch_sst_02','Question SST 02 #73 - Identification des dangers','["Option A","Option B","Option C","Option D"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_124','cmt_coordsst_001','ch_sst_02','Question SST 02 #74 - Identification des dangers','["Option A","Option B","Option C","Option D"]','B','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_125','cmt_coordsst_001','ch_sst_02','Question SST 02 #75 - Identification des dangers','["Option A","Option B","Option C","Option D"]','B','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_126','cmt_coordsst_001','ch_sst_02','Question SST 02 #76 - Identification des dangers','["Option A","Option B","Option C","Option D"]','A','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_127','cmt_coordsst_001','ch_sst_02','Question SST 02 #77 - Identification des dangers','["Option A","Option B","Option C","Option D"]','B','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_128','cmt_coordsst_001','ch_sst_02','Question SST 02 #78 - Identification des dangers','["Option A","Option B","Option C","Option D"]','C','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_129','cmt_coordsst_001','ch_sst_02','Question SST 02 #79 - Identification des dangers','["Option A","Option B","Option C","Option D"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_130','cmt_coordsst_001','ch_sst_02','Question SST 02 #80 - Identification des dangers','["Option A","Option B","Option C","Option D"]','D','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_131','cmt_coordsst_001','ch_sst_02','Question SST 02 #81 - Identification des dangers','["Option A","Option B","Option C","Option D"]','B','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_132','cmt_coordsst_001','ch_sst_02','Question SST 02 #82 - Identification des dangers','["Option A","Option B","Option C","Option D"]','B','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_133','cmt_coordsst_001','ch_sst_02','Question SST 02 #83 - Identification des dangers','["Option A","Option B","Option C","Option D"]','D','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_134','cmt_coordsst_001','ch_sst_02','Question SST 02 #84 - Identification des dangers','["Option A","Option B","Option C","Option D"]','D','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_135','cmt_coordsst_001','ch_sst_02','Question SST 02 #85 - Identification des dangers','["Option A","Option B","Option C","Option D"]','C','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_136','cmt_coordsst_001','ch_sst_02','Question SST 02 #86 - Identification des dangers','["Option A","Option B","Option C","Option D"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_137','cmt_coordsst_001','ch_sst_02','Question SST 02 #87 - Identification des dangers','["Option A","Option B","Option C","Option D"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_138','cmt_coordsst_001','ch_sst_02','Question SST 02 #88 - Identification des dangers','["Option A","Option B","Option C","Option D"]','C','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_139','cmt_coordsst_001','ch_sst_02','Question SST 02 #89 - Identification des dangers','["Option A","Option B","Option C","Option D"]','D','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_140','cmt_coordsst_001','ch_sst_02','Question SST 02 #90 - Identification des dangers','["Option A","Option B","Option C","Option D"]','D','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_141','cmt_coordsst_001','ch_sst_02','Question SST 02 #91 - Identification des dangers','["Option A","Option B","Option C","Option D"]','C','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_142','cmt_coordsst_001','ch_sst_02','Question SST 02 #92 - Identification des dangers','["Option A","Option B","Option C","Option D"]','B','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_143','cmt_coordsst_001','ch_sst_02','Question SST 02 #93 - Identification des dangers','["Option A","Option B","Option C","Option D"]','B','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_144','cmt_coordsst_001','ch_sst_02','Question SST 02 #94 - Identification des dangers','["Option A","Option B","Option C","Option D"]','B','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_145','cmt_coordsst_001','ch_sst_02','Question SST 02 #95 - Identification des dangers','["Option A","Option B","Option C","Option D"]','B','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_146','cmt_coordsst_001','ch_sst_02','Question SST 02 #96 - Identification des dangers','["Option A","Option B","Option C","Option D"]','C','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_147','cmt_coordsst_001','ch_sst_02','Question SST 02 #97 - Identification des dangers','["Option A","Option B","Option C","Option D"]','D','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_148','cmt_coordsst_001','ch_sst_02','Question SST 02 #98 - Identification des dangers','["Option A","Option B","Option C","Option D"]','D','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_149','cmt_coordsst_001','ch_sst_02','Question SST 02 #99 - Identification des dangers','["Option A","Option B","Option C","Option D"]','B','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_150','cmt_coordsst_001','ch_sst_02','Question SST 02 #100 - Identification des dangers','["Option A","Option B","Option C","Option D"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_151','cmt_coordsst_001','ch_sst_02','Question SST 02 #101 - Identification des dangers','["Option A","Option B","Option C","Option D"]','B','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_152','cmt_coordsst_001','ch_sst_02','Question SST 02 #102 - Identification des dangers','["Option A","Option B","Option C","Option D"]','C','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_153','cmt_coordsst_001','ch_sst_02','Question SST 02 #103 - Identification des dangers','["Option A","Option B","Option C","Option D"]','B','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_154','cmt_coordsst_001','ch_sst_02','Question SST 02 #104 - Identification des dangers','["Option A","Option B","Option C","Option D"]','B','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_155','cmt_coordsst_001','ch_sst_02','Question SST 02 #105 - Identification des dangers','["Option A","Option B","Option C","Option D"]','D','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_156','cmt_coordsst_001','ch_sst_02','Question SST 02 #106 - Identification des dangers','["Option A","Option B","Option C","Option D"]','B','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_157','cmt_coordsst_001','ch_sst_02','Question SST 02 #107 - Identification des dangers','["Option A","Option B","Option C","Option D"]','C','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_158','cmt_coordsst_001','ch_sst_02','Question SST 02 #108 - Identification des dangers','["Option A","Option B","Option C","Option D"]','D','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_159','cmt_coordsst_001','ch_sst_02','Question SST 02 #109 - Identification des dangers','["Option A","Option B","Option C","Option D"]','D','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_160','cmt_coordsst_001','ch_sst_02','Question SST 02 #110 - Identification des dangers','["Option A","Option B","Option C","Option D"]','A','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_161','cmt_coordsst_001','ch_sst_02','Question SST 02 #111 - Identification des dangers','["Option A","Option B","Option C","Option D"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_162','cmt_coordsst_001','ch_sst_02','Question SST 02 #112 - Identification des dangers','["Option A","Option B","Option C","Option D"]','D','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_163','cmt_coordsst_001','ch_sst_02','Question SST 02 #113 - Identification des dangers','["Option A","Option B","Option C","Option D"]','C','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_164','cmt_coordsst_001','ch_sst_02','Question SST 02 #114 - Identification des dangers','["Option A","Option B","Option C","Option D"]','C','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_165','cmt_coordsst_001','ch_sst_02','Question SST 02 #115 - Identification des dangers','["Option A","Option B","Option C","Option D"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_166','cmt_coordsst_001','ch_sst_02','Question SST 02 #116 - Identification des dangers','["Option A","Option B","Option C","Option D"]','C','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_167','cmt_coordsst_001','ch_sst_02','Question SST 02 #117 - Identification des dangers','["Option A","Option B","Option C","Option D"]','D','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_168','cmt_coordsst_001','ch_sst_02','Question SST 02 #118 - Identification des dangers','["Option A","Option B","Option C","Option D"]','C','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_169','cmt_coordsst_001','ch_sst_02','Question SST 02 #119 - Identification des dangers','["Option A","Option B","Option C","Option D"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_170','cmt_coordsst_001','ch_sst_02','Question SST 02 #120 - Identification des dangers','["Option A","Option B","Option C","Option D"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_171','cmt_coordsst_001','ch_sst_03','Question SST 03 #121 - Protection contre les chutes','["Option A","Option B","Option C","Option D"]','C','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_172','cmt_coordsst_001','ch_sst_03','Question SST 03 #122 - Protection contre les chutes','["Option A","Option B","Option C","Option D"]','D','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_173','cmt_coordsst_001','ch_sst_03','Question SST 03 #123 - Protection contre les chutes','["Option A","Option B","Option C","Option D"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_174','cmt_coordsst_001','ch_sst_03','Question SST 03 #124 - Protection contre les chutes','["Option A","Option B","Option C","Option D"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_175','cmt_coordsst_001','ch_sst_03','Question SST 03 #125 - Protection contre les chutes','["Option A","Option B","Option C","Option D"]','B','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_176','cmt_coordsst_001','ch_sst_03','Question SST 03 #126 - Protection contre les chutes','["Option A","Option B","Option C","Option D"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_177','cmt_coordsst_001','ch_sst_03','Question SST 03 #127 - Protection contre les chutes','["Option A","Option B","Option C","Option D"]','C','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_178','cmt_coordsst_001','ch_sst_03','Question SST 03 #128 - Protection contre les chutes','["Option A","Option B","Option C","Option D"]','A','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_179','cmt_coordsst_001','ch_sst_03','Question SST 03 #129 - Protection contre les chutes','["Option A","Option B","Option C","Option D"]','D','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_180','cmt_coordsst_001','ch_sst_03','Question SST 03 #130 - Protection contre les chutes','["Option A","Option B","Option C","Option D"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_181','cmt_coordsst_001','ch_sst_03','Question SST 03 #131 - Protection contre les chutes','["Option A","Option B","Option C","Option D"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_182','cmt_coordsst_001','ch_sst_03','Question SST 03 #132 - Protection contre les chutes','["Option A","Option B","Option C","Option D"]','B','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_183','cmt_coordsst_001','ch_sst_03','Question SST 03 #133 - Protection contre les chutes','["Option A","Option B","Option C","Option D"]','C','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_184','cmt_coordsst_001','ch_sst_03','Question SST 03 #134 - Protection contre les chutes','["Option A","Option B","Option C","Option D"]','D','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_185','cmt_coordsst_001','ch_sst_03','Question SST 03 #135 - Protection contre les chutes','["Option A","Option B","Option C","Option D"]','D','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_186','cmt_coordsst_001','ch_sst_03','Question SST 03 #136 - Protection contre les chutes','["Option A","Option B","Option C","Option D"]','C','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_187','cmt_coordsst_001','ch_sst_03','Question SST 03 #137 - Protection contre les chutes','["Option A","Option B","Option C","Option D"]','B','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_188','cmt_coordsst_001','ch_sst_03','Question SST 03 #138 - Protection contre les chutes','["Option A","Option B","Option C","Option D"]','C','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_189','cmt_coordsst_001','ch_sst_03','Question SST 03 #139 - Protection contre les chutes','["Option A","Option B","Option C","Option D"]','C','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_190','cmt_coordsst_001','ch_sst_03','Question SST 03 #140 - Protection contre les chutes','["Option A","Option B","Option C","Option D"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_191','cmt_coordsst_001','ch_sst_03','Question SST 03 #141 - Protection contre les chutes','["Option A","Option B","Option C","Option D"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_192','cmt_coordsst_001','ch_sst_03','Question SST 03 #142 - Protection contre les chutes','["Option A","Option B","Option C","Option D"]','D','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_193','cmt_coordsst_001','ch_sst_03','Question SST 03 #143 - Protection contre les chutes','["Option A","Option B","Option C","Option D"]','D','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_194','cmt_coordsst_001','ch_sst_03','Question SST 03 #144 - Protection contre les chutes','["Option A","Option B","Option C","Option D"]','D','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_195','cmt_coordsst_001','ch_sst_03','Question SST 03 #145 - Protection contre les chutes','["Option A","Option B","Option C","Option D"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_196','cmt_coordsst_001','ch_sst_03','Question SST 03 #146 - Protection contre les chutes','["Option A","Option B","Option C","Option D"]','B','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_197','cmt_coordsst_001','ch_sst_03','Question SST 03 #147 - Protection contre les chutes','["Option A","Option B","Option C","Option D"]','B','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_198','cmt_coordsst_001','ch_sst_03','Question SST 03 #148 - Protection contre les chutes','["Option A","Option B","Option C","Option D"]','C','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_199','cmt_coordsst_001','ch_sst_03','Question SST 03 #149 - Protection contre les chutes','["Option A","Option B","Option C","Option D"]','C','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_200','cmt_coordsst_001','ch_sst_03','Question SST 03 #150 - Protection contre les chutes','["Option A","Option B","Option C","Option D"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_201','cmt_coordsst_001','ch_sst_03','Question SST 03 #151 - Protection contre les chutes','["Option A","Option B","Option C","Option D"]','D','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_202','cmt_coordsst_001','ch_sst_03','Question SST 03 #152 - Protection contre les chutes','["Option A","Option B","Option C","Option D"]','B','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_203','cmt_coordsst_001','ch_sst_03','Question SST 03 #153 - Protection contre les chutes','["Option A","Option B","Option C","Option D"]','D','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_204','cmt_coordsst_001','ch_sst_03','Question SST 03 #154 - Protection contre les chutes','["Option A","Option B","Option C","Option D"]','C','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_205','cmt_coordsst_001','ch_sst_03','Question SST 03 #155 - Protection contre les chutes','["Option A","Option B","Option C","Option D"]','B','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_206','cmt_coordsst_001','ch_sst_03','Question SST 03 #156 - Protection contre les chutes','["Option A","Option B","Option C","Option D"]','C','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_207','cmt_coordsst_001','ch_sst_03','Question SST 03 #157 - Protection contre les chutes','["Option A","Option B","Option C","Option D"]','B','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_208','cmt_coordsst_001','ch_sst_03','Question SST 03 #158 - Protection contre les chutes','["Option A","Option B","Option C","Option D"]','D','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_209','cmt_coordsst_001','ch_sst_03','Question SST 03 #159 - Protection contre les chutes','["Option A","Option B","Option C","Option D"]','B','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_210','cmt_coordsst_001','ch_sst_03','Question SST 03 #160 - Protection contre les chutes','["Option A","Option B","Option C","Option D"]','B','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_211','cmt_coordsst_001','ch_sst_03','Question SST 03 #161 - Protection contre les chutes','["Option A","Option B","Option C","Option D"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_212','cmt_coordsst_001','ch_sst_03','Question SST 03 #162 - Protection contre les chutes','["Option A","Option B","Option C","Option D"]','B','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_213','cmt_coordsst_001','ch_sst_03','Question SST 03 #163 - Protection contre les chutes','["Option A","Option B","Option C","Option D"]','D','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_214','cmt_coordsst_001','ch_sst_03','Question SST 03 #164 - Protection contre les chutes','["Option A","Option B","Option C","Option D"]','B','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_215','cmt_coordsst_001','ch_sst_03','Question SST 03 #165 - Protection contre les chutes','["Option A","Option B","Option C","Option D"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_216','cmt_coordsst_001','ch_sst_03','Question SST 03 #166 - Protection contre les chutes','["Option A","Option B","Option C","Option D"]','D','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_217','cmt_coordsst_001','ch_sst_03','Question SST 03 #167 - Protection contre les chutes','["Option A","Option B","Option C","Option D"]','D','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_218','cmt_coordsst_001','ch_sst_03','Question SST 03 #168 - Protection contre les chutes','["Option A","Option B","Option C","Option D"]','C','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_219','cmt_coordsst_001','ch_sst_03','Question SST 03 #169 - Protection contre les chutes','["Option A","Option B","Option C","Option D"]','A','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_220','cmt_coordsst_001','ch_sst_03','Question SST 03 #170 - Protection contre les chutes','["Option A","Option B","Option C","Option D"]','D','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_221','cmt_coordsst_001','ch_sst_03','Question SST 03 #171 - Protection contre les chutes','["Option A","Option B","Option C","Option D"]','B','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_222','cmt_coordsst_001','ch_sst_03','Question SST 03 #172 - Protection contre les chutes','["Option A","Option B","Option C","Option D"]','D','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_223','cmt_coordsst_001','ch_sst_03','Question SST 03 #173 - Protection contre les chutes','["Option A","Option B","Option C","Option D"]','B','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_224','cmt_coordsst_001','ch_sst_03','Question SST 03 #174 - Protection contre les chutes','["Option A","Option B","Option C","Option D"]','D','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_225','cmt_coordsst_001','ch_sst_03','Question SST 03 #175 - Protection contre les chutes','["Option A","Option B","Option C","Option D"]','D','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_226','cmt_coordsst_001','ch_sst_03','Question SST 03 #176 - Protection contre les chutes','["Option A","Option B","Option C","Option D"]','C','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_227','cmt_coordsst_001','ch_sst_03','Question SST 03 #177 - Protection contre les chutes','["Option A","Option B","Option C","Option D"]','A','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_228','cmt_coordsst_001','ch_sst_03','Question SST 03 #178 - Protection contre les chutes','["Option A","Option B","Option C","Option D"]','B','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_229','cmt_coordsst_001','ch_sst_03','Question SST 03 #179 - Protection contre les chutes','["Option A","Option B","Option C","Option D"]','A','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_230','cmt_coordsst_001','ch_sst_03','Question SST 03 #180 - Protection contre les chutes','["Option A","Option B","Option C","Option D"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_231','cmt_coordsst_001','ch_sst_04','Question SST 04 #181 - Espaces clos','["Option A","Option B","Option C","Option D"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_232','cmt_coordsst_001','ch_sst_04','Question SST 04 #182 - Espaces clos','["Option A","Option B","Option C","Option D"]','C','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_233','cmt_coordsst_001','ch_sst_04','Question SST 04 #183 - Espaces clos','["Option A","Option B","Option C","Option D"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_234','cmt_coordsst_001','ch_sst_04','Question SST 04 #184 - Espaces clos','["Option A","Option B","Option C","Option D"]','C','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_235','cmt_coordsst_001','ch_sst_04','Question SST 04 #185 - Espaces clos','["Option A","Option B","Option C","Option D"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_236','cmt_coordsst_001','ch_sst_04','Question SST 04 #186 - Espaces clos','["Option A","Option B","Option C","Option D"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_237','cmt_coordsst_001','ch_sst_04','Question SST 04 #187 - Espaces clos','["Option A","Option B","Option C","Option D"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_238','cmt_coordsst_001','ch_sst_04','Question SST 04 #188 - Espaces clos','["Option A","Option B","Option C","Option D"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_239','cmt_coordsst_001','ch_sst_04','Question SST 04 #189 - Espaces clos','["Option A","Option B","Option C","Option D"]','D','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_240','cmt_coordsst_001','ch_sst_04','Question SST 04 #190 - Espaces clos','["Option A","Option B","Option C","Option D"]','B','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_241','cmt_coordsst_001','ch_sst_04','Question SST 04 #191 - Espaces clos','["Option A","Option B","Option C","Option D"]','C','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_242','cmt_coordsst_001','ch_sst_04','Question SST 04 #192 - Espaces clos','["Option A","Option B","Option C","Option D"]','B','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_243','cmt_coordsst_001','ch_sst_04','Question SST 04 #193 - Espaces clos','["Option A","Option B","Option C","Option D"]','A','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_244','cmt_coordsst_001','ch_sst_04','Question SST 04 #194 - Espaces clos','["Option A","Option B","Option C","Option D"]','C','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_245','cmt_coordsst_001','ch_sst_04','Question SST 04 #195 - Espaces clos','["Option A","Option B","Option C","Option D"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_246','cmt_coordsst_001','ch_sst_04','Question SST 04 #196 - Espaces clos','["Option A","Option B","Option C","Option D"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_247','cmt_coordsst_001','ch_sst_04','Question SST 04 #197 - Espaces clos','["Option A","Option B","Option C","Option D"]','B','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_248','cmt_coordsst_001','ch_sst_04','Question SST 04 #198 - Espaces clos','["Option A","Option B","Option C","Option D"]','D','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_249','cmt_coordsst_001','ch_sst_04','Question SST 04 #199 - Espaces clos','["Option A","Option B","Option C","Option D"]','D','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_250','cmt_coordsst_001','ch_sst_04','Question SST 04 #200 - Espaces clos','["Option A","Option B","Option C","Option D"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_251','cmt_coordsst_001','ch_sst_04','Question SST 04 #201 - Espaces clos','["Option A","Option B","Option C","Option D"]','B','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_252','cmt_coordsst_001','ch_sst_04','Question SST 04 #202 - Espaces clos','["Option A","Option B","Option C","Option D"]','A','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_253','cmt_coordsst_001','ch_sst_04','Question SST 04 #203 - Espaces clos','["Option A","Option B","Option C","Option D"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_254','cmt_coordsst_001','ch_sst_04','Question SST 04 #204 - Espaces clos','["Option A","Option B","Option C","Option D"]','C','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_255','cmt_coordsst_001','ch_sst_04','Question SST 04 #205 - Espaces clos','["Option A","Option B","Option C","Option D"]','B','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_256','cmt_coordsst_001','ch_sst_04','Question SST 04 #206 - Espaces clos','["Option A","Option B","Option C","Option D"]','C','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_257','cmt_coordsst_001','ch_sst_04','Question SST 04 #207 - Espaces clos','["Option A","Option B","Option C","Option D"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_258','cmt_coordsst_001','ch_sst_04','Question SST 04 #208 - Espaces clos','["Option A","Option B","Option C","Option D"]','D','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_259','cmt_coordsst_001','ch_sst_04','Question SST 04 #209 - Espaces clos','["Option A","Option B","Option C","Option D"]','B','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_260','cmt_coordsst_001','ch_sst_04','Question SST 04 #210 - Espaces clos','["Option A","Option B","Option C","Option D"]','C','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_261','cmt_coordsst_001','ch_sst_04','Question SST 04 #211 - Espaces clos','["Option A","Option B","Option C","Option D"]','B','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_262','cmt_coordsst_001','ch_sst_04','Question SST 04 #212 - Espaces clos','["Option A","Option B","Option C","Option D"]','B','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_263','cmt_coordsst_001','ch_sst_04','Question SST 04 #213 - Espaces clos','["Option A","Option B","Option C","Option D"]','B','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_264','cmt_coordsst_001','ch_sst_04','Question SST 04 #214 - Espaces clos','["Option A","Option B","Option C","Option D"]','B','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_265','cmt_coordsst_001','ch_sst_04','Question SST 04 #215 - Espaces clos','["Option A","Option B","Option C","Option D"]','C','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_266','cmt_coordsst_001','ch_sst_04','Question SST 04 #216 - Espaces clos','["Option A","Option B","Option C","Option D"]','C','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_267','cmt_coordsst_001','ch_sst_04','Question SST 04 #217 - Espaces clos','["Option A","Option B","Option C","Option D"]','C','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_268','cmt_coordsst_001','ch_sst_04','Question SST 04 #218 - Espaces clos','["Option A","Option B","Option C","Option D"]','D','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_269','cmt_coordsst_001','ch_sst_04','Question SST 04 #219 - Espaces clos','["Option A","Option B","Option C","Option D"]','C','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_270','cmt_coordsst_001','ch_sst_04','Question SST 04 #220 - Espaces clos','["Option A","Option B","Option C","Option D"]','C','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_271','cmt_coordsst_001','ch_sst_04','Question SST 04 #221 - Espaces clos','["Option A","Option B","Option C","Option D"]','D','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_272','cmt_coordsst_001','ch_sst_04','Question SST 04 #222 - Espaces clos','["Option A","Option B","Option C","Option D"]','D','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_273','cmt_coordsst_001','ch_sst_04','Question SST 04 #223 - Espaces clos','["Option A","Option B","Option C","Option D"]','D','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_274','cmt_coordsst_001','ch_sst_04','Question SST 04 #224 - Espaces clos','["Option A","Option B","Option C","Option D"]','B','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_275','cmt_coordsst_001','ch_sst_04','Question SST 04 #225 - Espaces clos','["Option A","Option B","Option C","Option D"]','B','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_276','cmt_coordsst_001','ch_sst_04','Question SST 04 #226 - Espaces clos','["Option A","Option B","Option C","Option D"]','D','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_277','cmt_coordsst_001','ch_sst_04','Question SST 04 #227 - Espaces clos','["Option A","Option B","Option C","Option D"]','D','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_278','cmt_coordsst_001','ch_sst_04','Question SST 04 #228 - Espaces clos','["Option A","Option B","Option C","Option D"]','D','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_279','cmt_coordsst_001','ch_sst_04','Question SST 04 #229 - Espaces clos','["Option A","Option B","Option C","Option D"]','D','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_280','cmt_coordsst_001','ch_sst_04','Question SST 04 #230 - Espaces clos','["Option A","Option B","Option C","Option D"]','C','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_281','cmt_coordsst_001','ch_sst_04','Question SST 04 #231 - Espaces clos','["Option A","Option B","Option C","Option D"]','C','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_282','cmt_coordsst_001','ch_sst_04','Question SST 04 #232 - Espaces clos','["Option A","Option B","Option C","Option D"]','B','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_283','cmt_coordsst_001','ch_sst_04','Question SST 04 #233 - Espaces clos','["Option A","Option B","Option C","Option D"]','D','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_284','cmt_coordsst_001','ch_sst_04','Question SST 04 #234 - Espaces clos','["Option A","Option B","Option C","Option D"]','B','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_285','cmt_coordsst_001','ch_sst_04','Question SST 04 #235 - Espaces clos','["Option A","Option B","Option C","Option D"]','C','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_286','cmt_coordsst_001','ch_sst_04','Question SST 04 #236 - Espaces clos','["Option A","Option B","Option C","Option D"]','D','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_287','cmt_coordsst_001','ch_sst_04','Question SST 04 #237 - Espaces clos','["Option A","Option B","Option C","Option D"]','B','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_288','cmt_coordsst_001','ch_sst_04','Question SST 04 #238 - Espaces clos','["Option A","Option B","Option C","Option D"]','B','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_289','cmt_coordsst_001','ch_sst_04','Question SST 04 #239 - Espaces clos','["Option A","Option B","Option C","Option D"]','B','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_290','cmt_coordsst_001','ch_sst_04','Question SST 04 #240 - Espaces clos','["Option A","Option B","Option C","Option D"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_291','cmt_coordsst_001','ch_sst_05','Question SST 05 #241 - Securite electrique','["Option A","Option B","Option C","Option D"]','D','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_292','cmt_coordsst_001','ch_sst_05','Question SST 05 #242 - Securite electrique','["Option A","Option B","Option C","Option D"]','C','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_293','cmt_coordsst_001','ch_sst_05','Question SST 05 #243 - Securite electrique','["Option A","Option B","Option C","Option D"]','B','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_294','cmt_coordsst_001','ch_sst_05','Question SST 05 #244 - Securite electrique','["Option A","Option B","Option C","Option D"]','B','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_295','cmt_coordsst_001','ch_sst_05','Question SST 05 #245 - Securite electrique','["Option A","Option B","Option C","Option D"]','B','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_296','cmt_coordsst_001','ch_sst_05','Question SST 05 #246 - Securite electrique','["Option A","Option B","Option C","Option D"]','C','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_297','cmt_coordsst_001','ch_sst_05','Question SST 05 #247 - Securite electrique','["Option A","Option B","Option C","Option D"]','D','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_298','cmt_coordsst_001','ch_sst_05','Question SST 05 #248 - Securite electrique','["Option A","Option B","Option C","Option D"]','D','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_299','cmt_coordsst_001','ch_sst_05','Question SST 05 #249 - Securite electrique','["Option A","Option B","Option C","Option D"]','C','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_300','cmt_coordsst_001','ch_sst_05','Question SST 05 #250 - Securite electrique','["Option A","Option B","Option C","Option D"]','B','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_301','cmt_coordsst_001','ch_sst_05','Question SST 05 #251 - Securite electrique','["Option A","Option B","Option C","Option D"]','C','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_302','cmt_coordsst_001','ch_sst_05','Question SST 05 #252 - Securite electrique','["Option A","Option B","Option C","Option D"]','C','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_303','cmt_coordsst_001','ch_sst_05','Question SST 05 #253 - Securite electrique','["Option A","Option B","Option C","Option D"]','B','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_304','cmt_coordsst_001','ch_sst_05','Question SST 05 #254 - Securite electrique','["Option A","Option B","Option C","Option D"]','B','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_305','cmt_coordsst_001','ch_sst_05','Question SST 05 #255 - Securite electrique','["Option A","Option B","Option C","Option D"]','B','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_306','cmt_coordsst_001','ch_sst_05','Question SST 05 #256 - Securite electrique','["Option A","Option B","Option C","Option D"]','B','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_307','cmt_coordsst_001','ch_sst_05','Question SST 05 #257 - Securite electrique','["Option A","Option B","Option C","Option D"]','B','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_308','cmt_coordsst_001','ch_sst_05','Question SST 05 #258 - Securite electrique','["Option A","Option B","Option C","Option D"]','A','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_309','cmt_coordsst_001','ch_sst_05','Question SST 05 #259 - Securite electrique','["Option A","Option B","Option C","Option D"]','B','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_310','cmt_coordsst_001','ch_sst_05','Question SST 05 #260 - Securite electrique','["Option A","Option B","Option C","Option D"]','D','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_311','cmt_coordsst_001','ch_sst_05','Question SST 05 #261 - Securite electrique','["Option A","Option B","Option C","Option D"]','D','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_312','cmt_coordsst_001','ch_sst_05','Question SST 05 #262 - Securite electrique','["Option A","Option B","Option C","Option D"]','D','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_313','cmt_coordsst_001','ch_sst_05','Question SST 05 #263 - Securite electrique','["Option A","Option B","Option C","Option D"]','B','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_314','cmt_coordsst_001','ch_sst_05','Question SST 05 #264 - Securite electrique','["Option A","Option B","Option C","Option D"]','D','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_315','cmt_coordsst_001','ch_sst_05','Question SST 05 #265 - Securite electrique','["Option A","Option B","Option C","Option D"]','B','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_316','cmt_coordsst_001','ch_sst_05','Question SST 05 #266 - Securite electrique','["Option A","Option B","Option C","Option D"]','B','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_317','cmt_coordsst_001','ch_sst_05','Question SST 05 #267 - Securite electrique','["Option A","Option B","Option C","Option D"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_318','cmt_coordsst_001','ch_sst_05','Question SST 05 #268 - Securite electrique','["Option A","Option B","Option C","Option D"]','B','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_319','cmt_coordsst_001','ch_sst_05','Question SST 05 #269 - Securite electrique','["Option A","Option B","Option C","Option D"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_320','cmt_coordsst_001','ch_sst_05','Question SST 05 #270 - Securite electrique','["Option A","Option B","Option C","Option D"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_321','cmt_coordsst_001','ch_sst_05','Question SST 05 #271 - Securite electrique','["Option A","Option B","Option C","Option D"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_322','cmt_coordsst_001','ch_sst_05','Question SST 05 #272 - Securite electrique','["Option A","Option B","Option C","Option D"]','A','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_323','cmt_coordsst_001','ch_sst_05','Question SST 05 #273 - Securite electrique','["Option A","Option B","Option C","Option D"]','D','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_324','cmt_coordsst_001','ch_sst_05','Question SST 05 #274 - Securite electrique','["Option A","Option B","Option C","Option D"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_325','cmt_coordsst_001','ch_sst_05','Question SST 05 #275 - Securite electrique','["Option A","Option B","Option C","Option D"]','C','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_326','cmt_coordsst_001','ch_sst_05','Question SST 05 #276 - Securite electrique','["Option A","Option B","Option C","Option D"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_327','cmt_coordsst_001','ch_sst_05','Question SST 05 #277 - Securite electrique','["Option A","Option B","Option C","Option D"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_328','cmt_coordsst_001','ch_sst_05','Question SST 05 #278 - Securite electrique','["Option A","Option B","Option C","Option D"]','C','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_329','cmt_coordsst_001','ch_sst_05','Question SST 05 #279 - Securite electrique','["Option A","Option B","Option C","Option D"]','B','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_330','cmt_coordsst_001','ch_sst_05','Question SST 05 #280 - Securite electrique','["Option A","Option B","Option C","Option D"]','D','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_331','cmt_coordsst_001','ch_sst_05','Question SST 05 #281 - Securite electrique','["Option A","Option B","Option C","Option D"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_332','cmt_coordsst_001','ch_sst_05','Question SST 05 #282 - Securite electrique','["Option A","Option B","Option C","Option D"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_333','cmt_coordsst_001','ch_sst_05','Question SST 05 #283 - Securite electrique','["Option A","Option B","Option C","Option D"]','B','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_334','cmt_coordsst_001','ch_sst_05','Question SST 05 #284 - Securite electrique','["Option A","Option B","Option C","Option D"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_335','cmt_coordsst_001','ch_sst_05','Question SST 05 #285 - Securite electrique','["Option A","Option B","Option C","Option D"]','C','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_336','cmt_coordsst_001','ch_sst_05','Question SST 05 #286 - Securite electrique','["Option A","Option B","Option C","Option D"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_337','cmt_coordsst_001','ch_sst_05','Question SST 05 #287 - Securite electrique','["Option A","Option B","Option C","Option D"]','D','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_338','cmt_coordsst_001','ch_sst_05','Question SST 05 #288 - Securite electrique','["Option A","Option B","Option C","Option D"]','C','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_339','cmt_coordsst_001','ch_sst_05','Question SST 05 #289 - Securite electrique','["Option A","Option B","Option C","Option D"]','D','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_340','cmt_coordsst_001','ch_sst_05','Question SST 05 #290 - Securite electrique','["Option A","Option B","Option C","Option D"]','D','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_341','cmt_coordsst_001','ch_sst_05','Question SST 05 #291 - Securite electrique','["Option A","Option B","Option C","Option D"]','B','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_342','cmt_coordsst_001','ch_sst_05','Question SST 05 #292 - Securite electrique','["Option A","Option B","Option C","Option D"]','B','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_343','cmt_coordsst_001','ch_sst_05','Question SST 05 #293 - Securite electrique','["Option A","Option B","Option C","Option D"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_344','cmt_coordsst_001','ch_sst_05','Question SST 05 #294 - Securite electrique','["Option A","Option B","Option C","Option D"]','B','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_345','cmt_coordsst_001','ch_sst_05','Question SST 05 #295 - Securite electrique','["Option A","Option B","Option C","Option D"]','C','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_346','cmt_coordsst_001','ch_sst_05','Question SST 05 #296 - Securite electrique','["Option A","Option B","Option C","Option D"]','C','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_347','cmt_coordsst_001','ch_sst_05','Question SST 05 #297 - Securite electrique','["Option A","Option B","Option C","Option D"]','B','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_348','cmt_coordsst_001','ch_sst_05','Question SST 05 #298 - Securite electrique','["Option A","Option B","Option C","Option D"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_349','cmt_coordsst_001','ch_sst_05','Question SST 05 #299 - Securite electrique','["Option A","Option B","Option C","Option D"]','B','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_350','cmt_coordsst_001','ch_sst_05','Question SST 05 #300 - Securite electrique','["Option A","Option B","Option C","Option D"]','B','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_351','cmt_coordsst_001','ch_sst_06','Question SST 06 #301 - Incendie et urgences','["Option A","Option B","Option C","Option D"]','B','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_352','cmt_coordsst_001','ch_sst_06','Question SST 06 #302 - Incendie et urgences','["Option A","Option B","Option C","Option D"]','B','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_353','cmt_coordsst_001','ch_sst_06','Question SST 06 #303 - Incendie et urgences','["Option A","Option B","Option C","Option D"]','C','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_354','cmt_coordsst_001','ch_sst_06','Question SST 06 #304 - Incendie et urgences','["Option A","Option B","Option C","Option D"]','B','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_355','cmt_coordsst_001','ch_sst_06','Question SST 06 #305 - Incendie et urgences','["Option A","Option B","Option C","Option D"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_356','cmt_coordsst_001','ch_sst_06','Question SST 06 #306 - Incendie et urgences','["Option A","Option B","Option C","Option D"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_357','cmt_coordsst_001','ch_sst_06','Question SST 06 #307 - Incendie et urgences','["Option A","Option B","Option C","Option D"]','B','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_358','cmt_coordsst_001','ch_sst_06','Question SST 06 #308 - Incendie et urgences','["Option A","Option B","Option C","Option D"]','D','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_359','cmt_coordsst_001','ch_sst_06','Question SST 06 #309 - Incendie et urgences','["Option A","Option B","Option C","Option D"]','A','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_360','cmt_coordsst_001','ch_sst_06','Question SST 06 #310 - Incendie et urgences','["Option A","Option B","Option C","Option D"]','C','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_361','cmt_coordsst_001','ch_sst_06','Question SST 06 #311 - Incendie et urgences','["Option A","Option B","Option C","Option D"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_362','cmt_coordsst_001','ch_sst_06','Question SST 06 #312 - Incendie et urgences','["Option A","Option B","Option C","Option D"]','C','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_363','cmt_coordsst_001','ch_sst_06','Question SST 06 #313 - Incendie et urgences','["Option A","Option B","Option C","Option D"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_364','cmt_coordsst_001','ch_sst_06','Question SST 06 #314 - Incendie et urgences','["Option A","Option B","Option C","Option D"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_365','cmt_coordsst_001','ch_sst_06','Question SST 06 #315 - Incendie et urgences','["Option A","Option B","Option C","Option D"]','C','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_366','cmt_coordsst_001','ch_sst_06','Question SST 06 #316 - Incendie et urgences','["Option A","Option B","Option C","Option D"]','B','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_367','cmt_coordsst_001','ch_sst_06','Question SST 06 #317 - Incendie et urgences','["Option A","Option B","Option C","Option D"]','C','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_368','cmt_coordsst_001','ch_sst_06','Question SST 06 #318 - Incendie et urgences','["Option A","Option B","Option C","Option D"]','B','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_369','cmt_coordsst_001','ch_sst_06','Question SST 06 #319 - Incendie et urgences','["Option A","Option B","Option C","Option D"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_370','cmt_coordsst_001','ch_sst_06','Question SST 06 #320 - Incendie et urgences','["Option A","Option B","Option C","Option D"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_371','cmt_coordsst_001','ch_sst_06','Question SST 06 #321 - Incendie et urgences','["Option A","Option B","Option C","Option D"]','D','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_372','cmt_coordsst_001','ch_sst_06','Question SST 06 #322 - Incendie et urgences','["Option A","Option B","Option C","Option D"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_373','cmt_coordsst_001','ch_sst_06','Question SST 06 #323 - Incendie et urgences','["Option A","Option B","Option C","Option D"]','B','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_374','cmt_coordsst_001','ch_sst_06','Question SST 06 #324 - Incendie et urgences','["Option A","Option B","Option C","Option D"]','C','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_375','cmt_coordsst_001','ch_sst_06','Question SST 06 #325 - Incendie et urgences','["Option A","Option B","Option C","Option D"]','C','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_376','cmt_coordsst_001','ch_sst_06','Question SST 06 #326 - Incendie et urgences','["Option A","Option B","Option C","Option D"]','C','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_377','cmt_coordsst_001','ch_sst_06','Question SST 06 #327 - Incendie et urgences','["Option A","Option B","Option C","Option D"]','C','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_378','cmt_coordsst_001','ch_sst_06','Question SST 06 #328 - Incendie et urgences','["Option A","Option B","Option C","Option D"]','C','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_379','cmt_coordsst_001','ch_sst_06','Question SST 06 #329 - Incendie et urgences','["Option A","Option B","Option C","Option D"]','B','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_380','cmt_coordsst_001','ch_sst_06','Question SST 06 #330 - Incendie et urgences','["Option A","Option B","Option C","Option D"]','B','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_381','cmt_coordsst_001','ch_sst_06','Question SST 06 #331 - Incendie et urgences','["Option A","Option B","Option C","Option D"]','D','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_382','cmt_coordsst_001','ch_sst_06','Question SST 06 #332 - Incendie et urgences','["Option A","Option B","Option C","Option D"]','D','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_383','cmt_coordsst_001','ch_sst_06','Question SST 06 #333 - Incendie et urgences','["Option A","Option B","Option C","Option D"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_384','cmt_coordsst_001','ch_sst_06','Question SST 06 #334 - Incendie et urgences','["Option A","Option B","Option C","Option D"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_385','cmt_coordsst_001','ch_sst_06','Question SST 06 #335 - Incendie et urgences','["Option A","Option B","Option C","Option D"]','B','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_386','cmt_coordsst_001','ch_sst_06','Question SST 06 #336 - Incendie et urgences','["Option A","Option B","Option C","Option D"]','D','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_387','cmt_coordsst_001','ch_sst_06','Question SST 06 #337 - Incendie et urgences','["Option A","Option B","Option C","Option D"]','C','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_388','cmt_coordsst_001','ch_sst_06','Question SST 06 #338 - Incendie et urgences','["Option A","Option B","Option C","Option D"]','C','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_389','cmt_coordsst_001','ch_sst_06','Question SST 06 #339 - Incendie et urgences','["Option A","Option B","Option C","Option D"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_390','cmt_coordsst_001','ch_sst_06','Question SST 06 #340 - Incendie et urgences','["Option A","Option B","Option C","Option D"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_391','cmt_coordsst_001','ch_sst_06','Question SST 06 #341 - Incendie et urgences','["Option A","Option B","Option C","Option D"]','D','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_392','cmt_coordsst_001','ch_sst_06','Question SST 06 #342 - Incendie et urgences','["Option A","Option B","Option C","Option D"]','D','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_393','cmt_coordsst_001','ch_sst_06','Question SST 06 #343 - Incendie et urgences','["Option A","Option B","Option C","Option D"]','B','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_394','cmt_coordsst_001','ch_sst_06','Question SST 06 #344 - Incendie et urgences','["Option A","Option B","Option C","Option D"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_395','cmt_coordsst_001','ch_sst_06','Question SST 06 #345 - Incendie et urgences','["Option A","Option B","Option C","Option D"]','C','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_396','cmt_coordsst_001','ch_sst_06','Question SST 06 #346 - Incendie et urgences','["Option A","Option B","Option C","Option D"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_397','cmt_coordsst_001','ch_sst_06','Question SST 06 #347 - Incendie et urgences','["Option A","Option B","Option C","Option D"]','B','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_398','cmt_coordsst_001','ch_sst_06','Question SST 06 #348 - Incendie et urgences','["Option A","Option B","Option C","Option D"]','B','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_399','cmt_coordsst_001','ch_sst_06','Question SST 06 #349 - Incendie et urgences','["Option A","Option B","Option C","Option D"]','D','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_400','cmt_coordsst_001','ch_sst_06','Question SST 06 #350 - Incendie et urgences','["Option A","Option B","Option C","Option D"]','C','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_401','cmt_coordsst_001','ch_sst_06','Question SST 06 #351 - Incendie et urgences','["Option A","Option B","Option C","Option D"]','C','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_402','cmt_coordsst_001','ch_sst_06','Question SST 06 #352 - Incendie et urgences','["Option A","Option B","Option C","Option D"]','B','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_403','cmt_coordsst_001','ch_sst_06','Question SST 06 #353 - Incendie et urgences','["Option A","Option B","Option C","Option D"]','D','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_404','cmt_coordsst_001','ch_sst_06','Question SST 06 #354 - Incendie et urgences','["Option A","Option B","Option C","Option D"]','C','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_405','cmt_coordsst_001','ch_sst_06','Question SST 06 #355 - Incendie et urgences','["Option A","Option B","Option C","Option D"]','A','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_406','cmt_coordsst_001','ch_sst_06','Question SST 06 #356 - Incendie et urgences','["Option A","Option B","Option C","Option D"]','B','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_407','cmt_coordsst_001','ch_sst_06','Question SST 06 #357 - Incendie et urgences','["Option A","Option B","Option C","Option D"]','C','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_408','cmt_coordsst_001','ch_sst_06','Question SST 06 #358 - Incendie et urgences','["Option A","Option B","Option C","Option D"]','C','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_409','cmt_coordsst_001','ch_sst_06','Question SST 06 #359 - Incendie et urgences','["Option A","Option B","Option C","Option D"]','D','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_410','cmt_coordsst_001','ch_sst_06','Question SST 06 #360 - Incendie et urgences','["Option A","Option B","Option C","Option D"]','B','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_411','cmt_coordsst_001','ch_sst_07','Question SST 07 #361 - Surveillance sante et ergonomie','["Option A","Option B","Option C","Option D"]','C','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_412','cmt_coordsst_001','ch_sst_07','Question SST 07 #362 - Surveillance sante et ergonomie','["Option A","Option B","Option C","Option D"]','B','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_413','cmt_coordsst_001','ch_sst_07','Question SST 07 #363 - Surveillance sante et ergonomie','["Option A","Option B","Option C","Option D"]','C','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_414','cmt_coordsst_001','ch_sst_07','Question SST 07 #364 - Surveillance sante et ergonomie','["Option A","Option B","Option C","Option D"]','D','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_415','cmt_coordsst_001','ch_sst_07','Question SST 07 #365 - Surveillance sante et ergonomie','["Option A","Option B","Option C","Option D"]','B','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_416','cmt_coordsst_001','ch_sst_07','Question SST 07 #366 - Surveillance sante et ergonomie','["Option A","Option B","Option C","Option D"]','B','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_417','cmt_coordsst_001','ch_sst_07','Question SST 07 #367 - Surveillance sante et ergonomie','["Option A","Option B","Option C","Option D"]','B','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_418','cmt_coordsst_001','ch_sst_07','Question SST 07 #368 - Surveillance sante et ergonomie','["Option A","Option B","Option C","Option D"]','B','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_419','cmt_coordsst_001','ch_sst_07','Question SST 07 #369 - Surveillance sante et ergonomie','["Option A","Option B","Option C","Option D"]','C','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_420','cmt_coordsst_001','ch_sst_07','Question SST 07 #370 - Surveillance sante et ergonomie','["Option A","Option B","Option C","Option D"]','D','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_421','cmt_coordsst_001','ch_sst_07','Question SST 07 #371 - Surveillance sante et ergonomie','["Option A","Option B","Option C","Option D"]','D','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_422','cmt_coordsst_001','ch_sst_07','Question SST 07 #372 - Surveillance sante et ergonomie','["Option A","Option B","Option C","Option D"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_423','cmt_coordsst_001','ch_sst_07','Question SST 07 #373 - Surveillance sante et ergonomie','["Option A","Option B","Option C","Option D"]','B','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_424','cmt_coordsst_001','ch_sst_07','Question SST 07 #374 - Surveillance sante et ergonomie','["Option A","Option B","Option C","Option D"]','C','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_425','cmt_coordsst_001','ch_sst_07','Question SST 07 #375 - Surveillance sante et ergonomie','["Option A","Option B","Option C","Option D"]','D','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_426','cmt_coordsst_001','ch_sst_07','Question SST 07 #376 - Surveillance sante et ergonomie','["Option A","Option B","Option C","Option D"]','B','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_427','cmt_coordsst_001','ch_sst_07','Question SST 07 #377 - Surveillance sante et ergonomie','["Option A","Option B","Option C","Option D"]','B','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_428','cmt_coordsst_001','ch_sst_07','Question SST 07 #378 - Surveillance sante et ergonomie','["Option A","Option B","Option C","Option D"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_429','cmt_coordsst_001','ch_sst_07','Question SST 07 #379 - Surveillance sante et ergonomie','["Option A","Option B","Option C","Option D"]','D','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_430','cmt_coordsst_001','ch_sst_07','Question SST 07 #380 - Surveillance sante et ergonomie','["Option A","Option B","Option C","Option D"]','C','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_431','cmt_coordsst_001','ch_sst_07','Question SST 07 #381 - Surveillance sante et ergonomie','["Option A","Option B","Option C","Option D"]','D','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_432','cmt_coordsst_001','ch_sst_07','Question SST 07 #382 - Surveillance sante et ergonomie','["Option A","Option B","Option C","Option D"]','C','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_433','cmt_coordsst_001','ch_sst_07','Question SST 07 #383 - Surveillance sante et ergonomie','["Option A","Option B","Option C","Option D"]','C','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_434','cmt_coordsst_001','ch_sst_07','Question SST 07 #384 - Surveillance sante et ergonomie','["Option A","Option B","Option C","Option D"]','C','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_435','cmt_coordsst_001','ch_sst_07','Question SST 07 #385 - Surveillance sante et ergonomie','["Option A","Option B","Option C","Option D"]','C','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_436','cmt_coordsst_001','ch_sst_07','Question SST 07 #386 - Surveillance sante et ergonomie','["Option A","Option B","Option C","Option D"]','B','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_437','cmt_coordsst_001','ch_sst_07','Question SST 07 #387 - Surveillance sante et ergonomie','["Option A","Option B","Option C","Option D"]','C','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_438','cmt_coordsst_001','ch_sst_07','Question SST 07 #388 - Surveillance sante et ergonomie','["Option A","Option B","Option C","Option D"]','D','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_439','cmt_coordsst_001','ch_sst_07','Question SST 07 #389 - Surveillance sante et ergonomie','["Option A","Option B","Option C","Option D"]','A','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_440','cmt_coordsst_001','ch_sst_07','Question SST 07 #390 - Surveillance sante et ergonomie','["Option A","Option B","Option C","Option D"]','D','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_441','cmt_coordsst_001','ch_sst_07','Question SST 07 #391 - Surveillance sante et ergonomie','["Option A","Option B","Option C","Option D"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_442','cmt_coordsst_001','ch_sst_07','Question SST 07 #392 - Surveillance sante et ergonomie','["Option A","Option B","Option C","Option D"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_443','cmt_coordsst_001','ch_sst_07','Question SST 07 #393 - Surveillance sante et ergonomie','["Option A","Option B","Option C","Option D"]','C','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_444','cmt_coordsst_001','ch_sst_07','Question SST 07 #394 - Surveillance sante et ergonomie','["Option A","Option B","Option C","Option D"]','D','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_445','cmt_coordsst_001','ch_sst_07','Question SST 07 #395 - Surveillance sante et ergonomie','["Option A","Option B","Option C","Option D"]','C','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_446','cmt_coordsst_001','ch_sst_07','Question SST 07 #396 - Surveillance sante et ergonomie','["Option A","Option B","Option C","Option D"]','A','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_447','cmt_coordsst_001','ch_sst_07','Question SST 07 #397 - Surveillance sante et ergonomie','["Option A","Option B","Option C","Option D"]','D','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_448','cmt_coordsst_001','ch_sst_07','Question SST 07 #398 - Surveillance sante et ergonomie','["Option A","Option B","Option C","Option D"]','C','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_449','cmt_coordsst_001','ch_sst_07','Question SST 07 #399 - Surveillance sante et ergonomie','["Option A","Option B","Option C","Option D"]','B','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_450','cmt_coordsst_001','ch_sst_07','Question SST 07 #400 - Surveillance sante et ergonomie','["Option A","Option B","Option C","Option D"]','D','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_451','cmt_coordsst_001','ch_sst_07','Question SST 07 #401 - Surveillance sante et ergonomie','["Option A","Option B","Option C","Option D"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_452','cmt_coordsst_001','ch_sst_07','Question SST 07 #402 - Surveillance sante et ergonomie','["Option A","Option B","Option C","Option D"]','A','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_453','cmt_coordsst_001','ch_sst_07','Question SST 07 #403 - Surveillance sante et ergonomie','["Option A","Option B","Option C","Option D"]','C','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_454','cmt_coordsst_001','ch_sst_07','Question SST 07 #404 - Surveillance sante et ergonomie','["Option A","Option B","Option C","Option D"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_455','cmt_coordsst_001','ch_sst_07','Question SST 07 #405 - Surveillance sante et ergonomie','["Option A","Option B","Option C","Option D"]','B','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_456','cmt_coordsst_001','ch_sst_07','Question SST 07 #406 - Surveillance sante et ergonomie','["Option A","Option B","Option C","Option D"]','B','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_457','cmt_coordsst_001','ch_sst_07','Question SST 07 #407 - Surveillance sante et ergonomie','["Option A","Option B","Option C","Option D"]','C','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_458','cmt_coordsst_001','ch_sst_07','Question SST 07 #408 - Surveillance sante et ergonomie','["Option A","Option B","Option C","Option D"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_459','cmt_coordsst_001','ch_sst_07','Question SST 07 #409 - Surveillance sante et ergonomie','["Option A","Option B","Option C","Option D"]','D','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_460','cmt_coordsst_001','ch_sst_07','Question SST 07 #410 - Surveillance sante et ergonomie','["Option A","Option B","Option C","Option D"]','B','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_461','cmt_coordsst_001','ch_sst_07','Question SST 07 #411 - Surveillance sante et ergonomie','["Option A","Option B","Option C","Option D"]','D','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_462','cmt_coordsst_001','ch_sst_07','Question SST 07 #412 - Surveillance sante et ergonomie','["Option A","Option B","Option C","Option D"]','C','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_463','cmt_coordsst_001','ch_sst_07','Question SST 07 #413 - Surveillance sante et ergonomie','["Option A","Option B","Option C","Option D"]','C','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_464','cmt_coordsst_001','ch_sst_07','Question SST 07 #414 - Surveillance sante et ergonomie','["Option A","Option B","Option C","Option D"]','B','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_465','cmt_coordsst_001','ch_sst_07','Question SST 07 #415 - Surveillance sante et ergonomie','["Option A","Option B","Option C","Option D"]','D','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_466','cmt_coordsst_001','ch_sst_07','Question SST 07 #416 - Surveillance sante et ergonomie','["Option A","Option B","Option C","Option D"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_467','cmt_coordsst_001','ch_sst_07','Question SST 07 #417 - Surveillance sante et ergonomie','["Option A","Option B","Option C","Option D"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_468','cmt_coordsst_001','ch_sst_07','Question SST 07 #418 - Surveillance sante et ergonomie','["Option A","Option B","Option C","Option D"]','B','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_469','cmt_coordsst_001','ch_sst_07','Question SST 07 #419 - Surveillance sante et ergonomie','["Option A","Option B","Option C","Option D"]','A','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_470','cmt_coordsst_001','ch_sst_07','Question SST 07 #420 - Surveillance sante et ergonomie','["Option A","Option B","Option C","Option D"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_471','cmt_coordsst_001','ch_sst_08','Question SST 08 #421 - Inspection et enquete','["Option A","Option B","Option C","Option D"]','A','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_472','cmt_coordsst_001','ch_sst_08','Question SST 08 #422 - Inspection et enquete','["Option A","Option B","Option C","Option D"]','C','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_473','cmt_coordsst_001','ch_sst_08','Question SST 08 #423 - Inspection et enquete','["Option A","Option B","Option C","Option D"]','B','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_474','cmt_coordsst_001','ch_sst_08','Question SST 08 #424 - Inspection et enquete','["Option A","Option B","Option C","Option D"]','D','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_475','cmt_coordsst_001','ch_sst_08','Question SST 08 #425 - Inspection et enquete','["Option A","Option B","Option C","Option D"]','A','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_476','cmt_coordsst_001','ch_sst_08','Question SST 08 #426 - Inspection et enquete','["Option A","Option B","Option C","Option D"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_477','cmt_coordsst_001','ch_sst_08','Question SST 08 #427 - Inspection et enquete','["Option A","Option B","Option C","Option D"]','D','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_478','cmt_coordsst_001','ch_sst_08','Question SST 08 #428 - Inspection et enquete','["Option A","Option B","Option C","Option D"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_479','cmt_coordsst_001','ch_sst_08','Question SST 08 #429 - Inspection et enquete','["Option A","Option B","Option C","Option D"]','C','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_480','cmt_coordsst_001','ch_sst_08','Question SST 08 #430 - Inspection et enquete','["Option A","Option B","Option C","Option D"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_481','cmt_coordsst_001','ch_sst_08','Question SST 08 #431 - Inspection et enquete','["Option A","Option B","Option C","Option D"]','A','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_482','cmt_coordsst_001','ch_sst_08','Question SST 08 #432 - Inspection et enquete','["Option A","Option B","Option C","Option D"]','B','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_483','cmt_coordsst_001','ch_sst_08','Question SST 08 #433 - Inspection et enquete','["Option A","Option B","Option C","Option D"]','A','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_484','cmt_coordsst_001','ch_sst_08','Question SST 08 #434 - Inspection et enquete','["Option A","Option B","Option C","Option D"]','D','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_485','cmt_coordsst_001','ch_sst_08','Question SST 08 #435 - Inspection et enquete','["Option A","Option B","Option C","Option D"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_486','cmt_coordsst_001','ch_sst_08','Question SST 08 #436 - Inspection et enquete','["Option A","Option B","Option C","Option D"]','C','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_487','cmt_coordsst_001','ch_sst_08','Question SST 08 #437 - Inspection et enquete','["Option A","Option B","Option C","Option D"]','B','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_488','cmt_coordsst_001','ch_sst_08','Question SST 08 #438 - Inspection et enquete','["Option A","Option B","Option C","Option D"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_489','cmt_coordsst_001','ch_sst_08','Question SST 08 #439 - Inspection et enquete','["Option A","Option B","Option C","Option D"]','D','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_490','cmt_coordsst_001','ch_sst_08','Question SST 08 #440 - Inspection et enquete','["Option A","Option B","Option C","Option D"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_491','cmt_coordsst_001','ch_sst_08','Question SST 08 #441 - Inspection et enquete','["Option A","Option B","Option C","Option D"]','D','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_492','cmt_coordsst_001','ch_sst_08','Question SST 08 #442 - Inspection et enquete','["Option A","Option B","Option C","Option D"]','A','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_493','cmt_coordsst_001','ch_sst_08','Question SST 08 #443 - Inspection et enquete','["Option A","Option B","Option C","Option D"]','D','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_494','cmt_coordsst_001','ch_sst_08','Question SST 08 #444 - Inspection et enquete','["Option A","Option B","Option C","Option D"]','C','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_495','cmt_coordsst_001','ch_sst_08','Question SST 08 #445 - Inspection et enquete','["Option A","Option B","Option C","Option D"]','D','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_496','cmt_coordsst_001','ch_sst_08','Question SST 08 #446 - Inspection et enquete','["Option A","Option B","Option C","Option D"]','D','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_497','cmt_coordsst_001','ch_sst_08','Question SST 08 #447 - Inspection et enquete','["Option A","Option B","Option C","Option D"]','B','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_498','cmt_coordsst_001','ch_sst_08','Question SST 08 #448 - Inspection et enquete','["Option A","Option B","Option C","Option D"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_499','cmt_coordsst_001','ch_sst_08','Question SST 08 #449 - Inspection et enquete','["Option A","Option B","Option C","Option D"]','A','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_500','cmt_coordsst_001','ch_sst_08','Question SST 08 #450 - Inspection et enquete','["Option A","Option B","Option C","Option D"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_501','cmt_coordsst_001','ch_sst_08','Question SST 08 #451 - Inspection et enquete','["Option A","Option B","Option C","Option D"]','C','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_502','cmt_coordsst_001','ch_sst_08','Question SST 08 #452 - Inspection et enquete','["Option A","Option B","Option C","Option D"]','C','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_503','cmt_coordsst_001','ch_sst_08','Question SST 08 #453 - Inspection et enquete','["Option A","Option B","Option C","Option D"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_504','cmt_coordsst_001','ch_sst_08','Question SST 08 #454 - Inspection et enquete','["Option A","Option B","Option C","Option D"]','B','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_505','cmt_coordsst_001','ch_sst_08','Question SST 08 #455 - Inspection et enquete','["Option A","Option B","Option C","Option D"]','A','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_506','cmt_coordsst_001','ch_sst_08','Question SST 08 #456 - Inspection et enquete','["Option A","Option B","Option C","Option D"]','C','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_507','cmt_coordsst_001','ch_sst_08','Question SST 08 #457 - Inspection et enquete','["Option A","Option B","Option C","Option D"]','B','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_508','cmt_coordsst_001','ch_sst_08','Question SST 08 #458 - Inspection et enquete','["Option A","Option B","Option C","Option D"]','C','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_509','cmt_coordsst_001','ch_sst_08','Question SST 08 #459 - Inspection et enquete','["Option A","Option B","Option C","Option D"]','C','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_510','cmt_coordsst_001','ch_sst_08','Question SST 08 #460 - Inspection et enquete','["Option A","Option B","Option C","Option D"]','C','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_511','cmt_coordsst_001','ch_sst_08','Question SST 08 #461 - Inspection et enquete','["Option A","Option B","Option C","Option D"]','B','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_512','cmt_coordsst_001','ch_sst_08','Question SST 08 #462 - Inspection et enquete','["Option A","Option B","Option C","Option D"]','C','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_513','cmt_coordsst_001','ch_sst_08','Question SST 08 #463 - Inspection et enquete','["Option A","Option B","Option C","Option D"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_514','cmt_coordsst_001','ch_sst_08','Question SST 08 #464 - Inspection et enquete','["Option A","Option B","Option C","Option D"]','B','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_515','cmt_coordsst_001','ch_sst_08','Question SST 08 #465 - Inspection et enquete','["Option A","Option B","Option C","Option D"]','D','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_516','cmt_coordsst_001','ch_sst_08','Question SST 08 #466 - Inspection et enquete','["Option A","Option B","Option C","Option D"]','B','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_517','cmt_coordsst_001','ch_sst_08','Question SST 08 #467 - Inspection et enquete','["Option A","Option B","Option C","Option D"]','D','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_518','cmt_coordsst_001','ch_sst_08','Question SST 08 #468 - Inspection et enquete','["Option A","Option B","Option C","Option D"]','B','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_519','cmt_coordsst_001','ch_sst_08','Question SST 08 #469 - Inspection et enquete','["Option A","Option B","Option C","Option D"]','B','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_520','cmt_coordsst_001','ch_sst_08','Question SST 08 #470 - Inspection et enquete','["Option A","Option B","Option C","Option D"]','C','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_521','cmt_coordsst_001','ch_sst_08','Question SST 08 #471 - Inspection et enquete','["Option A","Option B","Option C","Option D"]','A','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_522','cmt_coordsst_001','ch_sst_08','Question SST 08 #472 - Inspection et enquete','["Option A","Option B","Option C","Option D"]','D','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_523','cmt_coordsst_001','ch_sst_08','Question SST 08 #473 - Inspection et enquete','["Option A","Option B","Option C","Option D"]','D','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_524','cmt_coordsst_001','ch_sst_08','Question SST 08 #474 - Inspection et enquete','["Option A","Option B","Option C","Option D"]','A','HARD','MCQ','fr',NOW(),NOW()),
('q_sst_525','cmt_coordsst_001','ch_sst_08','Question SST 08 #475 - Inspection et enquete','["Option A","Option B","Option C","Option D"]','C','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_526','cmt_coordsst_001','ch_sst_08','Question SST 08 #476 - Inspection et enquete','["Option A","Option B","Option C","Option D"]','C','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_527','cmt_coordsst_001','ch_sst_08','Question SST 08 #477 - Inspection et enquete','["Option A","Option B","Option C","Option D"]','D','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_528','cmt_coordsst_001','ch_sst_08','Question SST 08 #478 - Inspection et enquete','["Option A","Option B","Option C","Option D"]','D','MEDIUM','MCQ','fr',NOW(),NOW()),
('q_sst_529','cmt_coordsst_001','ch_sst_08','Question SST 08 #479 - Inspection et enquete','["Option A","Option B","Option C","Option D"]','D','EASY','MCQ','fr',NOW(),NOW()),
('q_sst_530','cmt_coordsst_001','ch_sst_08','Question SST 08 #480 - Inspection et enquete','["Option A","Option B","Option C","Option D"]','C','MEDIUM','MCQ','fr',NOW(),NOW());